import Link from "next/link";
import { formatMetric, formatPercentile, type ComparisonEntity, type ComparisonPack } from "@/lib/analytics/comparisonData";
import { matchupInsights, sharedMeasuredAxisCount } from "@/lib/analytics/matchupInsights";
import { mlbAtlasFamily } from "@/lib/analytics/mlbAtlasFamily";
import { type TennisSurface } from "@/lib/analytics/tennisSurfaceComparison";
import { TennisSurfaceComparison } from "./TennisSurfaceComparison";
import { PitchCountComparison } from "./PitchCountComparison";
import { PitchResultComparison } from "./PitchResultComparison";
import { SoccerVenueComparison } from "./SoccerVenueComparison";
import { MetricRow, ProfileHeading } from "./CompareResultParts";
import { sharedPercentileLadder } from "@/lib/analytics/percentileLadder";
import { PercentileBar } from "@/components/analytics/PercentileBar";

function publicPath(path: string): string { return `${process.env.NEXT_PUBLIC_BASE_PATH || ""}/data/showcase/${path}`; }
function rankedCount(pack: ComparisonPack, field: string): number | undefined { const value = pack.nRankedByMetric?.[field]; return typeof value === "number" && Number.isInteger(value) && value > 0 ? value : undefined; }

export function ComparisonResults({ pack, a, b, manifest, sport, surface, onSurfaceChange }: { pack: ComparisonPack; a: ComparisonEntity; b: ComparisonEntity; manifest: string; sport?: string; surface: TennisSurface; onSurfaceChange: (surface: TennisSurface) => void }) {
  const aFamily = pack.key === "mlb_pitch" ? mlbAtlasFamily(a.sourceEntity) : undefined;
  const bFamily = pack.key === "mlb_pitch" ? mlbAtlasFamily(b.sourceEntity) : undefined;
  const mixedMlbAtlas = pack.key === "mlb_pitch" && (!aFamily || aFamily !== bFamily);
  const rawMlbAtlas = pack.key === "mlb_pitch" && !mixedMlbAtlas;
  const insights = matchupInsights(pack, a, b), axisCount = sharedMeasuredAxisCount(pack, a, b);
  const ladder = sharedPercentileLadder(pack, a, b);
  return <><div className="compare-profiles" aria-label="Compared profiles"><ProfileHeading entity={a} pack={pack.key} label="Profile A" comparables={pack.comparablesByEntity?.[a.slug]} hasPackComparables={Boolean(pack.comparablesByEntity)} /><div className="compare-versus" aria-hidden="true">vs</div><ProfileHeading entity={b} pack={pack.key} label="Profile B" comparables={pack.comparablesByEntity?.[b.slug]} hasPackComparables={Boolean(pack.comparablesByEntity)} /></div>
    {mixedMlbAtlas ? <p className="compare-empty" role="status">Choose two pitch types, two teams, or two count states to compare recorded MLB atlas values.</p> : null}
    {pack.key === "tennis" ? <TennisSurfaceComparison a={a} b={b} surface={surface} onSurfaceChange={onSurfaceChange} sourceHref={publicPath(manifest)} nRankedByMetric={pack.nRankedByMetric} /> : null}{pack.key === "soccer" ? <SoccerVenueComparison a={a} b={b} sourceHref={publicPath(manifest)} /> : null}{rawMlbAtlas ? <><PitchCountComparison a={a} b={b} sourceHref={publicPath(manifest)} /><PitchResultComparison a={a} b={b} sourceHref={publicPath(manifest)} /></> : null}
    {!mixedMlbAtlas && !rawMlbAtlas ? <><section className="compare-insights" aria-labelledby="compare-insights-title"><div className="compare-insights-heading"><div><span className="compare-section-label">Measured contrasts</span><h2 id="compare-insights-title">Largest measured differences</h2></div><span className="compare-overlap">{axisCount} measurements recorded for both profiles</span></div><p className="compare-insights-intro">Largest percentile gaps among fields reported for both profiles. Values stay tied to the published historical corpus.</p>{insights.length ? <div className="compare-insight-grid">{insights.map((insight) => { const nRanked = rankedCount(pack, insight.field); return <article className="compare-insight" key={insight.field}><div className="compare-insight-top"><strong>{insight.label}</strong><span>{Math.round(insight.gap)} pt gap</span></div><div className="compare-insight-values"><span><b>{insight.aValue}</b><small>{a.name} - {formatPercentile(insight.aPercentile)}</small></span><span><b>{insight.bValue}</b><small>{b.name} - {formatPercentile(insight.bPercentile)}</small></span></div>{nRanked ? <small className="compare-rank-context">Ranked among {nRanked} profiles with this measurement.</small> : null}</article>; })}</div> : <p className="compare-empty">No shared numeric axes are published for this pair.</p>}</section><section className="compare-ladder" aria-labelledby="compare-ladder-title"><div><span className="compare-section-label">Within-pack ranks</span><h2 id="compare-ladder-title">Percentile ladder</h2></div><p>Measurements with the largest percentile differences appear first.</p>{ladder.length ? <div className="compare-ladder-list">{ladder.map((row) => { const nRanked = rankedCount(pack, row.field); return <article key={row.field}><div className="compare-ladder-label"><strong>{row.field.replace(/_/g, " ")}</strong><span>{Math.round(row.gap)} pt gap</span></div><div className="compare-ladder-bars"><div><b>{formatMetric(a.values[row.field], row.field)}</b><PercentileBar pct={row.aPercentile} nRanked={nRanked} /></div><div><b>{formatMetric(b.values[row.field], row.field)}</b><PercentileBar pct={row.bPercentile} nRanked={nRanked} /></div></div></article>; })}</div> : <p className="compare-empty">No shared ranked axes are published for this pair.</p>}</section></> : null}
    {!mixedMlbAtlas ? (pack.metricKeys.length ? <div className="compare-table-wrap"><table className="compare-table"><caption>{rawMlbAtlas ? "Published raw values" : "Published values and within-pack percentile ranks"}</caption><thead><tr><th scope="col">Metric</th><th scope="col"><span>Profile A</span>{a.name}</th><th scope="col"><span>Profile B</span>{b.name}</th></tr></thead><tbody>{pack.metricKeys.map((key) => <MetricRow key={key} field={key} a={a} b={b} showRanks={!rawMlbAtlas} nRanked={rankedCount(pack, key)} />)}</tbody></table></div> : <p className="compare-empty">This pack has no published within-pack percentile fields, so it cannot show a ranked comparison.</p>) : null}
    <p className="compare-note">{pack.key === "mlb_pitch" ? "Raw records are shown only for same-family MLB atlas pairs. Source percentiles mix pitch types, teams, and count states, so ranks and percentile gaps are omitted." : "Percentiles are within this pack only. Higher means a higher raw measured value, never better. Corpus labels describe the years represented by the card; they are not projections."}</p><p className="compare-sources">Sources: <a href={publicPath(manifest)} target="_blank" rel="noreferrer">raw manifest</a>, <a href={publicPath("entity_percentiles.json")} target="_blank" rel="noreferrer">raw percentiles</a>, and <a href={publicPath("entity_comparables.json")} target="_blank" rel="noreferrer">raw comparables</a>. <Link href={sport === "nba" ? "/analytics/research/nba-matchup-profile-contrast/" : sport ? `/analytics/browse/?sport=${sport}` : "/analytics/browse/"}>More {sport === "nba" ? "NBA profile research" : "library analysis"}</Link></p>
  </>;
}
