import type { ComparisonEntity } from "@/lib/analytics/comparisonData";
import { type SoccerVenueAvailability, type SoccerVenueRow, soccerVenueComparison } from "@/lib/analytics/soccerVenueComparison";

type Props = { a: ComparisonEntity; b: ComparisonEntity; sourceHref: string };
function valueText(value: number | null, availability: SoccerVenueAvailability, row: SoccerVenueRow): string { if (value === null) return availability === "invalid" ? "Unavailable" : "Not published"; return row.unit === "percentage_points" ? `${(value * 100).toFixed(1)}%` : value.toFixed(1); }
function gapText(value: number | null, home: SoccerVenueAvailability, away: SoccerVenueAvailability, row: SoccerVenueRow): string { if (value === null) return `Home minus away: ${home === "invalid" || away === "invalid" ? "Unavailable" : "Not published"}`; const number = `${value > 0 ? "+" : ""}${value.toFixed(1)}`; return `Home minus away: ${number}${row.unit === "percentage_points" ? " percentage points" : " points per game"}`; }
function VenueBar({ name, venue, value, availability, row }: { name: string; venue: "Home" | "Away"; value: number | null; availability: SoccerVenueAvailability; row: SoccerVenueRow }) { const maximum = row.unit === "percentage_points" ? 1 : 3; const text = valueText(value, availability, row); return <div className="soccer-venue-value"><span>{venue}: <b>{text}</b></span>{value === null ? <i className="soccer-venue-track is-unavailable" aria-hidden="true" /> : <span className="soccer-venue-track" role="img" aria-label={`${name} ${row.label} ${venue}: ${text}`}><i style={{ width: `${value / maximum * 100}%` }} /></span>}</div>; }
function VenueAxis({ row }: { row: SoccerVenueRow }) { return <span className="soccer-venue-axis" aria-label={`${row.label} scale`}><i>0</i><i>{row.unit === "percentage_points" ? "50%" : "1.5"}</i><i>{row.unit === "percentage_points" ? "100%" : "3"}</i></span>; }

export function SoccerVenueComparison({ a, b, sourceHref }: Props) {
  const comparison = soccerVenueComparison(a, b);
  if (!comparison) return null;
  return <section className="soccer-venue-comparison" aria-labelledby="soccer-venue-title">
    <div><span className="compare-section-label">Soccer record</span><h2 id="soccer-venue-title">Home and away form</h2></div>
    <p className="soccer-venue-intro">Published home and away records are shown separately for each club. They describe prior matches and do not estimate a venue effect or a future result.</p>
    {comparison.rows.map((row) => <section className="soccer-venue-group" key={row.key} aria-labelledby={`venue-${row.key}`}><div className="soccer-venue-group-head"><div><h3 id={`venue-${row.key}`}>{row.label}</h3><span>{row.unit === "percentage_points" ? "0-100% scale" : "0-3 points per game scale"}</span></div></div><div className="soccer-venue-clubs"><article><h4>{a.name}</h4><VenueAxis row={row} /><VenueBar name={a.name} venue="Home" value={row.a.home} availability={row.a.homeAvailability} row={row} /><VenueBar name={a.name} venue="Away" value={row.a.away} availability={row.a.awayAvailability} row={row} /><p>{gapText(row.a.gap, row.a.homeAvailability, row.a.awayAvailability, row)}</p></article><article><h4>{b.name}</h4><VenueAxis row={row} /><VenueBar name={b.name} venue="Home" value={row.b.home} availability={row.b.homeAvailability} row={row} /><VenueBar name={b.name} venue="Away" value={row.b.away} availability={row.b.awayAvailability} row={row} /><p>{gapText(row.b.gap, row.b.homeAvailability, row.b.awayAvailability, row)}</p></article></div></section>)}
    <div className="soccer-venue-table-wrap"><table className="soccer-venue-table"><caption>Published home and away form values</caption><thead><tr><th scope="col">Measure</th><th scope="col">{a.name}</th><th scope="col">{b.name}</th></tr></thead><tbody>{comparison.rows.map((row) => <tr key={row.key}><th scope="row">{row.label}<small>{row.unit === "percentage_points" ? "Home minus away in percentage points" : "Home minus away in points per game"}</small></th><td>Home {valueText(row.a.home, row.a.homeAvailability, row)}<br />Away {valueText(row.a.away, row.a.awayAvailability, row)}<small>{gapText(row.a.gap, row.a.homeAvailability, row.a.awayAvailability, row)}</small></td><td>Home {valueText(row.b.home, row.b.homeAvailability, row)}<br />Away {valueText(row.b.away, row.b.awayAvailability, row)}<small>{gapText(row.b.gap, row.b.homeAvailability, row.b.awayAvailability, row)}</small></td></tr>)}</tbody></table></div>
    <div className="soccer-venue-meta"><p>Source window: separate trailing home and away prior-match windows. Total prior-match counts and club-specific latest match dates are not published.</p><details><summary>Methods and source details</summary><p>Points per game awards 3 points for a win, 1 for a draw, and 0 for a loss. A clean sheet means no goals conceded.</p><p>{comparison.note}</p><p><a href={sourceHref} target="_blank" rel="noreferrer">Raw soccer atlas manifest</a></p>{comparison.entities.a.floors === comparison.entities.b.floors ? <p>{comparison.entities.a.floors}</p> : <><p><b>{a.name}:</b> {comparison.entities.a.floors}</p><p><b>{b.name}:</b> {comparison.entities.b.floors}</p></>}</details><p>Claim computation snapshot: {comparison.entities.a.asOf.slice(0, 10)}</p></div>
  </section>;
}
