"""Per-file tests for intel_query.ask + intel_query.families.

Run with:
  cd /c/Users/neelj/nba-ai-system && python -m pytest \
    scripts/platformkit/intel_query/test_ask.py -q

Acceptance criteria:
  1. top_n question against a VERIFIED ranking claim returns the ranking,
     evidence carries claim_id + source_files + as_of + VERIFIED verdict.
  2. entity_lookup finds a named player's rank inside a VERIFIED claim.
  3. provenance returns criteria + caveats for a named VERIFIED claim_id.
  4. A claim_id that is MISMATCH or UNVERIFIABLE in the validation summary
     is INVISIBLE to ask() (never answered from).
  5. An unclassifiable question is honestly unanswerable with
     nearest_supported_families populated.
  6. A well-formed question with no VERIFIED claim covering it is honestly
     unanswerable (never falls back to raw computation).
  7. families.classify buckets top_n / entity_lookup / provenance /
     gate_verdict / None correctly, including a window= hint.
  8. gate_verdict question against a VERIFIED claim_kind=verdict row returns
     gate_module/verdict/primary_number/provenance; a MISMATCH verdict-claim
     row is invisible; an uncovered gate topic is honestly unanswerable.
  9. discover_claim_source_pairs (PROGRAM v3 ask-coverage lane) AUTOMATICALLY
     glob-discovers every *.jsonl claims store paired with its same-stem
     _validation.json sibling, with zero per-store registration -- proven
     against a tmp_path fixture with 3 stores (2 conventional, 1 unpaired)
     plus a REAL end-to-end check that every wave-51 store this lane added
     (wnba/tennis_claims_v3/catcher_framing/platoon_split/umpire_zone) is
     actually discovered from the real repo tree.
"""
from __future__ import annotations

import json
import time

import pytest

from scripts.platformkit.intel_query import ask as ask_mod
from scripts.platformkit.intel_query import families


def _ranking_claim(claim_id: str, metric: str, window: str, ranking: list[dict]) -> dict:
    return {
        "claim_id": claim_id,
        "kind": "ranking",
        "question": f"Top by {metric} in window={window}?",
        "criteria": {"metric": metric, "window": window, "formula": "sum(x)/sum(y)"},
        "ranking": ranking,
        "source_files": ["data/fake/source.parquet"],
        "computed_at": "2026-07-04T00:00:00+00:00",
        "n_considered": 100,
        "n_excluded_below_floor": 10,
        "caveats": ["fixture caveat"],
    }


@pytest.fixture
def fixture_sources(tmp_path, monkeypatch):
    """One validation-summary + producer-claims pair with a VERIFIED ranking
    claim, a MISMATCH claim, and an UNVERIFIABLE claim -- so tests can assert
    only the VERIFIED one is ever answerable."""
    claims_path = tmp_path / "claims.jsonl"
    validation_path = tmp_path / "validation.json"

    verified_row = _ranking_claim(
        "fixture_composite_last_20", "composite", "last_20",
        [
            {"rank": 1, "player_id": 1, "player_name": "Alpha Player", "value": 0.9, "n": 20},
            {"rank": 2, "player_id": 2, "player_name": "Beta Player", "value": 0.8, "n": 20},
        ],
    )
    mismatch_row = _ranking_claim(
        "fixture_composite_mismatch", "composite", "last_20",
        [{"rank": 1, "player_id": 3, "player_name": "Gamma Player", "value": 0.95, "n": 20}],
    )
    unverifiable_row = {
        "claim_id": "fixture_gate_verdict",
        "kind": "gate_verdict",
        "question": "Does X beat Y?",
        "criteria": {"gate": "3a"},
        "computed_at": "2026-07-04T00:00:00+00:00",
    }

    with open(claims_path, "w", encoding="ascii") as f:
        for row in (verified_row, mismatch_row, unverifiable_row):
            f.write(json.dumps(row) + "\n")

    validation_summary = {
        "component": "intel_claims_validation",
        "n_claims": 3,
        "details": [
            {"claim_id": "fixture_composite_last_20", "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": "fixture_composite_mismatch", "verdict": "MISMATCH", "reason": "bad"},
            {"claim_id": "fixture_gate_verdict", "verdict": "UNVERIFIABLE", "reason": "no formula"},
        ],
    }
    validation_path.write_text(json.dumps(validation_summary), encoding="ascii")

    # INTEL_CLAIMS_DIR isolation matters here specifically because ask()'s
    # FAMILY_TOP_N path tries the real INTEL_CLAIMS_DIR's sidecar indexes
    # FIRST (spec sec 4) -- without this, a TOP_N question in this fixture
    # would scan whatever REAL families/indexes happen to exist on disk
    # (e.g. the live NBA claims generated by this same lane) before falling
    # through to CLAIM_SOURCE_PAIRS, which is slow and not what this
    # fixture is testing. Pointing INTEL_CLAIMS_DIR at the empty tmp_path
    # makes the fast-path scan trivially cheap (no families found) with
    # ZERO change to any assertion -- these questions never matched real
    # on-disk claims anyway, they only ever answered from CLAIM_SOURCE_PAIRS.
    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return validation_path, claims_path


def test_top_n_answers_from_verified_claim_with_evidence(fixture_sources):
    result = ask_mod.ask("Who are the top 2 best shooters (composite) in window=last_20?")
    assert result["answerable"] is True
    assert result["family"] == families.FAMILY_TOP_N
    ranking = result["answer"]["ranking"]
    assert [r["player_name"] for r in ranking] == ["Alpha Player", "Beta Player"]
    evidence = result["evidence"][0]
    assert evidence["claim_id"] == "fixture_composite_last_20"
    assert evidence["validator_verdict"] == "VERIFIED"
    assert evidence["source_files"] == ["data/fake/source.parquet"]
    assert evidence["as_of"] == "2026-07-04T00:00:00+00:00"


def test_entity_lookup_finds_named_player(fixture_sources):
    result = ask_mod.ask("Where does Alpha Player rank on composite in window=last_20?")
    assert result["answerable"] is True
    assert result["answer"]["entity_name"] == "Alpha Player"
    assert result["answer"]["rankings"][0]["rank"] == 1


@pytest.fixture
def fixture_name_keyed_sources(tmp_path, monkeypatch):
    """A NAME-KEYED store shaped like nba_referee_crew_ft: entity_key=
    "entity_id" but the ranking rows carry no player_name/entity_name field
    at all -- the entity_id VALUE IS the official's name. Root-cause fix
    target: _answer_entity_lookup used to only ever check "player_name"."""
    claims_path = tmp_path / "claims.jsonl"
    validation_path = tmp_path / "validation.json"
    row = {
        "claim_id": "fixture_referee_mean_fta_alltime",
        "kind": "ranking",
        "question": "NBA official mean fta environment, alltime?",
        "criteria": {"metric": "mean_fta", "window": "alltime", "entity_key": "entity_id"},
        "ranking": [
            {"rank": 1, "entity_id": "Leon Wood", "value": 46.2, "n_games": 120},
            {"rank": 2, "entity_id": "Rodney Mott", "value": 44.1, "n_games": 90},
        ],
        "source_files": ["data/fake/referee_source.parquet"],
        "computed_at": "2026-07-18T00:00:00+00:00",
    }
    with open(claims_path, "w", encoding="ascii") as f:
        f.write(json.dumps(row) + "\n")
    validation_path.write_text(json.dumps({
        "component": "intel_claims_validation", "n_claims": 1,
        "details": [{"claim_id": "fixture_referee_mean_fta_alltime", "verdict": "VERIFIED", "reason": "ok"}],
    }), encoding="ascii")
    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return validation_path, claims_path


def test_entity_lookup_matches_name_keyed_row(fixture_name_keyed_sources):
    """A referee named directly (entity_id-as-name row) must match, not
    fall to honest-unanswerable just because the row has no player_name."""
    result = ask_mod.ask("Where does Leon Wood rank on mean fta in window=alltime?")
    assert result["answerable"] is True
    assert result["answer"]["entity_name"] == "Leon Wood"
    assert result["answer"]["rankings"][0]["rank"] == 1


def test_entity_lookup_unrelated_name_still_unanswerable(fixture_name_keyed_sources):
    result = ask_mod.ask("Where does Fake Nobody rank on mean fta in window=alltime?")
    assert result["answerable"] is False


# --- officials-domain gate + index fast-path name matching (probe fixes ------
# 2026-07-19): real-data probes caught two regressions the first synthetic
# fixtures missed. (1) "top officials by <player metric>" was answered by the
# PLAYER family -- officials are not players; an officials question must never
# be won by a player/team row even when the metric token matches. (2) the
# referee family has a FRESH index, so index_entity_lookup's name check (not
# the slow path's) decided the answer, and it still only looked at
# player_name -- the entity_id-as-name fallback has to live there too.
@pytest.fixture
def fixture_officials_vs_players(tmp_path, monkeypatch):
    from scripts.platformkit.intel_query.claims_index import build_index

    player_row = _ranking_claim(
        "nba_player_box_fta_per_game_alltime", "fta_per_game", "alltime",
        [{"rank": 1, "player_id": 1, "player_name": "Giannis Antetokounmpo", "value": 11.2, "n": 500}],
    )
    referee_row = {
        "claim_id": "nba_referee_crew_ft_mean_fta_environment_alltime",
        "kind": "ranking",
        "question": "NBA official mean fta environment, alltime?",
        "criteria": {"metric": "mean_fta", "window": "alltime", "entity_key": "entity_id"},
        "ranking": [{"rank": 1, "entity_id": "Leon Wood", "value": 46.2, "n_games": 120}],
        "source_files": ["data/fake/referee_source.parquet"],
        "computed_at": "2026-07-18T00:00:00+00:00",
    }
    pairs = []
    for family, row in (("nba_player_box_rate", player_row), ("nba_referee_crew_ft_claims", referee_row)):
        claims_path, validation_path = _write_indexable_pair(
            tmp_path, family, [row], {row["claim_id"]: "VERIFIED"})
        build_index(family, tmp_path)
        pairs.append((validation_path, claims_path))
    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", tuple(pairs))
    return tmp_path


def test_officials_question_never_answered_by_player_claim(fixture_officials_vs_players):
    """PROBE 1 regression: the player metric alias fires ("free throw
    attempts per game" -> fta_per_game) but the officials token must
    suppress the player family -- honest unanswerable, never Giannis."""
    result = ask_mod.ask("top officials by free throw attempts per game")
    assert result["answerable"] is False


def test_players_question_still_answered_by_player_claim(fixture_officials_vs_players):
    result = ask_mod.ask("top 3 players by free throw attempts per game")
    assert result["answerable"] is True
    assert result["answer"]["ranking"][0]["player_name"] == "Giannis Antetokounmpo"


def test_entity_lookup_name_keyed_via_index_fast_path(fixture_officials_vs_players):
    """PROBE 2 regression: with a FRESH index, index_entity_lookup (not the
    slow path) does the name match -- entity_id-as-name must hit there."""
    result = ask_mod.ask("where does Leon Wood rank on mean fta among nba officials")
    assert result["answerable"] is True
    assert result["answer"]["entity_name"] == "Leon Wood"
    assert result["answer"]["rankings"][0]["rank"] == 1


# --- entity_lookup index fast path (2026-07-16 memory fix) -----------------
#
# entity_lookup used to be the ONLY family with no index fast path: every
# question fell through to load_verified_claims, which whole-loads every
# VERIFIED row of every store into memory for the life of the call. For
# nba_player_box_rate (2.8GB / 59,710 rows, each a duplicated ~44KB
# full-league ranking blob) that meant multi-GB resident just to answer a
# single-player question. These tests prove ask_index.index_entity_lookup
# seeks+reads only VERIFIED, hint-matching byte ranges -- never a MISMATCH
# row sharing the same metric/window, never the whole store.

def test_entity_lookup_index_fast_path_and_fallback_agree(indexable_fixture):
    tmp_path, family, _claims_path, _validation_path = indexable_fixture
    q = "Where does Delta Player rank on composite in window=idx_test_window_v1?"
    fast_result = ask_mod.ask(q)
    assert fast_result["answerable"] is True
    assert fast_result["answer"]["rankings"][0]["value"] == 0.7

    (tmp_path / f"{family}.index.jsonl").unlink()  # force missing-index fallback
    fallback_result = ask_mod.ask(q)
    assert fallback_result == fast_result  # SAME answer, found via a different path


def test_entity_lookup_fast_path_seeks_only_verified_byte_ranges(tmp_path, monkeypatch):
    """Proves the fast path SEEKS the underlying claims file rather than
    scanning it: a MISMATCH-verdict row sharing the exact same metric/
    window as the VERIFIED hit (and a different value, so a leak is
    detectable) must never be seeked -- its verdict is known from the
    small .index.jsonl alone -- and the total seek count must equal
    exactly the VERIFIED rows, never all 3 rows in the file."""
    from scripts.platformkit.intel_query.claims_index import build_index
    from scripts.platformkit.intel_query import ask_index as ask_index_mod

    family = "ent_fast_fam"
    verified_row = _ranking_claim(
        "ent_fast_verified", "composite", "v1",
        [{"rank": 1, "player_id": 1, "player_name": "Delta Player", "value": 0.7, "n": 25}],
    )
    mismatch_row = _ranking_claim(
        "ent_fast_mismatch", "composite", "v1",
        [{"rank": 1, "player_id": 2, "player_name": "Delta Player", "value": 0.9, "n": 25}],
    )
    other_row = _ranking_claim(
        "ent_fast_other", "other_metric", "v2",
        [{"rank": 1, "player_id": 3, "player_name": "Echo Player", "value": 0.4, "n": 25}],
    )
    claims_path, validation_path = _write_indexable_pair(
        tmp_path, family, [verified_row, mismatch_row, other_row],
        {"ent_fast_verified": "VERIFIED", "ent_fast_mismatch": "MISMATCH", "ent_fast_other": "VERIFIED"},
    )
    build_index(family, tmp_path)

    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))

    seek_calls: list[tuple] = []
    real_seek = ask_index_mod.seek_claim_row

    def _tracking_seek(path, offset):
        seek_calls.append((path, offset))
        return real_seek(path, offset)

    monkeypatch.setattr(ask_index_mod, "seek_claim_row", _tracking_seek)

    result = ask_mod.ask("Where does Delta Player rank on composite in window=v1?")
    assert result["answerable"] is True
    assert result["answer"]["rankings"][0]["value"] == 0.7  # VERIFIED row's value, not mismatch's 0.9

    # Bounded: exactly 1 seek. "composite" is a recognized metric alias
    # (families._METRIC_ALIASES), so metric_hints=["composite"] excludes
    # other_row (metric="other_metric") via the index alone -- no seek.
    # mismatch_row shares metric+window with the hit but verdict!=VERIFIED
    # -- also excluded via the index alone, never touched, never seeked.
    # Only ent_fast_verified (VERIFIED, metric=composite, window=v1)
    # survives the index pre-filter and gets seeked -- never a linear
    # readlines()/full-file scan of the 3-row store.
    assert len(seek_calls) == 1
    assert seek_calls[0] == (claims_path, 0)  # the VERIFIED row's own byte_offset (first line)


def test_provenance_returns_criteria_and_caveats(fixture_sources):
    result = ask_mod.ask("How do you know? Show the evidence for fixture_composite_last_20.")
    assert result["answerable"] is True
    assert result["answer"]["claim_id"] == "fixture_composite_last_20"
    assert result["answer"]["caveats"] == ["fixture caveat"]


def test_mismatch_claim_never_surfaces(fixture_sources):
    # Same metric/window as the verified claim, but only the VERIFIED one's
    # players should ever appear -- Gamma Player (mismatch) must be excluded.
    result = ask_mod.ask("Who are the top 10 best shooters (composite) in window=last_20?")
    names = [r["player_name"] for r in result["answer"]["ranking"]]
    assert "Gamma Player" not in names

    lookup = ask_mod.ask("Where does Gamma Player rank on composite in window=last_20?")
    assert lookup["answerable"] is False


def test_unverifiable_gate_claim_never_answerable_via_provenance(fixture_sources):
    result = ask_mod.ask("How do you know? Show the evidence for fixture_gate_verdict.")
    assert result["answerable"] is False
    assert "nearest_supported_families" in result


def test_unclassifiable_question_is_honest_unanswerable(fixture_sources):
    result = ask_mod.ask("What is the weather in Boston tomorrow?")
    assert result["answerable"] is False
    assert len(result["nearest_supported_families"]) == 4


def test_wellformed_question_no_covering_claim_is_honest_unanswerable(fixture_sources):
    result = ask_mod.ask("Who are the top 5 best shooters (composite) in window=season_1999-00?")
    assert result["answerable"] is False


# --- entity-type + metric-synonym routing bug fix ---------------------------
#
# Live-reproduced bug: "who are the top 5 nba players by free throw
# percentage this season" answered with metric=team_pts_per_game (a TEAM
# claim) because families.classify's metric_hints alias dict has no
# synonym for "free throw percentage" (metric_hints came back empty), and
# an empty metric_hints used to skip ALL metric filtering -- every VERIFIED
# ranking claim across every family (player or team) became eligible, and
# the most-recent computed_at won by accident. These fixtures reproduce
# the EXACT collision shape (a player ft_pct claim + an unrelated, more
# recent team_pts_per_game claim in the same corpus) to prove it cannot
# recur, regardless of what the real on-disk corpus currently contains.

def _player_ranking_claim(claim_id: str, metric: str, window: str, computed_at: str, ranking: list[dict]) -> dict:
    return {
        "claim_id": claim_id, "kind": "ranking",
        "question": f"Top by {metric} in window={window}?",
        "criteria": {"metric": metric, "window": window, "entity_key": "player_id", "formula": "x/y"},
        "ranking": ranking, "source_files": ["data/fake/player_source.parquet"],
        "computed_at": computed_at, "n_considered": 50, "n_excluded_below_floor": 5,
        "caveats": ["fixture caveat"],
    }


def _team_ranking_claim(claim_id: str, metric: str, window: str, computed_at: str, ranking: list[dict]) -> dict:
    return {
        "claim_id": claim_id, "kind": "ranking",
        "question": f"Top by {metric} in window={window}?",
        "criteria": {"metric": metric, "window": window, "entity_key": "team", "formula": "x/y"},
        "ranking": ranking, "source_files": ["data/fake/team_source.parquet"],
        "computed_at": computed_at, "n_considered": 30, "n_excluded_below_floor": 0,
        "caveats": ["fixture caveat"],
    }


@pytest.fixture
def fixture_player_team_collision(tmp_path, monkeypatch):
    """A player-shaped ft_pct-style claim (metric=ft_reliability, older
    computed_at) alongside a MORE RECENT, unrelated team_pts_per_game claim
    -- the exact shape that let the team claim win by recency when the
    question's metric_hints came back empty. No sidecar .index.jsonl is
    built, so this exercises the full-load path (_filter_by_hints)."""
    claims_path = tmp_path / "claims.jsonl"
    validation_path = tmp_path / "validation.json"

    player_row = _player_ranking_claim(
        "fixture_ft_reliability", "ft_reliability", "season_2024_25", "2026-07-01T00:00:00+00:00",
        [
            {"rank": 1, "player_id": 1, "player_name": "Free Thrower", "value": 1.0, "n": 24},
            {"rank": 2, "player_id": 2, "player_name": "Second Shooter", "value": 0.95, "n": 61},
        ],
    )
    team_row = _team_ranking_claim(
        "fixture_team_pts_per_game", "team_pts_per_game", "season_2024_25", "2026-07-06T00:00:00+00:00",
        [{"rank": 1, "team": "CLE", "value": 121.6, "n": 82}],
    )

    with open(claims_path, "w", encoding="ascii") as f:
        for row in (player_row, team_row):
            f.write(json.dumps(row) + "\n")

    validation_summary = {
        "component": "intel_claims_validation",
        "n_claims": 2,
        "details": [
            {"claim_id": "fixture_ft_reliability", "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": "fixture_team_pts_per_game", "verdict": "VERIFIED", "reason": "ok"},
        ],
    }
    validation_path.write_text(json.dumps(validation_summary), encoding="ascii")

    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return validation_path, claims_path


def test_players_question_with_unaliased_metric_finds_player_claim_not_team(fixture_player_team_collision):
    """THE regression: the exact failing question shape now returns the
    PLAYER ft_pct-style ranking, never the more-recent team claim."""
    result = ask_mod.ask("who are the top 5 nba players by free throw percentage this season")
    assert result["answerable"] is True
    assert result["family"] == families.FAMILY_TOP_N
    assert result["answer"]["metric"] == "ft_reliability"
    ranking = result["answer"]["ranking"]
    assert ranking[0]["player_name"] == "Free Thrower"
    assert "team" not in ranking[0]  # rank-1 row is a player row, not a team row


def test_team_phrasing_still_returns_team_metric(fixture_player_team_collision):
    """A team-phrased question must still resolve to the team claim -- the
    entity-type gate filters, it does not become a player-only allowlist."""
    result = ask_mod.ask("who are the top 5 nba teams by team points per game this season")
    assert result["answerable"] is True
    assert result["answer"]["metric"] == "team_pts_per_game"
    assert result["answer"]["ranking"][0]["team"] == "CLE"


def test_unknown_metric_is_honest_unanswerable_never_wrong_entity(fixture_player_team_collision):
    """A metric with no synonym AND no families.py alias must never fall
    back to answering from an unrelated claim (of either entity type) --
    honest UNANSWERABLE, not a guess."""
    result = ask_mod.ask("who are the top 5 nba players by hustle plays this season")
    assert result["answerable"] is False
    assert "reason" in result


def test_longest_metric_synonym_match_beats_substring_collision(fixture_player_team_collision):
    """"team free throw percentage" contains "free throw percentage" as a
    literal substring -- the longest-match rule must resolve it to
    team_ft_pct, not the shorter ft_reliability alias. Neither metric
    exists in this fixture's corpus, so the honest result is
    UNANSWERABLE either way, but it must be unanswerable for the RIGHT
    metric (team_ft_pct), never silently answered from ft_reliability."""
    from scripts.platformkit.intel_query import ask_index as ask_index_mod

    assert ask_index_mod.extract_metric_synonym("team free throw percentage") == "team_ft_pct"
    assert ask_index_mod.extract_metric_synonym("free throw percentage") == "ft_reliability"

    result = ask_mod.ask("who are the top 5 nba teams by team free throw percentage this season")
    assert result["answerable"] is False  # fixture has no team_ft_pct claim -- honest miss
    # never silently answers from the DIFFERENT (player) ft_reliability claim
    assert result.get("answer", {}).get("metric") != "ft_reliability"


def test_real_repo_ft_percentage_question_never_answers_wrong_entity_or_metric():
    """LIVE-REPRODUCED bug, real corpus (no monkeypatch): whatever ask()
    currently returns for this question, it must NEVER be a team claim
    (metric starting with "team_") and NEVER a metric unrelated to free
    throws. Today the corpus has no VALIDATED player ft_pct/ft_reliability
    claim (see spawned task: nba_shooting_claims.jsonl's 20 rows are paired
    with a validation summary that covers a DIFFERENT producer file), so
    the honest, current answer is UNANSWERABLE -- proving the routing fix
    holds against the real on-disk data, not just a fixture."""
    result = ask_mod.ask("who are the top 5 nba players by free throw percentage this season")
    if result["answerable"]:
        assert not str(result["answer"]["metric"]).startswith("team_")
        assert "ft" in result["answer"]["metric"].lower()
        for row in result["answer"]["ranking"]:
            assert "team" not in row  # rank rows must be player rows, not team rows
    else:
        assert "reason" in result


def _write_indexable_pair(claims_dir, family: str, rows: list[dict], verdicts: dict[str, str]):
    """Same shape as claims_index.py's own test helpers -- writes
    <family>.jsonl + <family>_validation.json into claims_dir (no index)."""
    claims_path = claims_dir / f"{family}.jsonl"
    validation_path = claims_dir / f"{family}_validation.json"
    with open(claims_path, "w", encoding="ascii") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")
    payload = {
        "component": "intel_claims_validation", "generated_at": "2026-07-06T00:00:00+00:00",
        "n_claims": len(rows), "n_verified": sum(1 for v in verdicts.values() if v == "VERIFIED"),
        "n_mismatch": 0, "n_unverifiable": 0, "edge_claimed": False,
        "details": [{"claim_id": cid, "verdict": v, "reason": "test"} for cid, v in verdicts.items()],
    }
    validation_path.write_text(json.dumps(payload), encoding="ascii")
    return claims_path, validation_path


@pytest.fixture
def indexable_fixture(tmp_path, monkeypatch):
    """One family with a fresh sidecar .index.jsonl -- INTEL_CLAIMS_DIR and
    CLAIM_SOURCE_PAIRS both monkeypatched to the SAME tmp_path so the fast
    (index) path and the slow (full-load) path see IDENTICAL underlying
    files, making a true index-vs-fallback parity check possible."""
    from scripts.platformkit.intel_query.claims_index import build_index

    family = "idx_parity_fam"
    row = _ranking_claim(
        "idx_parity_a", "composite", "idx_test_window_v1",
        [{"rank": 1, "player_id": 10, "player_name": "Delta Player", "value": 0.7, "n": 25}],
    )
    claims_path, validation_path = _write_indexable_pair(tmp_path, family, [row], {"idx_parity_a": "VERIFIED"})
    build_index(family, tmp_path)

    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return tmp_path, family, claims_path, validation_path


_IDX_QUESTION = "Who are the top 1 best shooters (composite) in window=idx_test_window_v1?"


def test_index_fast_path_answers_correctly(indexable_fixture):
    result = ask_mod.ask(_IDX_QUESTION)
    assert result["answerable"] is True
    assert result["answer"]["ranking"][0]["player_name"] == "Delta Player"
    assert result["answer"]["ranking"][0]["value"] == 0.7
    assert result["evidence"][0]["validator_verdict"] == "VERIFIED"


def test_index_path_and_full_load_fallback_give_the_same_answer(indexable_fixture):
    tmp_path, family, _claims_path, _validation_path = indexable_fixture
    fast_result = ask_mod.ask(_IDX_QUESTION)

    (tmp_path / f"{family}.index.jsonl").unlink()  # force missing-index fallback
    fallback_result = ask_mod.ask(_IDX_QUESTION)

    assert fast_result["answerable"] is True
    assert fallback_result == fast_result  # SAME answer, found via a different path


def test_missing_index_never_built_falls_back_cleanly(tmp_path, monkeypatch):
    row = _ranking_claim(
        "idx_never_built", "composite", "idx_test_window_never_indexed",
        [{"rank": 1, "player_id": 11, "player_name": "Zeta Player", "value": 0.6, "n": 25}],
    )
    claims_path, validation_path = _write_indexable_pair(
        tmp_path, "idx_never_built_fam", [row], {"idx_never_built": "VERIFIED"}
    )
    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))

    result = ask_mod.ask("Who are the top 1 best shooters (composite) in window=idx_test_window_never_indexed?")
    assert result["answerable"] is True
    assert result["answer"]["ranking"][0]["player_name"] == "Zeta Player"


def test_all_families_indexed_short_circuits_without_slow_load(tmp_path, monkeypatch):
    """BUG FIX regression (m38, j2 day-queue item): with EVERY family
    fresh-indexed, a top_n question whose metric resolves but matches no
    claim must return honest unanswerable WITHOUT ever calling
    load_verified_claims's whole-corpus loop -- that full parse (GBs on the
    real corpus) is exactly the measured 51.6s bug. Monkeypatching
    load_verified_claims to raise proves the short-circuit, not just that
    the answer happens to be right."""
    from scripts.platformkit.intel_query.claims_index import build_index

    row = _ranking_claim(
        "sc_fam_a", "composite", "sc_window_v1",
        [{"rank": 1, "player_id": 1, "player_name": "Echo Player", "value": 0.5, "n": 25}],
    )
    claims_a, validation_a = _write_indexable_pair(tmp_path, "sc_fam_a", [row], {"sc_fam_a": "VERIFIED"})
    build_index("sc_fam_a", tmp_path)

    row_b = _ranking_claim(
        "sc_fam_b", "other_metric", "sc_window_v1",
        [{"rank": 1, "player_id": 2, "player_name": "Foxtrot Player", "value": 0.4, "n": 25}],
    )
    claims_b, validation_b = _write_indexable_pair(tmp_path, "sc_fam_b", [row_b], {"sc_fam_b": "VERIFIED"})
    build_index("sc_fam_b", tmp_path)

    monkeypatch.setattr(ask_mod, "INTEL_CLAIMS_DIR", tmp_path)
    monkeypatch.setattr(
        ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_a, claims_a), (validation_b, claims_b))
    )

    real_load = ask_mod.load_verified_claims

    def _guarded(pairs=ask_mod.CLAIM_SOURCE_PAIRS):
        # Both families are fresh-indexed -- the short-circuit's residual
        # load must be called with an EMPTY pairs tuple (nothing stale), and
        # must NEVER be called with the full CLAIM_SOURCE_PAIRS (that is the
        # slow whole-corpus path this fix exists to skip).
        assert pairs != ask_mod.CLAIM_SOURCE_PAIRS, "slow path must not run"
        return real_load(pairs)

    monkeypatch.setattr(ask_mod, "load_verified_claims", _guarded)

    result = ask_mod.ask("Who are the top 5 best shooters (composite) in window=sc_window_unmatched?")
    assert result["answerable"] is False
    assert "metric" in result["reason"]


def test_stale_index_falls_back_cleanly(indexable_fixture):
    tmp_path, family, _claims_path, validation_path = indexable_fixture
    # Rewrite (not delete) the validation summary WITHOUT rebuilding the
    # index: bumps its mtime past the index's stored source_mtime, so
    # is_index_fresh flips False even though the index file still exists
    # (same sleep-then-rewrite pattern proven in test_claims_index.py).
    time.sleep(0.05)
    validation_path.write_text(validation_path.read_text(encoding="ascii"), encoding="ascii")

    result = ask_mod.ask(_IDX_QUESTION)
    assert result["answerable"] is True
    assert result["answer"]["ranking"][0]["player_name"] == "Delta Player"


def _verdict_claim(claim_id: str, verdict: str, gate_module: str) -> dict:
    return {
        "claim_id": claim_id,
        "kind": "verdict",
        "question": f"What did {gate_module} find?",
        "gate_module": gate_module,
        "verdict_file": "data/fake/verdict.json",
        "verdict": verdict,
        "primary_number": 0.00042,
        "corpus_ids": ["fixture_corpus"],
        "planted_null_passed": True,
        "edge_claimed": False,
        "field_paths": {
            "verdict": "verdict",
            "primary_number": "delta",
            "planted_null_passed": "planted_null_dies",
        },
        "computed_at": "2026-07-04T00:00:00+00:00",
        "caveats": ["fixture verdict caveat"],
    }


@pytest.fixture
def fixture_sources_with_verdicts(tmp_path, monkeypatch):
    """A VERIFIED gate_verdict claim (tennis surface topic) plus a MISMATCH
    gate_verdict claim (also tennis-topic, different claim_id) so tests can
    assert only the VERIFIED one is ever answerable."""
    claims_path = tmp_path / "claims.jsonl"
    validation_path = tmp_path / "validation.json"

    verified_verdict = _verdict_claim(
        "fixture_tennis_surface_verdict", "REJECT", "tennis surface hold-prior gate"
    )
    mismatch_verdict = _verdict_claim(
        "fixture_tennis_surface_verdict_bad", "SHIP", "tennis surface hold-prior gate"
    )

    with open(claims_path, "w", encoding="ascii") as f:
        for row in (verified_verdict, mismatch_verdict):
            f.write(json.dumps(row) + "\n")

    validation_summary = {
        "component": "intel_verdict_claims_validation",
        "n_claims": 2,
        "details": [
            {"claim_id": "fixture_tennis_surface_verdict", "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": "fixture_tennis_surface_verdict_bad", "verdict": "MISMATCH", "reason": "bad"},
        ],
    }
    validation_path.write_text(json.dumps(validation_summary), encoding="ascii")

    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return validation_path, claims_path


def test_gate_verdict_answers_from_verified_claim(fixture_sources_with_verdicts):
    result = ask_mod.ask("What did the tennis surface gate find?")
    assert result["answerable"] is True
    assert result["family"] == families.FAMILY_GATE_VERDICT
    assert result["answer"]["verdict"] == "REJECT"
    assert result["answer"]["edge_claimed"] is False
    evidence = result["evidence"][0]
    assert evidence["claim_id"] == "fixture_tennis_surface_verdict"
    assert evidence["validator_verdict"] == "VERIFIED"


def test_gate_verdict_mismatch_claim_never_surfaces(fixture_sources_with_verdicts):
    result = ask_mod.ask("What did the tennis surface gate find?")
    assert result["answer"]["verdict"] != "SHIP"


def test_gate_verdict_uncovered_topic_is_honest_unanswerable(fixture_sources_with_verdicts):
    result = ask_mod.ask("What did the soccer tier gate find?")
    assert result["answerable"] is False
    assert "nearest_supported_families" in result


@pytest.fixture
def fixture_sources_ambiguous_verdicts(tmp_path, monkeypatch):
    """Two VERIFIED gate_verdict claims sharing a topic word (both match
    'tennis surface') with DIFFERENT verdicts and the SAME computed_at --
    this is the wave-38 tiebreak bug: the old code used
    max(..., key=computed_at) which is arbitrary under a tie. Also includes
    a distinct-topic claim (mlb_fatigue) that must never be pulled in."""
    claims_path = tmp_path / "claims.jsonl"
    validation_path = tmp_path / "validation.json"

    claim_a = _verdict_claim("fixture_tennis_a", "SHIP", "tennis surface gate a")
    claim_b = _verdict_claim("fixture_tennis_b", "REJECT", "tennis surface gate b")
    claim_other = _verdict_claim("fixture_mlb_fatigue", "REJECT", "mlb sp fatigue gate")

    with open(claims_path, "w", encoding="ascii") as f:
        for row in (claim_a, claim_b, claim_other):
            f.write(json.dumps(row) + "\n")

    validation_summary = {
        "component": "intel_verdict_claims_validation",
        "n_claims": 3,
        "details": [
            {"claim_id": "fixture_tennis_a", "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": "fixture_tennis_b", "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": "fixture_mlb_fatigue", "verdict": "VERIFIED", "reason": "ok"},
        ],
    }
    validation_path.write_text(json.dumps(validation_summary), encoding="ascii")

    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return validation_path, claims_path


def test_gate_verdict_tiebreak_is_deterministic_across_runs(fixture_sources_ambiguous_verdicts):
    # Same topic word, same computed_at, DIFFERENT verdicts -> old code
    # (max by computed_at, dict-iteration order under the tie) could return
    # either row nondeterministically. New code must be stable.
    results = [ask_mod.ask("What did the tennis surface gate find?") for _ in range(10)]
    first = results[0]
    for r in results[1:]:
        assert r == first


def test_gate_verdict_ambiguous_topic_reports_honestly(fixture_sources_ambiguous_verdicts):
    result = ask_mod.ask("What did the tennis surface gate find?")
    assert result["answerable"] is True
    assert "note" in result
    assert "multiple matching verdicts" in result["note"]
    assert set(result["candidates"]) == {"fixture_tennis_a", "fixture_tennis_b"}
    # the unrelated mlb-fatigue claim must never leak into the ambiguity set
    assert "fixture_mlb_fatigue" not in result["candidates"]


def test_gate_verdict_non_ambiguous_topic_still_resolves(fixture_sources_with_verdicts):
    # sanity: the pre-existing non-ambiguous fixture (VERIFIED + MISMATCH,
    # so only one VERIFIED candidate survives) must still resolve directly,
    # not go down the ambiguity path.
    result = ask_mod.ask("What did the tennis surface gate find?")
    assert result["answerable"] is True
    assert "note" not in result
    assert result["answer"]["verdict"] == "REJECT"


def test_classify_families_and_window_hint():
    top_n = families.classify("Who are the top 10 best shooters (composite) in window=last_20?")
    assert top_n.family == families.FAMILY_TOP_N
    assert top_n.top_n == 10
    assert top_n.window_hint == "last_20"

    lookup = families.classify("Where does Stephen Curry rank on fg3_pct in window=season_2024-25?")
    assert lookup.family == families.FAMILY_ENTITY_LOOKUP
    assert lookup.entity_name == "Stephen Curry"
    assert lookup.window_hint == "season_2024-25"

    provenance = families.classify("How do you know? Show the evidence for nba_shooting_composite_last_20.")
    assert provenance.family == families.FAMILY_PROVENANCE
    assert provenance.claim_id == "nba_shooting_composite_last_20"

    gate_verdict = families.classify("What did the tennis surface gate find?")
    assert gate_verdict.family == families.FAMILY_GATE_VERDICT
    assert "tennis_surface" in gate_verdict.topic_hints

    unknown = families.classify("What time is it?")
    assert unknown.family is None


# --- compose_fit (PROGRAM v3 item 2, FIT question family) -------------------

def _fixture_fit_claims() -> tuple[dict, dict, dict]:
    archetype_claim = {
        "claim_id": ask_mod._FIT_ARCHETYPE_CLAIM_ID,
        "kind": "ranking",
        "question": "archetype profile?",
        "criteria": {"metric": "usage_pct", "formula": "usage_pct", "entity_key": "pid"},
        "ranking": [
            {"rank": 1, "pid": 999, "player_name": "Fixture Star", "value": 0.9, "n": None,
             "team": "ATL", "posgroup": "WING", "archetype": "WING_CREATOR",
             "creation": 0.9, "playmaking": 0.8, "spacing": 0.5, "rim_pressure": 0.2,
             "rebounding": 0.4, "rim_protect": 0.3, "perimeter_d": 0.6, "self_create": 0.7,
             "usage_pct": 0.9},
        ],
        "source_files": ["data/fake/archetype.parquet"],
        "computed_at": "2026-07-05T00:00:00+00:00",
        "n_considered": 10, "n_excluded_below_floor": 2, "caveats": ["fixture caveat"],
    }
    scheme_claim = {
        "claim_id": ask_mod._FIT_SCHEME_CLAIM_ID,
        "kind": "ranking",
        "question": "scheme identity?",
        "criteria": {"metric": "wf_ppp_allowed_z", "formula": "wf_ppp_allowed_z", "entity_key": "team"},
        "ranking": [
            {"rank": 1, "team": "ATL", "value": 0.5, "n": 20,
             "dominant_tag": "SWITCH HEAVY", "best_scheme": None, "confidence": "high"},
        ],
        "source_files": ["data/fake/scheme.parquet"],
        "computed_at": "2026-07-05T00:00:00+00:00",
        "n_considered": 30, "n_excluded_below_floor": 0, "caveats": ["fixture caveat"],
    }
    vacancy_claim = {
        "claim_id": ask_mod._FIT_VACANCY_CLAIM_ID,
        "kind": "ranking",
        "question": "role vacancy?",
        "criteria": {"metric": "vacancy_share", "formula": "mean(is_below_median)", "entity_key": "team_posgroup"},
        "ranking": [
            {"rank": 1, "team_posgroup": "ATL|WING", "value": 0.4444, "n": 9,
             "team": "ATL", "posgroup": "WING"},
        ],
        "source_files": ["data/fake/vacancy_snapshot.parquet"],
        "computed_at": "2026-07-05T00:00:00+00:00",
        "n_considered": 40, "n_excluded_below_floor": 3, "caveats": ["fixture caveat"],
    }
    return archetype_claim, scheme_claim, vacancy_claim


@pytest.fixture
def fixture_fit_sources(tmp_path, monkeypatch):
    """One VERIFIED row for each of the 3 fit-ingredient claims (Fixture
    Star on ATL, posgroup WING) -- a full-pop compose_fit lookup should
    join all three cleanly."""
    # store name must be in ask._FIT_CLAIM_STORES -- compose_fit now scopes the
    # load via pairs_for_claim_stores so a bare whole-corpus load can't OOM on
    # the 2.8GB nba_player_box_rate store.
    claims_path = tmp_path / "nba_fit_ingredient_claims.jsonl"
    validation_path = tmp_path / "nba_fit_ingredient_claims_validation.json"
    archetype_claim, scheme_claim, vacancy_claim = _fixture_fit_claims()

    with open(claims_path, "w", encoding="ascii") as f:
        for row in (archetype_claim, scheme_claim, vacancy_claim):
            f.write(json.dumps(row) + "\n")

    validation_summary = {
        "component": "fit_claims_validation",
        "n_claims": 3,
        "details": [
            {"claim_id": ask_mod._FIT_ARCHETYPE_CLAIM_ID, "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": ask_mod._FIT_SCHEME_CLAIM_ID, "verdict": "VERIFIED", "reason": "ok"},
            {"claim_id": ask_mod._FIT_VACANCY_CLAIM_ID, "verdict": "VERIFIED", "reason": "ok"},
        ],
    }
    validation_path.write_text(json.dumps(validation_summary), encoding="ascii")

    monkeypatch.setattr(ask_mod, "CLAIM_SOURCE_PAIRS", ((validation_path, claims_path),))
    return validation_path, claims_path


def test_compose_fit_full_population_lookup_joins_all_three_ingredients(fixture_fit_sources):
    result = ask_mod.compose_fit("Fixture Star", "ATL")
    assert result["answerable"] is True
    assert result["family"] == ask_mod.FAMILY_FIT
    answer = result["answer"]
    assert answer["archetype_profile"]["posgroup"] == "WING"
    assert answer["archetype_profile"]["archetype"] == "WING_CREATOR"
    assert answer["team_scheme_identity"]["dominant_tag"] == "SWITCH HEAVY"
    assert answer["role_vacancy"]["team_posgroup"] == "ATL|WING"
    assert answer["role_vacancy"]["vacancy_share"] == 0.4444
    # never predictive/edge language in a fit answer
    blob = json.dumps(answer).lower()
    for forbidden in ask_mod._FORBIDDEN_FIT_WORDS:
        assert forbidden not in blob
    # every ingredient carries provenance
    assert len(result["evidence"]) == 3
    claim_ids = {e["claim_id"] for e in result["evidence"]}
    assert claim_ids == {
        ask_mod._FIT_ARCHETYPE_CLAIM_ID, ask_mod._FIT_SCHEME_CLAIM_ID, ask_mod._FIT_VACANCY_CLAIM_ID,
    }
    for e in result["evidence"]:
        assert e["validator_verdict"] == "VERIFIED"


def test_compose_fit_missing_ingredient_is_honest_unanswerable(fixture_fit_sources):
    # player exists in the archetype claim, but the fixture only has a
    # scheme/vacancy row for ATL -- asking about a DIFFERENT team should
    # honestly name team_scheme_identity as the missing ingredient, not
    # silently compose from a partial join.
    result = ask_mod.compose_fit("Fixture Star", "BOS")
    assert result["answerable"] is False
    assert result["family"] == ask_mod.FAMILY_FIT
    assert result["missing_ingredient"] == "team_scheme_identity"

    # a player entirely absent from the archetype claim is also honest
    # UNANSWERABLE, naming archetype_profile as the missing ingredient
    result2 = ask_mod.compose_fit("Nobody Fake", "ATL")
    assert result2["answerable"] is False
    assert result2["missing_ingredient"] == "archetype_profile"


# --- discover_claim_source_pairs (PROGRAM v3 ask-coverage lane) --------------

def test_discover_claim_source_pairs_matches_by_stem_convention(tmp_path):
    """<stem>.jsonl auto-pairs with <stem>_validation.json in the SAME
    directory -- the convention every store except the 2 legacy overrides
    already follows."""
    (tmp_path / "some_new_sport_claims.jsonl").write_text('{"claim_id": "x"}\n', encoding="ascii")
    (tmp_path / "some_new_sport_claims_validation.json").write_text("{}", encoding="ascii")

    pairs = ask_mod.discover_claim_source_pairs(tmp_path)
    assert len(pairs) == 1
    validation_path, claims_path = pairs[0]
    assert claims_path.name == "some_new_sport_claims.jsonl"
    assert validation_path.name == "some_new_sport_claims_validation.json"


def test_discover_claim_source_pairs_skips_unpaired_jsonl(tmp_path):
    """A *.jsonl with NO matching _validation.json (and no legacy override)
    is silently skipped -- unvalidated claims stay invisible, discovery
    never errors on a partial store."""
    (tmp_path / "orphan_claims.jsonl").write_text('{"claim_id": "y"}\n', encoding="ascii")
    (tmp_path / "paired_claims.jsonl").write_text('{"claim_id": "z"}\n', encoding="ascii")
    (tmp_path / "paired_claims_validation.json").write_text("{}", encoding="ascii")

    pairs = ask_mod.discover_claim_source_pairs(tmp_path)
    claims_names = {c.name for _v, c in pairs}
    assert "orphan_claims.jsonl" not in claims_names
    assert "paired_claims.jsonl" in claims_names
    assert len(pairs) == 1


def test_discover_claim_source_pairs_empty_dir_returns_empty(tmp_path):
    empty_dir = tmp_path / "does_not_exist"
    assert ask_mod.discover_claim_source_pairs(empty_dir) == ()


def test_discover_claim_source_pairs_deterministic_order(tmp_path):
    for stem in ("zzz_claims", "aaa_claims", "mmm_claims"):
        (tmp_path / f"{stem}.jsonl").write_text('{"claim_id": "q"}\n', encoding="ascii")
        (tmp_path / f"{stem}_validation.json").write_text("{}", encoding="ascii")

    pairs = ask_mod.discover_claim_source_pairs(tmp_path)
    names = [c.name for _v, c in pairs]
    assert names == sorted(names)


def test_real_repo_discovery_covers_every_wave51_store():
    """END-TO-END proof (no monkeypatch, the actual repo tree): the
    automatic glob discovery finds every claim store this lane's wave-51
    modules produced, so ask() covers them with zero registration here."""
    pairs = ask_mod.discover_claim_source_pairs()
    claims_names = {c.name for _v, c in pairs}
    for expected in (
        "wnba_claims.jsonl",
        "tennis_claims_v3.jsonl",
        "catcher_framing_claims.jsonl",
        "platoon_split_claims.jsonl",
        "umpire_zone_claims.jsonl",
        "nba_fit_ingredient_claims.jsonl",
        "npb_kbo_claims.jsonl",  # lane npb-kbo-strength-claims
    ):
        assert expected in claims_names, f"{expected} not discovered from the real repo tree"

    # every discovered pair's validation file must actually exist on disk
    for validation_path, claims_path in pairs:
        assert validation_path.exists(), f"{validation_path} missing for {claims_path}"
        assert claims_path.exists()


def test_real_repo_lebron_james_rank_lookup_is_verified():
    """ACCEPTANCE (a): a LeBron James rank lookup on a dimension wave-51
    says he IS rankable on -- nba_fit_archetype_profile_current's usage_pct
    (rank 95, window=current) -- returns a VERIFIED answer with rank+n.
    Deliberately scoped to nba_fit_ingredient_claims' OWN dedicated
    <stem>_validation.json (not the shared data/frontend/ops/
    intel_claims_validation.json path nba_shooting_claims.jsonl still
    depends on -- see spawned task re: DEFAULT_OUTPUT collision -- so this
    acceptance check is immune to that pre-existing, out-of-lane race)."""
    result = ask_mod.ask("Where does LeBron James rank on usage_pct?")
    assert result["answerable"] is True
    assert result["answer"]["entity_name"] == "LeBron James"
    usage_hit = next(
        r for r in result["answer"]["rankings"] if r["metric"] == "usage_pct" and r["window"] == "career_to_date"
    )
    assert usage_hit["rank"] == 95
    assert any(e["validator_verdict"] == "VERIFIED" for e in result["evidence"])


def test_real_repo_below_floor_player_is_honest_excluded_not_a_miss():
    """ACCEPTANCE (b): Sami Whitcomb (n_games_played=2 in the source WNBA
    parquet, floor is n_games_played>=10) returns the honest
    excluded-below-floor reason, never a generic/silent miss."""
    result = ask_mod.ask("Where does Sami Whitcomb rank on ts_pct in window=season_2026_wnba?")
    assert result["answerable"] is False
    assert "min_sample floor" in result["reason"]


def test_real_repo_compose_fit_non_star_player_composes():
    """ACCEPTANCE (c): compose_fit for a NON-star player (Taurean Prince, a
    rotation wing, not a franchise star) + his real team composes cleanly
    from the 3 VERIFIED fit-ingredient claims plus the fit-validity gate
    REJECT citation, with full provenance."""
    result = ask_mod.compose_fit("Taurean Prince", "MIL")
    assert result["answerable"] is True
    assert result["answer"]["archetype_profile"]["posgroup"] == "WING"
    assert len(result["evidence"]) == 4
    assert all(e["validator_verdict"] == "VERIFIED" for e in result["evidence"])
    claim_ids = {e["claim_id"] for e in result["evidence"]}
    assert ask_mod._FIT_VALIDITY_CLAIM_ID in claim_ids
    assert "REJECT" in result["answer"]["note"]


def test_real_repo_tennis_h2h_pairkeyed_claim_discovered_and_answerable():
    """ACCEPTANCE (d): the lane tennis-h2h-fullpairs store
    (tennis_h2h_claims.jsonl, pair-keyed entity_key=[p1_id, p2_id]) is
    AUTO-DISCOVERED via the same glob every other store uses (no
    registration here) and answerable via the provenance family -- proving
    the FIRST production pair-keyed claim flows end-to-end through ask()."""
    pairs = ask_mod.discover_claim_source_pairs()
    assert "tennis_h2h_claims.jsonl" in {c.name for _v, c in pairs}

    result = ask_mod.ask(
        "How do you know? Show the evidence for tennis_h2h_win_share_atp_fullpairs."
    )
    assert result["answerable"] is True
    assert result["answer"]["claim_id"] == "tennis_h2h_win_share_atp_fullpairs"
    assert result["answer"]["criteria"]["entity_key"] == ["p1_id", "p2_id"]
    assert result["answer"]["n_considered"] > result["answer"]["n_excluded_below_floor"]
    caveats = " ".join(result["answer"]["caveats"]).lower()
    assert "not a predictor" in caveats
    assert all(e["validator_verdict"] == "VERIFIED" for e in result["evidence"])


# --- fit-validity-into-ask (PROGRAM v3 closure) ------------------------------

def test_real_repo_validity_question_returns_reject_claim_with_provenance():
    """ACCEPTANCE (b): a validity question ('does scheme fit predict
    performance after a move') routes to gate_verdict and returns the
    pre-registered fit-validity gate's REJECT claim (pooled_delta<0,
    n_moves=417, folds=5, sign_holds=1/5, both planted nulls died), citing
    the read-only verdict json as evidence."""
    result = ask_mod.ask("Does scheme fit predict performance after a move?")
    assert result["answerable"] is True
    assert result["family"] == families.FAMILY_GATE_VERDICT
    answer = result["answer"]
    assert answer["verdict"] == "REJECT"
    assert answer["primary_number"] < 0
    assert answer["planted_null_passed"] is True
    assert answer["edge_claimed"] is False
    assert answer["verdict_file"] == "data/domains/nba/fit_validity_gate_verdict.json"
    evidence = result["evidence"][0]
    assert evidence["claim_id"] == "nba_fit_validity_gate_verdict"
    assert evidence["validator_verdict"] == "VERIFIED"


def test_real_repo_compose_fit_note_cites_validity_reject_inline():
    """ACCEPTANCE (c): every compose_fit() SCOUTING answer cites the
    fit-validity gate's REJECT verdict inline in its note field -- the
    composition never implies validity it does not have."""
    result = ask_mod.compose_fit("Taurean Prince", "MIL")
    assert result["answerable"] is True
    note = result["answer"]["note"]
    assert "descriptive" in note.lower()
    assert "REJECT" in note
    blob = json.dumps(result["answer"]).lower()
    for forbidden in ask_mod._FORBIDDEN_FIT_WORDS:
        assert forbidden not in blob


# --- P0: streaming _load_jsonl + per-file line cap (unbounded-load fix) ------
def test_load_jsonl_streams_and_caps(tmp_path):
    """_load_jsonl is a STREAMING generator (never materializes the whole
    file -- the old readlines() spiked 2.8GB on nba_player_box_rate) and
    `max_lines` caps physical lines READ. A malformed line is still skipped."""
    path = tmp_path / "s.jsonl"
    with open(path, "w", encoding="ascii") as f:
        f.write(json.dumps({"claim_id": "a"}) + "\n")
        f.write(json.dumps({"claim_id": "b"}) + "\n")
        f.write("{ not json\n")            # malformed -> skipped, not raised
        f.write(json.dumps({"claim_id": "c"}) + "\n")
        f.write(json.dumps({"claim_id": "d"}) + "\n")

    gen = ask_mod._load_jsonl(path)
    assert iter(gen) is gen                 # a generator, not a list
    assert [r["claim_id"] for r in ask_mod._load_jsonl(path)] == ["a", "b", "c", "d"]
    # cap=2 reads only the first 2 physical lines -> only a, b parsed
    assert [r["claim_id"] for r in ask_mod._load_jsonl(path, max_lines=2)] == ["a", "b"]
    # missing file yields nothing (fail-open), still an iterator
    assert list(ask_mod._load_jsonl(tmp_path / "nope.jsonl")) == []


def test_load_verified_claims_max_lines_per_file_truncates(tmp_path, monkeypatch):
    """A fat store (6 VERIFIED rows) truncates at the per-file cap; claim_ids
    past the cap are honestly absent. Default None loads all of them -- the
    full-scan consumers (coverage report / fit-sweep validators) rely on that."""
    claims_path = tmp_path / "fat.jsonl"
    validation_path = tmp_path / "fat_validation.json"
    ids = [f"fat_{i}" for i in range(6)]
    with open(claims_path, "w", encoding="ascii") as f:
        for cid in ids:
            f.write(json.dumps({"claim_id": cid, "kind": "ranking"}) + "\n")
    validation_path.write_text(json.dumps(
        {"details": [{"claim_id": cid, "verdict": "VERIFIED"} for cid in ids]}), encoding="ascii")
    pairs = ((validation_path, claims_path),)

    capped = ask_mod.load_verified_claims(pairs, max_lines_per_file=3)
    assert set(capped) == {"fat_0", "fat_1", "fat_2"}      # rows past line 3 truncated
    assert "fat_5" not in capped
    full = ask_mod.load_verified_claims(pairs)              # default None -> no cap
    assert set(full) == set(ids)
