"""scripts.platform.atlas.build_all — Multi-sport atlas build driver.

Usage: python scripts/platform/atlas/build_all.py [--sport tennis|soccer|mlb|nba|all] [--out vault/Sports]

Per sport: build_atlas → H2H (Matchups/) → Playstyles/Archetypes → Tournaments (tennis) → Seasons
(soccer/mlb/nba).  All steps graceful-skip on ImportError/exception.  Always writes _Hub.md.
Discipline: Py3.9, from __future__ import annotations, type hints, no edge language, 300 LOC ceiling.
"""
from __future__ import annotations

import argparse
import importlib
import inspect
import logging
import sys
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Tuple

_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parents[3]  # scripts/platform/atlas/ → repo root
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

# (sport_id, display_name, adapter_module, corpus_hint)
_SPORT_MANIFEST: List[Tuple[str, str, str, str]] = [
    ("tennis_atp",     "Tennis",         "domains.tennis.atlas",               "data/domains/tennis"),
    ("soccer_fd",      "Soccer",         "domains.soccer.atlas",               "data/domains/soccer"),
    ("mlb_sbro",       "MLB",            "domains.mlb.atlas",                  "data/domains/mlb"),
    ("basketball_nba", "Basketball_NBA", "domains.basketball_nba.memory_atlas", "data"),
]

_ALIASES: Dict[str, str] = {
    "tennis": "tennis_atp", "tennis_atp": "tennis_atp",
    "soccer": "soccer_fd",  "soccer_fd":  "soccer_fd",
    "mlb":    "mlb_sbro",   "mlb_sbro":   "mlb_sbro",
    "nba":    "basketball_nba", "basketball": "basketball_nba",
    "basketball_nba": "basketball_nba",
    "all":    "all",
}


# ---------------------------------------------------------------------------
# Hub note
# ---------------------------------------------------------------------------
def _hub_body(today: str, table: str) -> str:
    return (
        f"---\ntags: [sport, memory-graph, hub, index]\nupdated: {today}\n---\n"
        "# Multi-Sport Intelligence Hub\n\n"
        "> Registry-driven knowledge graph spanning every sport domain in the platform.\n"
        "> Auto-generated by `scripts/platform/atlas/build_all.py` — edit the driver, not this file.\n\n"
        "Each sport has its own intelligence folder under `vault/Sports/<Sport>/` with an\n"
        "`_Index` note as the entry point.  The existing NBA intelligence vault lives\n"
        "at `vault/` (Home, Intelligence/, MOC-* notes).\n\n---\n\n"
        "## Sport Index\n\n| Sport | Corpus | Index |\n|-------|--------|-------|\n"
        f"{table}\n\n---\n\n"
        "## NBA Intelligence Vault (existing)\n\n"
        "The NBA system predates the multi-sport platform.  Its intelligence artifacts live\n"
        "in the main vault rather than `vault/Sports/Basketball_NBA/`.\n\n"
        "- [[Home]] — platform home note, model performance, current state\n"
        "- [[Intelligence/_Scout_Index]] — NBA scout / player atlas index\n"
        "- [[MOC-CV]] · [[MOC-Models]] · [[MOC-Betting]] · [[MOC-Strategy]]\n\n---\n\n"
        "## Tags\n\n#sport #memory-graph #hub #index\n\n---\n\n"
        f"*Generated {today} by `scripts/platform/atlas/build_all.py`*\n"
    )


def write_hub(out_dir: Path, built_sports: List[Tuple[str, str, int]]) -> Path:
    """Write (or overwrite) ``<out_dir>/_Hub.md``.  Returns the hub path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    built_ids = {sid for sid, _, _ in built_sports}
    rows: List[str] = []
    for sport_id, display_name, _, corpus_hint in _SPORT_MANIFEST:
        corpus_label = Path(corpus_hint).name
        if sport_id in built_ids:
            count = next(n for s, _, n in built_sports if s == sport_id)
            link = f"[[{display_name}/_Index]] · {count} notes"
        else:
            link = f"[[{display_name}/_Index]] *(pending)* · module absent — skipped"
        rows.append(f"| {display_name} | `{corpus_label}` | {link} |")
    hub_path = out_dir / "_Hub.md"
    hub_path.write_text(_hub_body(date.today().isoformat(), "\n".join(rows)), encoding="utf-8")
    return hub_path


# ---------------------------------------------------------------------------
# Per-sport build helpers
# ---------------------------------------------------------------------------
def _load_build_fn(adapter_module: str):  # type: ignore[return]
    """Import *adapter_module* and return its ``build_atlas`` callable or None."""
    try:
        mod = importlib.import_module(adapter_module)
    except ImportError as exc:
        log.debug("ImportError for %s: %s", adapter_module, exc)
        return None
    fn = getattr(mod, "build_atlas", None)
    if fn is None:
        log.warning("%s is importable but exposes no build_atlas() — skipping.", adapter_module)
    return fn


def _derive_domain(adapter_module: str) -> str:
    """Return domain from adapter_module (``"domains.tennis.atlas"`` → ``"tennis"``)."""
    parts = adapter_module.split(".")
    return parts[1] if len(parts) >= 2 and parts[0] == "domains" else parts[0]


def _call_optional(fn, out_dir: Path, corpus_dir: Path, corpus_kwarg: str) -> int:
    """Call *fn(out_dir, <corpus_kwarg>=corpus_dir)* if the kwarg is accepted; else call fn(out_dir).

    Returns len(result) or 0.  out_dir is created before the call.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    sig = inspect.signature(fn)
    notes: List[Path] = fn(out_dir, **{corpus_kwarg: corpus_dir}) if corpus_kwarg in sig.parameters else fn(out_dir)
    return len(notes) if notes is not None else 0


def _try_build_optional(
    module_path: str,
    fn_name: str,
    subdir: str,
    sport_out: Path,
    corpus_dir: Path,
    corpus_kwarg: str = "corpus_dir",
) -> int:
    """Import module_path, call fn_name → sport_out/subdir (sig-probed kwarg).  Returns 0 on any failure."""
    try:
        mod = importlib.import_module(module_path)
    except ImportError:
        log.debug("No %s — skipping %s.", module_path, subdir)
        return 0
    fn = getattr(mod, fn_name, None)
    if fn is None:
        return 0
    try:
        count = _call_optional(fn, sport_out / subdir, corpus_dir, corpus_kwarg)
        log.info("  %s (%s): %d note(s)", subdir, module_path.rsplit(".", 1)[-1], count)
        return count
    except Exception as exc:  # noqa: BLE001
        log.warning("  %s.%s raised %s: %s — skipping %s.", module_path, fn_name, type(exc).__name__, exc, subdir)
        return 0


def _try_build_h2h(domain: str, sport_out: Path, corpus_dir: Path) -> int:
    """Try ``domains.<domain>.atlas_h2h.build_h2h`` → Matchups/.  Returns note count or 0."""
    return _try_build_optional(
        f"domains.{domain}.atlas_h2h", "build_h2h", "Matchups", sport_out, corpus_dir
    )


def _try_build_playstyles(domain: str, sport_out: Path, corpus_dir: Path) -> int:
    """atlas_playstyles → Playstyles/ (tennis/soccer/mlb) or memory_atlas_archetypes → Archetypes/ (nba)."""
    if domain == "basketball_nba":
        return _try_build_optional(
            f"domains.{domain}.memory_atlas_archetypes", "build_archetypes",
            "Archetypes", sport_out, corpus_dir, "data_dir",
        )
    return _try_build_optional(
        f"domains.{domain}.atlas_playstyles", "build_playstyles",
        "Playstyles", sport_out, corpus_dir,
    )


def _try_build_tournaments(domain: str, sport_out: Path, corpus_dir: Path) -> int:
    """atlas_tournaments → Tournaments/ (tennis only).  Returns 0 for all other domains."""
    if domain != "tennis":
        return 0
    return _try_build_optional(
        f"domains.{domain}.atlas_tournaments", "build_tournaments",
        "Tournaments", sport_out, corpus_dir,
    )


def _try_build_seasons(domain: str, sport_out: Path, corpus_dir: Path) -> int:
    """atlas_seasons/memory_atlas_seasons → Seasons/ (soccer/mlb/nba).  Returns 0 otherwise."""
    if domain == "basketball_nba":
        return _try_build_optional(
            f"domains.{domain}.memory_atlas_seasons", "build_seasons",
            "Seasons", sport_out, corpus_dir, "data_dir",
        )
    if domain in {"soccer", "mlb"}:
        return _try_build_optional(
            f"domains.{domain}.atlas_seasons", "build_seasons",
            "Seasons", sport_out, corpus_dir,
        )
    return 0


def build_sport(
    sport_id: str,
    display_name: str,
    adapter_module: str,
    corpus_hint: str,
    out_dir: Path,
) -> Optional[int]:
    """Build atlas + H2H + Playstyles/Archetypes + Tournaments + Seasons for one sport.

    Returns total note count or None when the adapter module is absent.
    """
    log.info("Building atlas: %s (%s) …", display_name, sport_id)
    build_fn = _load_build_fn(adapter_module)
    if build_fn is None:
        log.warning("  Skipping %s — module %s not importable.", display_name, adapter_module)
        return None

    sport_out = out_dir / display_name
    sport_out.mkdir(parents=True, exist_ok=True)
    corpus_dir = _REPO_ROOT / corpus_hint

    try:
        sig = inspect.signature(build_fn)
        notes: List[Path] = (
            build_fn(sport_out, corpus_dir=corpus_dir)
            if "corpus_dir" in sig.parameters
            else build_fn(sport_out)
        )
    except Exception as exc:  # noqa: BLE001
        log.warning("  build_atlas for %s raised %s: %s — skipping.", display_name, type(exc).__name__, exc)
        return None

    count = len(notes) if notes is not None else 0
    log.info("  %s: %d atlas note(s) written to %s", display_name, count, sport_out)

    domain = _derive_domain(adapter_module)
    total = (
        count
        + _try_build_h2h(domain, sport_out, corpus_dir)
        + _try_build_playstyles(domain, sport_out, corpus_dir)
        + _try_build_tournaments(domain, sport_out, corpus_dir)
        + _try_build_seasons(domain, sport_out, corpus_dir)
    )
    return total


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
def main(argv: Optional[List[str]] = None) -> int:
    """Build atlases and write hub.  Returns 0 on success (graceful-skips count as success)."""
    parser = argparse.ArgumentParser(prog="build_all.py", description="Build per-sport Obsidian atlases.")
    parser.add_argument("--sport", default="all", metavar="SPORT",
                        help="Sport: tennis|soccer|mlb|nba|all (default: all).")
    parser.add_argument("--out", default="vault/Sports", metavar="DIR",
                        help="Output root (default: vault/Sports).")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    resolved = _ALIASES.get(args.sport.lower())
    if resolved is None:
        log.error("Unknown --sport %r.  Valid: %s", args.sport, sorted(_ALIASES))
        return 1

    out_dir = _REPO_ROOT / args.out if not Path(args.out).is_absolute() else Path(args.out)
    targets = _SPORT_MANIFEST if resolved == "all" else [e for e in _SPORT_MANIFEST if e[0] == resolved]
    if not targets:
        log.error("No manifest entry for %r.", resolved)
        return 1

    built: List[Tuple[str, str, int]] = []
    for sport_id, display_name, adapter_module, corpus_hint in targets:
        count = build_sport(sport_id, display_name, adapter_module, corpus_hint, out_dir)
        if count is not None:
            built.append((sport_id, display_name, count))

    hub_path = write_hub(out_dir, built)

    def _disp(p: Path) -> str:
        try:
            return str(p.relative_to(_REPO_ROOT))
        except ValueError:
            return str(p)

    print()
    print("=" * 60)
    print("Multi-sport atlas build complete")
    print(f"  Hub note : {_disp(hub_path)}")
    print(f"  Out dir  : {_disp(out_dir)}")
    print()
    for _, display_name, note_count in built:
        print(f"  {display_name:<20} {note_count:>4} note(s)")
    for sid, dn, _, _ in targets:
        if sid not in {s for s, _, _ in built}:
            print(f"  {dn:<20}  --- skipped (module absent)")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
