"""scripts.platform.atlas.build_all — Multi-sport atlas + H2H build driver.

Usage: python scripts/platform/atlas/build_all.py [--sport tennis|soccer|mlb|nba|all] [--out vault/Sports]

Per sport: imports ``domains.<sport>.atlas.build_atlas`` (graceful-skip on ImportError),
then tries ``domains.<domain>.atlas_h2h.build_h2h`` for Matchups/ notes (graceful-skip
when absent — e.g. NBA).  Always writes ``<out_dir>/_Hub.md``.
Discipline: Py3.9, from __future__ import annotations, type hints, no edge language, 300 LOC ceiling.
"""
from __future__ import annotations

import argparse
import importlib
import inspect
import logging
import sys
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Repo root — PYTHONPATH-agnostic
# ---------------------------------------------------------------------------
_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parents[3]  # scripts/platform/atlas/ → repo root
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Sport manifest: (sport_id, display_name, adapter_module, corpus_hint)
# ---------------------------------------------------------------------------
_SPORT_MANIFEST: List[Tuple[str, str, str, str]] = [
    ("tennis_atp",    "Tennis",         "domains.tennis.atlas",         "data/domains/tennis"),
    ("soccer_fd",     "Soccer",         "domains.soccer.atlas",          "data/domains/soccer"),
    ("mlb_sbro",      "MLB",            "domains.mlb.atlas",             "data/domains/mlb"),
    ("basketball_nba","Basketball_NBA", "domains.basketball_nba.memory_atlas", "data"),
]

# CLI aliases (lower-case) → sport_id
_ALIASES: Dict[str, str] = {
    "tennis": "tennis_atp", "tennis_atp": "tennis_atp",
    "soccer": "soccer_fd",  "soccer_fd":  "soccer_fd",
    "mlb":    "mlb_sbro",   "mlb_sbro":   "mlb_sbro",
    "nba":    "basketball_nba", "basketball": "basketball_nba",
    "basketball_nba": "basketball_nba",
    "all":    "all",
}

# ---------------------------------------------------------------------------
# Hub note writer
# ---------------------------------------------------------------------------
def write_hub(out_dir: Path, built_sports: List[Tuple[str, str, int]]) -> Path:
    """Write (or overwrite) ``<out_dir>/_Hub.md``.  Returns the hub path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    hub_path = out_dir / "_Hub.md"
    today = date.today().isoformat()
    built_ids = {sid for sid, _, _ in built_sports}

    rows: List[str] = []
    for sport_id, display_name, _, corpus_hint in _SPORT_MANIFEST:
        corpus_label = Path(corpus_hint).name
        if sport_id in built_ids:
            count = next(n for s, _, n in built_sports if s == sport_id)
            link = f"[[{display_name}/_Index]] · {count} notes"
        else:
            link = f"[[{display_name}/_Index]] *(pending)* · module absent — skipped"
        rows.append(f"| {display_name} | `{corpus_label}` | {link} |")

    table = "\n".join(rows)

    hub_path.write_text(
        f"""\
---
tags: [sport, memory-graph, hub, index]
updated: {today}
---
# Multi-Sport Intelligence Hub

> Registry-driven knowledge graph spanning every sport domain in the platform.
> Auto-generated by `scripts/platform/atlas/build_all.py` — edit the driver, not this file.

Each sport has its own intelligence folder under `vault/Sports/<Sport>/` with an
`_Index` note as the entry point.  The existing NBA intelligence vault lives
at `vault/` (Home, Intelligence/, MOC-* notes).

---

## Sport Index

| Sport | Corpus | Index |
|-------|--------|-------|
{table}

---

## NBA Intelligence Vault (existing)

The NBA system predates the multi-sport platform.  Its intelligence artifacts live
in the main vault rather than `vault/Sports/Basketball_NBA/`.

- [[Home]] — platform home note, model performance, current state
- [[Intelligence/_Scout_Index]] — NBA scout / player atlas index
- [[MOC-CV]] · [[MOC-Models]] · [[MOC-Betting]] · [[MOC-Strategy]]

---

## Tags

#sport #memory-graph #hub #index

---

*Generated {today} by `scripts/platform/atlas/build_all.py`*
""",
        encoding="utf-8",
    )
    return hub_path


# ---------------------------------------------------------------------------
# Per-sport build helpers
# ---------------------------------------------------------------------------
def _load_build_fn(adapter_module: str):  # type: ignore[return]
    """Import *adapter_module* and return its ``build_atlas`` callable or None."""
    try:
        mod = importlib.import_module(adapter_module)
    except ImportError as exc:
        log.debug("ImportError for %s: %s", adapter_module, exc)
        return None
    fn = getattr(mod, "build_atlas", None)
    if fn is None:
        log.warning(
            "%s is importable but exposes no build_atlas() — skipping.",
            adapter_module,
        )
    return fn


def _derive_domain(adapter_module: str) -> str:
    """Return domain name from adapter_module (``"domains.tennis.atlas"`` → ``"tennis"``).."""
    parts = adapter_module.split(".")
    return parts[1] if len(parts) >= 2 and parts[0] == "domains" else parts[0]


def _try_build_h2h(domain: str, sport_out: Path, corpus_dir: Path) -> int:
    """Import ``domains.<domain>.atlas_h2h`` and call ``build_h2h`` if present.

    Returns note count written, or 0 (graceful-skip on ImportError or any exception).
    """
    try:
        mod = importlib.import_module(f"domains.{domain}.atlas_h2h")
    except ImportError:
        log.debug("No atlas_h2h for domain %r — skipping H2H step.", domain)
        return 0
    h2h_fn = getattr(mod, "build_h2h", None)
    if h2h_fn is None:
        log.debug("domains.%s.atlas_h2h has no build_h2h — skipping.", domain)
        return 0
    try:
        matchups_dir = sport_out / "Matchups"
        matchups_dir.mkdir(parents=True, exist_ok=True)
        sig = inspect.signature(h2h_fn)
        if "corpus_dir" in sig.parameters:
            notes: List[Path] = h2h_fn(matchups_dir, corpus_dir=corpus_dir)
        else:
            notes = h2h_fn(matchups_dir)
        count = len(notes) if notes is not None else 0
        log.info("  H2H (%s): %d matchup note(s) in %s", domain, count, matchups_dir)
        return count
    except Exception as exc:  # noqa: BLE001
        log.warning("  build_h2h for %r raised %s: %s — skipping H2H.", domain, type(exc).__name__, exc)
        return 0


def build_sport(
    sport_id: str,
    display_name: str,
    adapter_module: str,
    corpus_hint: str,
    out_dir: Path,
) -> Optional[int]:
    """Build atlas (and H2H notes if available) for one sport.

    Returns total note count or None when the atlas module is absent / raises.
    """
    log.info("Building atlas: %s (%s) …", display_name, sport_id)
    build_fn = _load_build_fn(adapter_module)
    if build_fn is None:
        log.warning(
            "  Skipping %s — module %s not importable (sibling agent pending).",
            display_name, adapter_module,
        )
        return None

    sport_out = out_dir / display_name
    sport_out.mkdir(parents=True, exist_ok=True)
    corpus_dir = _REPO_ROOT / corpus_hint

    try:
        sig = inspect.signature(build_fn)
        if "corpus_dir" in sig.parameters:
            notes: List[Path] = build_fn(sport_out, corpus_dir=corpus_dir)
        else:
            notes = build_fn(sport_out)
    except Exception as exc:  # noqa: BLE001
        log.warning(
            "  build_atlas for %s raised %s: %s — skipping.",
            display_name, type(exc).__name__, exc,
        )
        return None

    count = len(notes) if notes is not None else 0
    log.info("  %s: %d atlas note(s) written to %s", display_name, count, sport_out)

    domain = _derive_domain(adapter_module)
    h2h_count = _try_build_h2h(domain, sport_out, corpus_dir)
    return count + h2h_count


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
def main(argv: Optional[List[str]] = None) -> int:
    """Build atlases and write hub.  Returns 0 on success (graceful-skip counts as success)."""
    parser = argparse.ArgumentParser(
        prog="build_all.py",
        description="Build per-sport Obsidian atlases and write _Hub.md.",
    )
    parser.add_argument(
        "--sport", default="all", metavar="SPORT",
        help="Sport: tennis|soccer|mlb|nba|all (default: all).",
    )
    parser.add_argument(
        "--out", default="vault/Sports", metavar="DIR",
        help="Output root (default: vault/Sports).",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    resolved = _ALIASES.get(args.sport.lower())
    if resolved is None:
        log.error("Unknown --sport %r.  Valid: %s", args.sport, sorted(_ALIASES))
        return 1

    out_dir = _REPO_ROOT / args.out if not Path(args.out).is_absolute() else Path(args.out)
    targets = _SPORT_MANIFEST if resolved == "all" else [
        e for e in _SPORT_MANIFEST if e[0] == resolved
    ]
    if not targets:
        log.error("No manifest entry for %r.", resolved)
        return 1

    built: List[Tuple[str, str, int]] = []
    for sport_id, display_name, adapter_module, corpus_hint in targets:
        count = build_sport(sport_id, display_name, adapter_module, corpus_hint, out_dir)
        if count is not None:
            built.append((sport_id, display_name, count))

    hub_path = write_hub(out_dir, built)

    def _disp(p: Path) -> str:
        try:
            return str(p.relative_to(_REPO_ROOT))
        except ValueError:
            return str(p)

    print()
    print("=" * 60)
    print("Multi-sport atlas build complete")
    print(f"  Hub note : {_disp(hub_path)}")
    print(f"  Out dir  : {_disp(out_dir)}")
    print()
    for _, display_name, note_count in built:
        print(f"  {display_name:<20} {note_count:>4} note(s)")
    skipped_names = [
        dn for sid, dn, _, _ in targets
        if sid not in {s for s, _, _ in built}
    ]
    for dn in skipped_names:
        print(f"  {dn:<20}  --- skipped (module absent)")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
