import type { LabDataset } from "./labTypes";
import { field as f, labRows, snapshot, type SourceRow } from "./labHelpers";
export function establishedDatasets(): LabDataset[] {
  const output: LabDataset[] = [];
  const pitches = snapshot<{ pitch_type_distribution: SourceRow[]; velo_percentiles_by_pitch_type: SourceRow[] }>("statcast_showcase");
  const pitchFields = [f("p50", "Median velocity", "mph"), f("p10", "10th-percentile velocity", "mph"), f("p90", "90th-percentile velocity", "mph"), f("pct", "Pitch share (%)"), f("mix_n", "Pitch-mix observations", "number", 0), f("velocity_n", "Velocity observations", "number", 0)];
  const pitchRows = pitches.pitch_type_distribution.map(p => { const v = pitches.velo_percentiles_by_pitch_type.find(r => r.pitch_type === p.pitch_type); return { ...p, ...(v || {}), mix_n: p.n, velocity_n: v?.n ?? null }; });
  output.push({ id: "pitch-profiles", title: "Pitch mix and velocity profiles", sport: "mlb", category: "Pitch analysis", source: "statcast_showcase", description: "Compare pitch usage with the center and spread of measured velocity.", scope: "693,037 pitches from the published 2025 Statcast pull.", caveat: "Velocity and pitch-mix denominators differ when velocity is missing. Pitch-type rates are descriptive; they do not establish pitcher quality or prediction accuracy.", status: "Descriptive", fields: pitchFields, rows: labRows(pitchRows, pitchFields, "pitch_type") });
  const consistent = snapshot<{ most_consistent_top15: SourceRow[]; least_consistent_top15: SourceRow[] }>("nba_consistency_profiles");
  const consistencyFields = [f("composite_cv_shrunk", "Composite variability", "number", 4), f("pts_per36_mean", "Points / 36"), f("pts_cv_shrunk", "Points variability", "number", 4), f("reb_cv_shrunk", "Rebound variability", "number", 4), f("ast_cv_shrunk", "Assist variability", "number", 4), f("games", "Games", "number", 0)];
  output.push({ id: "nba-consistency", title: "Player consistency", sport: "nba", category: "Player & team", source: "nba_consistency_profiles", description: "Explore how much a player's per-36 production varies from game to game.", scope: "Published extremes from 579 eligible players; 2023-24 through 2025-26.", caveat: "These are the 15 lowest and 15 highest published variability profiles, not the complete player population. Lower variability is not higher skill. Small means can inflate CV.", status: "Descriptive", fields: consistencyFields, rows: [...labRows(consistent.most_consistent_top15, consistencyFields, "player_name", "Most consistent"), ...labRows(consistent.least_consistent_top15, consistencyFields, "player_name", "Least consistent")] });
  const lineup = snapshot<{ top: SourceRow[]; bottom: SourceRow[] }>("lineup_synergy");
  const lineupFields = [f("synergy_residual", "Synergy residual / 48"), f("net_per48", "Observed net / 48"), f("expected_net_per48", "Expected net / 48"), f("min", "Minutes"), f("n_games", "Games", "number", 0)];
  const lineupRows = (rows: SourceRow[]) => rows.map(r => ({ ...r, name: (r.members as string[]).map(n => n.split(" ").slice(-1)[0]).join(" / "), note: (r.members as string[]).join(", ") }));
  output.push({ id: "lineup-synergy", title: "Five-player lineup synergy", sport: "nba", category: "Player & team", source: "lineup_synergy", description: "Compare a lineup's observed net rating with its player-based expected rating.", scope: "Published top and bottom lineups from 102 qualifying units, 2024-25.", caveat: "Roughly 100-minute floor; one season and unadjusted opponents. Residuals describe association and include roster and selection effects.", status: "Descriptive", fields: lineupFields, rows: [...labRows(lineupRows(lineup.top), lineupFields, "name", "Top residuals"), ...labRows(lineupRows(lineup.bottom), lineupFields, "name", "Bottom residuals")] });
  const rim = snapshot<{ seasons: { season: string; leaders: SourceRow[]; n_qualified: number }[] }>("rim_deterrence");
  const rimFields = [f("delta", "On-minus-off rim share", "pp"), f("rim_share_allowed_on", "Opponent rim share: on", "percent"), f("rim_share_allowed_off", "Opponent rim share: off", "percent"), f("rim_efg_delta", "Rim eFG difference", "pp"), f("min_on", "On-court minutes")];
  output.push({ id: "rim-deterrence", title: "Who changes the shot profile?", sport: "nba", category: "Player & team", source: "rim_deterrence", description: "Inspect opponent rim-attempt shares with a defender on and off the floor.", scope: "Published season leaderboards; 500-minute on-court floor.", caveat: "Negative on-minus-off means fewer rim attempts. This is a selected leaderboard, with teammate, opponent and roster confounds; not an isolated defensive impact estimate.", status: "Descriptive", fields: rimFields, rows: rim.seasons.flatMap(s => labRows(s.leaders, rimFields, "player_name", s.season).map(row => ({ ...row, definition: { season: s.season } }))) });
  const home = snapshot<{ by_era: SourceRow[]; venue: Record<string, SourceRow> }>("soccer_home_advantage");
  const homeFields = [f("true_home_goal_diff", "True-home goal difference"), f("neutral_goal_diff", "Neutral-site goal difference"), f("effect_goal_diff", "Home-minus-neutral gap"), f("n_true_home", "True-home matches", "number", 0), f("n_neutral", "Neutral matches", "number", 0)];
  output.push({ id: "soccer-home-advantage", title: "Home advantage across eras", sport: "soccer", category: "Game context", source: "soccer_home_advantage", description: "Separate true-home matches from neutral-site matches before comparing eras.", scope: "49,425 international matches, 1872-11-30 to 2026-06-16.", caveat: "Neutral venues are not randomly assigned; team strength and tournament mix are uncontrolled. Travel effects are not testable from this source.", status: "Descriptive", fields: homeFields, rows: labRows(home.by_era, homeFields, "era") });
  const tennis = snapshot<{ combos: Record<string, { n_players_in_snapshot?: number; clay_hard_gap: { most_clay_favoring?: SourceRow[]; most_hard_favoring?: SourceRow[]; n_qualifying?: number; floor?: string; note?: string }; grass_adaptability: { most_adaptive?: SourceRow[]; least_adaptive?: SourceRow[]; n_qualifying?: number; floor?: string; note?: string } }> }>("tennis_surface_transfer");
  const clayFields = [f("clay_minus_hard", "Clay-minus-hard win rate", "pp"), f("clay_wr", "Clay win rate", "percent"), f("hard_wr", "Hard win rate", "percent"), f("clay_n", "Clay matches", "number", 0), f("hard_n", "Hard matches", "number", 0)];
  const grassFields = [f("grass_adapt", "Grass-minus-overall win rate", "pp"), f("grass_wr", "Grass win rate", "percent"), f("ov_wr", "Overall win rate", "percent"), f("grass_n", "Grass matches", "number", 0)];
  for (const [key, combo] of Object.entries(tennis.combos)) {
    const title = key.replace(/_/g, " ").replace(/atp/g, "ATP").replace(/wta/g, "WTA");
    for (const kind of ["clay", "grass"] as const) {
      const fields = kind === "clay" ? clayFields : grassFields;
      const c = combo.clay_hard_gap; const g = combo.grass_adaptability;
      const rows = kind === "clay" ? [...(c?.most_clay_favoring || []), ...(c?.most_hard_favoring || [])] : [...(g?.most_adaptive || []), ...(g?.least_adaptive || [])];
      const measure = kind === "clay" ? c : g;
      output.push({ id: `tennis-${key}-${kind}`, title: `${title}: ${kind === "clay" ? "clay vs. hard" : "grass adaptation"}`, sport: "tennis", category: "Surface analysis", source: "tennis_surface_transfer", description: "Compare published surface-rate extremes and the match counts behind them.", scope: `${title}; ${kind === "clay" ? "25 matches on each surface" : "15 grass matches"} minimum. Published extremes only.`, caveat: "Opponent strength and draws are uncontrolled. Career means the source's collected history. Empty WTA views indicate no published qualifiers, not a zero effect.", status: rows.length ? "Descriptive" : "No qualifying rows", fields, rows: labRows(rows, fields, "player_name", title), eligiblePopulation: combo.n_players_in_snapshot, qualificationRule: measure?.floor, nQualifying: measure?.n_qualifying, note: measure?.note });
    }
  }
  return output;
}
