import type { LabDataset } from "./labTypes";
import { field as f, labRows, snapshot, type SourceRow } from "./labHelpers";
const sportName = (s: unknown) => String(s).replace("soccer_intl", "International soccer").toUpperCase();
const observationWindow = (window: SourceRow | undefined) => window && typeof window.start === "string" && typeof window.end === "string"
  ? `${window.start} to ${window.end}${typeof window.days === "number" ? ` (${window.days} days)` : ""}` : undefined;
const presentCheckpoint = (value: unknown): value is string | number => value !== undefined && value !== null && value !== "";
const checkpointWindow = (checkpoints: SourceRow[]) => {
  const first = checkpoints[0]?.checkpoint;
  const last = checkpoints.at(-1)?.checkpoint;
  return presentCheckpoint(first) && presentCheckpoint(last) ? `Checkpoints ${first} to ${last}` : undefined;
};
export function novelDatasets(): LabDataset[] {
  const lhlFields = [f("half_life_hours", "Line half-life", "hours"), f("final_hour_movement_share", "Final-hour movement share", "percent"), f("n_move_pairs", "Observed move pairs", "number", 0)];
  const lhl = snapshot<{ results: SourceRow[] }>("novel_line_half_life");
  const lcfFields = [f("live_clock_fraction", "Live-clock fraction", "percent"), f("decided_frac_of_games", "Games decided by threshold", "percent"), f("n_games_total", "Games observed", "number", 0), f("n_games_decided", "Games decided", "number", 0)];
  const lcf = snapshot<{ results: SourceRow[] }>("novel_live_clock_fraction");
  const loadFields = [f("delta_winprob", "Estimator A probability difference", "pp"), f("delta_win_rate", "Estimator B win-rate difference", "pp"), f("n_active", "Games active (B)", "number", 0), f("n_missed", "Games missed (B)", "number", 0)];
  const load = snapshot<{ results: { team: string; estimator_a_elo_onoff: SourceRow; estimator_b_raw_withwithout: SourceRow; agreement_same_player: boolean }[] }>("novel_load_bearing_index");
  const loadRows = load.results.map(r => ({ team: r.team, ...r.estimator_a_elo_onoff, ...r.estimator_b_raw_withwithout, note: `Estimator A: ${r.estimator_a_elo_onoff.player_name}; estimator B: ${r.estimator_b_raw_withwithout.player_name}. Same player: ${r.agreement_same_player ? "yes" : "no"}.` }));
  const mfpFields = [f("mfp", "Market foresight premium", "number", 4), f("market_skill", "Market skill vs. naive", "number", 4), f("model_skill", "Model skill vs. naive", "number", 4), f("entropy_market_bits", "Market entropy (bits)", "number", 4), f("n", "Checkpoint observations", "number", 0)];
  const mfp = snapshot<{ results: Record<string, { checkpoints: SourceRow[] }> }>("novel_market_foresight_premium");
  const ohgFields = [f("ohg", "Overreaction harvest gap", "number", 4), f("overreaction_abs_mean", "Mean absolute overshoot", "number", 4), f("model_can_beat_model_closer_rate", "Model closer-to-outcome rate", "percent"), f("model_brier_at_max_disagree", "Model Brier at max disagreement", "number", 4), f("market_brier_at_max_disagree", "Market Brier at max disagreement", "number", 4), f("max_disagreement_n", "Max-disagreement observations", "number", 0)];
  const ohg = snapshot<{ results: SourceRow[] }>("novel_overreaction_harvest_gap");
  const fatigueFields = [f("sft_credible_pts_per100_ortg", "Schedule fatigue tax / 100 possessions", "number", 4), f("sft_descriptive_composite_per36", "Descriptive composite / 36", "number", 4), f("b2b_freq", "Back-to-back frequency", "percent"), f("b2b_games", "Back-to-back games", "number", 0)];
  const fatigue = snapshot<{ results: SourceRow[] }>("novel_schedule_fatigue_tax");
  return [
    { id: "line-half-life", title: "Line Half-Life", sport: "all", category: "Experimental metrics", source: "novel_line_half_life", description: "How many hours before start has half of the observed pre-game line motion occurred?", scope: "Short sport-specific capture windows in June-July 2026; 14-30 days, dense move-pair sampling.", caveat: "Absolute movement measures activity and churn, not net price travel. Tennis and WNBA are censored above 6 hours; their missing numeric half-lives are not zero. KBO and NPB had fewer than 20 pre-game move pairs, and the separate soccer feed was excluded for a timestamp-coverage artifact.", status: "Novel packaging", fields: lhlFields, rows: labRows(lhl.results.map(r => ({ ...r, name: sportName(r.sport), note: `Half-life label: ${r.half_life_label}${r.crossing_in_open_bucket ? " (censored)" : ""}. Window: ${JSON.stringify(r.observation_window)}.` })), lhlFields, "name", r => sportName(r.sport)).map((row, index) => ({ ...row, definition: { sport: sportName(lhl.results[index].sport), population: `${lhl.results[index].n_move_pairs} observed move pairs`, observationWindow: observationWindow(lhl.results[index].observation_window as SourceRow | undefined) } })) },
    { id: "live-clock", title: "Live-Clock Fraction", sport: "all", category: "Experimental metrics", source: "novel_live_clock_fraction", description: "How late does a game remain contested under the source's score-gap definition?", scope: "MLB: 178 games; international soccer: 29 games.", caveat: "Sport-specific score thresholds and clock units are not equivalent. This is not a universal cross-sport excitement score. NBA and tennis are not buildable in this artifact because no blowout corpus is available.", status: "Incremental metric", fields: lcfFields, rows: labRows(lcf.results.map(r => ({ ...r, name: sportName(r.sport), note: `Threshold: ${r.near_median_threshold} ${r.unit}. Clock: ${r.clock_field}.` })), lcfFields, "name", r => sportName(r.sport)).map((row, index) => ({ ...row, definition: { sport: sportName(lcf.results[index].sport), threshold: lcf.results[index].near_median_threshold as number, unit: String(lcf.results[index].unit), clockField: String(lcf.results[index].clock_field), population: `${lcf.results[index].n_games_total} games` } })) },
    { id: "load-bearing", title: "Load-Bearing Index", sport: "nba", category: "Experimental metrics", source: "novel_load_bearing_index", description: "Inspect two estimates of team dependence on a player, including where their leading players disagree.", scope: "30 teams. The two estimators name the same leading player for only 1 of 30 teams.", caveat: "The estimators use different seasons and may refer to different players. Roster, injury and rest confounds remain. This is not causal player impact.", status: "Incremental metric", fields: loadFields, rows: labRows(loadRows, loadFields, "team") },
    { id: "market-foresight", title: "Market Foresight Premium", sport: "all", category: "Experimental metrics", source: "novel_market_foresight_premium", description: "Track the market's skill advantage over this model, scaled by remaining market uncertainty.", scope: "Published in-game checkpoints, separated by sport.", caveat: "Model misspecification and news are confounded. Thin late-game cells remain visible. A larger value describes the market's advantage over this model, not an opportunity.", status: "Incremental metric", fields: mfpFields, rows: Object.entries(mfp.results).flatMap(([sport, result]) => {
      const window = checkpointWindow(result.checkpoints);
      return labRows(result.checkpoints.map(point => ({ ...point, label: `${sportName(sport)} / ${point.checkpoint}` })), mfpFields, "label", sportName(sport)).map(row => ({ ...row, definition: { sport: sportName(sport), observationWindow: window } }));
    }) },
    { id: "overreaction-gap", title: "Overreaction Harvest Gap", sport: "all", category: "Experimental metrics", source: "novel_overreaction_harvest_gap", description: "Examine why observed price overshoot did not improve the model comparison.", scope: "MLB and international soccer; selected disagreement buckets include small samples.", caveat: "An honest null: the reference is usually closer at maximum disagreement. This artifact records that result for the published buckets.", status: "Honest null", fields: ohgFields, rows: labRows(ohg.results.map(r => ({ ...r, name: sportName(r.sport), note: `Disagreement bucket: ${r.max_disagreement_bucket}. Market usually right: ${r.market_usually_right_at_max_disagree}.` })), ohgFields, "name", r => sportName(r.sport)) },
    { id: "schedule-fatigue", title: "Schedule Fatigue Tax", sport: "nba", category: "Experimental metrics", source: "novel_schedule_fatigue_tax", description: "Explore how schedule density weights the source's pooled back-to-back effect.", scope: "90 published team-seasons. Select a season before comparing teams.", caveat: "Raw pooled descriptive estimate. The -1.73 anchor is locally confirmed, not adjusted for roster, opponent, minutes or home advantage. This is not a game forecast.", status: "Descriptive composite", fields: fatigueFields, rows: Array.from(new Set(fatigue.results.map(r => String(r.season)))).flatMap(season => labRows(fatigue.results.filter(r => String(r.season) === season), fatigueFields, "team", season).map(row => ({ ...row, definition: { season } }))) },
  ];
}
