import type { LabDataset } from "./labTypes";
import { field as f, labRows, snapshot, type SourceRow } from "./labHelpers";
import { getLiveClockLabDataset } from "./labLiveClock";
import { getMarketForesightLabDataset } from "./labMarketForesight";
const sportName = (s: unknown) => String(s).replace("soccer_intl", "International soccer").toUpperCase();
const observationWindow = (window: SourceRow | undefined) => window && typeof window.start === "string" && typeof window.end === "string"
  ? `${window.start} to ${window.end}${typeof window.days === "number" ? ` (${window.days} days)` : ""}` : undefined;
export function novelDatasets(): LabDataset[] {
  const lhlFields = [f("half_life_hours", "Line half-life", "hours"), f("final_hour_movement_share", "Final-hour movement share", "percent"), f("n_move_pairs", "Observed move pairs", "number", 0)];
  const lhl = snapshot<{ results: SourceRow[] }>("novel_line_half_life");
  const loadFields = [f("delta_winprob", "Estimator A probability difference", "pp"), f("delta_win_rate", "Estimator B win-rate difference", "pp"), f("n_active", "Games active (B)", "number", 0), f("n_missed", "Games missed (B)", "number", 0)];
  const load = snapshot<{ as_of?: { estimator_a?: string; estimator_b?: string }; results: { team: string; estimator_a_elo_onoff: SourceRow; estimator_b_raw_withwithout: SourceRow; agreement_same_player: boolean }[] }>("novel_load_bearing_index");
  const loadPeriodA = typeof load.as_of?.estimator_a === "string" && load.as_of.estimator_a.trim() ? load.as_of.estimator_a : "not published";
  const loadPeriodB = typeof load.as_of?.estimator_b === "string" && load.as_of.estimator_b.trim() ? load.as_of.estimator_b : "not published";
  const loadRows = load.results.map(r => ({ team: r.team, ...r.estimator_a_elo_onoff, ...r.estimator_b_raw_withwithout, note: `Estimator A: ${r.estimator_a_elo_onoff.player_name}; estimator B: ${r.estimator_b_raw_withwithout.player_name}. Same player: ${r.agreement_same_player ? "yes" : "no"}.` }));
  const ohgFields = [f("ohg", "Overreaction harvest gap", "number", 4), f("overreaction_abs_mean", "Mean absolute overshoot", "number", 4), f("model_can_beat_model_closer_rate", "Model closer-to-outcome rate", "percent"), f("model_brier_at_max_disagree", "Model Brier at max disagreement", "number", 4), f("market_brier_at_max_disagree", "Market Brier at max disagreement", "number", 4), f("max_disagreement_n", "Max-disagreement observations", "number", 0)];
  const ohg = snapshot<{ results: SourceRow[] }>("novel_overreaction_harvest_gap");
  const fatigueFields = [f("b2b_freq", "Back-to-back frequency", "percent"), f("b2b_games", "Back-to-back games", "number", 0), f("sft_descriptive_composite_per36", "Frequency-weighted composite / 36", "number", 4), f("sft_credible_pts_per100_ortg", "ORtg effect (under review)", "number", 4)];
  const fatigue = snapshot<{ results: SourceRow[] }>("novel_schedule_fatigue_tax");
  return [
    { id: "line-half-life", title: "Line Half-Life", sport: "all", category: "Experimental metrics", source: "novel_line_half_life", description: "How many hours before start has half of the observed pre-game line motion occurred?", scope: "Short sport-specific capture windows in June-July 2026; 14-30 days, dense move-pair sampling.", caveat: "Absolute movement measures activity and churn, not net price travel. Tennis and WNBA are censored above 6 hours; their missing numeric half-lives are not zero. KBO and NPB had fewer than 20 pre-game move pairs, and the separate soccer feed was excluded for a timestamp-coverage artifact.", status: "Novel packaging", fields: lhlFields, rows: labRows(lhl.results.map(r => ({ ...r, name: sportName(r.sport), note: `Half-life label: ${r.half_life_label}${r.crossing_in_open_bucket ? " (censored)" : ""}. Window: ${JSON.stringify(r.observation_window)}.` })), lhlFields, "name", r => sportName(r.sport)).map((row, index) => ({ ...row, definition: { sport: sportName(lhl.results[index].sport), population: `${lhl.results[index].n_move_pairs} observed move pairs`, observationWindow: observationWindow(lhl.results[index].observation_window as SourceRow | undefined) } })) },
    getLiveClockLabDataset(),
    { id: "load-bearing", title: "Load-Bearing Index", sport: "nba", category: "Experimental metrics", source: "novel_load_bearing_index", description: "Inspect two estimates of team dependence on a player, including where their leading players disagree.", scope: `30 teams. The two estimators name the same leading player for only 1 of 30 teams. Estimator A period: ${loadPeriodA}. Estimator B period: ${loadPeriodB}.`, caveat: "The estimators use different seasons and may refer to different players. Roster, injury and rest confounds remain. This is not causal player impact.", status: "Incremental metric", fields: loadFields, rows: labRows(loadRows, loadFields, "team") },
    getMarketForesightLabDataset(),
    { id: "overreaction-gap", title: "Overreaction Harvest Gap", sport: "all", category: "Experimental metrics", source: "novel_overreaction_harvest_gap", description: "Examine why observed price overshoot did not improve the model comparison.", scope: "MLB and international soccer; selected disagreement buckets include small samples.", caveat: "An honest null: the reference is usually closer at maximum disagreement. This artifact records that result for the published buckets.", status: "Honest null", fields: ohgFields, rows: labRows(ohg.results.map(r => ({ ...r, name: sportName(r.sport), note: `Disagreement bucket: ${r.max_disagreement_bucket}. Market usually right: ${r.market_usually_right_at_max_disagree}.` })), ohgFields, "name", r => sportName(r.sport)) },
    { id: "schedule-fatigue", title: "Back-to-back schedule frequency", sport: "nba", category: "Experimental metrics", source: "novel_schedule_fatigue_tax", description: "Compare published back-to-back counts, frequencies, and the separate raw descriptive composite by team-season.", scope: "90 published team-seasons. Select a season before comparing teams.", caveat: "The source's ORtg tax is under review: its claimed anchor is a scoring-margin contrast, not an ORtg measurement. The raw per-36 composite remains descriptive and is not a causal effect or game forecast.", status: "Under review", fields: fatigueFields, rows: Array.from(new Set(fatigue.results.map(r => String(r.season)))).flatMap(season => labRows(fatigue.results.filter(r => String(r.season) === season).map(r => ({ ...r, sft_credible_pts_per100_ortg: null })), fatigueFields, "team", season).map(row => ({ ...row, definition: { season } }))) },
  ];
}
