// Per-findings social share cards. Each findings route has its own 1200x630 card
// (webapp/public/brand/og-finding-<slug>.png, generated by
// scripts/platformkit/analytics_showcase/make_og_card.py) carrying that finding's
// headline, so a shared link renders a distinct, compelling embed instead of the
// generic default. Spread the result into a page's `metadata`:
//
//   export const metadata: Metadata = { title, description, ...findingMeta("reliability") };
//
// openGraph.images overrides the layout's default card; twitter.images likewise.
// The twitter card TYPE (summary_large_image) is inherited from the layout.
const BASE = process.env.NEXT_PUBLIC_BASE_PATH || "";

export function findingMeta(slug: string) {
  const img = `${BASE}/brand/og-finding-${slug}.png`;
  return {
    openGraph: { images: [{ url: img, width: 1200, height: 630, alt: "CourtVision Analytics finding" }] },
    twitter: { images: [img] },
  };
}
