import { field as f, labRows, snapshot, type SourceRow } from "./labHelpers";
import type { ResearchAnalysis } from "./researchTypes";
import { outcomeBalance, safeDivide, supportRate, velocityShape } from "./researchMultisportHelpers";

const MLB = [{ title: "MLB Statcast glossary", url: "https://www.mlb.com/glossary/statcast" }, { title: "MLB velocity definition", url: "https://www.mlb.com/glossary/statcast/velocity" }];
const ITF = [{ title: "ITF classified tennis surfaces", url: "https://www.itftennis.com/en/about-us/tennis-tech/classified-surfaces/" }];
const IFAB = [{ title: "IFAB Law 10: outcome of a match", url: "https://www.theifab.com/laws/latest/determining-the-outcome-of-a-match/" }];
type Velo = { pitch_type: string; n: number; p10: number; p50: number; p90: number };
type Mix = { pitch_type: string; n: number; pct: number };
type CountRow = { balls: number; strikes: number; n: number; top_pitch_type: string; top_pitch_pct: number; strike_rate_type_S: number; in_zone_rate: number };
type SurfaceDist = { n: number; mean: number; std: number; p10: number; p50: number; p90: number; share_positive: number };
type SurfaceCombo = { n_players_in_snapshot: number; clay_hard_gap: { n_qualifying: number; distribution: SurfaceDist | null }; grass_adaptability: { n_qualifying: number; distribution: SurfaceDist | null } };

function mlbAnalyses(): ResearchAnalysis[] {
  const statcast = snapshot<{ n_pitches: number; pitch_type_distribution: Mix[]; velo_percentiles_by_pitch_type: Velo[] }>("statcast_showcase");
  const counts = snapshot<{ as_of: string; by_exact_count: CountRow[] }>("mlb_count_leverage");
  const shape = statcast.velo_percentiles_by_pitch_type.map(r => ({ ...r, ...velocityShape(r), label: r.pitch_type, note: `p10 ${r.p10}, p50 ${r.p50}, p90 ${r.p90} mph; n=${r.n}.` }));
  const mix = statcast.pitch_type_distribution.map(r => ({ ...r, share: r.pct / 100, squared_share: (r.pct / 100) ** 2, label: r.pitch_type }));
  const countRows = counts.by_exact_count.map(r => ({ ...r, label: `${r.balls}-${r.strikes}`, top_pitch_share: r.top_pitch_pct / 100, strike_zone_gap: r.strike_rate_type_S - r.in_zone_rate, note: `Top pitch: ${r.top_pitch_type}; n=${r.n}. S includes called, swinging, and foul strikes.` }));
  return [
    { id: "mlb-velocity-shape", title: "Pitch Velocity Shape", sport: "mlb", category: "Pitch matchup context", source: "statcast_showcase", description: "Compares the middle 80% velocity span and whether that span extends farther above or below the median for each pitch type.", scope: `Local 2025 Statcast pull; ${statcast.n_pitches.toLocaleString("en-US")} pitches, with each type's published non-null n shown.`, caveat: "League-level pitch-type distributions mix pitchers, parks, roles, and dates. Percentile shape is descriptive and is not a pitcher matchup forecast.", status: "Descriptive", fields: [f("p10", "10th percentile", "mph"), f("p50", "Median", "mph"), f("p90", "90th percentile", "mph"), f("spread", "P90-P10 span", "mph"), f("asymmetry", "Tail asymmetry", "mph"), f("upperShare", "Upper-tail share", "percent")], rows: labRows(shape, [f("p10", "10th percentile", "mph"), f("p50", "Median", "mph"), f("p90", "90th percentile", "mph"), f("spread", "P90-P10 span", "mph"), f("asymmetry", "Tail asymmetry", "mph"), f("upperShare", "Upper-tail share", "percent")], "label", "2025 pitch types"), formula: "spread = p90 - p10; asymmetry = (p90 - p50) - (p50 - p10); upper-tail share = (p90 - p50) / spread", interpretation: "A positive asymmetry means the observed central velocity range stretches farther above its median; compare pitch types only within this league snapshot.", references: MLB, novelty: "Derived analysis" },
    { id: "mlb-pitch-mix-concentration", title: "Pitch Mix Concentration", sport: "mlb", category: "Pitch matchup context", source: "statcast_showcase", description: "Shows each pitch type's contribution to a Herfindahl concentration summary of the league pitch mix.", scope: `All ${statcast.pitch_type_distribution.length} published pitch-type rows from the local 2025 Statcast pull.`, caveat: "The distribution includes unknown classifications and describes the league aggregate, not any individual pitcher. Shares published as percentages are converted to fractions before squaring.", status: "Descriptive", fields: [f("share", "Pitch share", "percent"), f("squared_share", "HHI contribution", "number", 4), f("n", "Pitches", "number", 0)], rows: labRows(mix, [f("share", "Pitch share", "percent"), f("squared_share", "HHI contribution", "number", 4), f("n", "Pitches", "number", 0)], "label", `HHI=${mix.reduce((s, r) => s + r.squared_share, 0).toFixed(4)}`), formula: "pitch share = published pct / 100; HHI = sum(pitch share^2); row contribution = pitch share^2", interpretation: "Larger contributions identify which pitch types make the aggregate repertoire less diverse; the group label reports the sum across published types.", references: MLB, novelty: "Derived analysis" },
    { id: "mlb-count-contrast", title: "Count Strike-Zone Contrast", sport: "mlb", category: "Count matchup context", source: "mlb_count_leverage", description: "Contrasts the source's broad strike-event share with its in-zone share for every exact ball-strike count.", scope: "Twelve legal pre-pitch counts in the local 2025 Statcast pull; each row retains its published raw count n.", caveat: "The S event includes called strikes, swinging strikes, and fouls, so the gap is not chase rate. S-event and in-zone rates use separate non-null denominators (n_type and n_zone), which are not exposed in these rows; the difference is therefore a descriptive proxy. Top-pitch share uses the count's classified-pitch denominator.", status: "Descriptive proxy", fields: [f("strike_rate_type_S", "S-event rate", "percent"), f("in_zone_rate", "In-zone rate", "percent"), f("strike_zone_gap", "S minus zone", "pp"), f("top_pitch_share", "Top-pitch share", "percent"), f("n", "Pitches", "number", 0)], rows: labRows(countRows, [f("strike_rate_type_S", "S-event rate", "percent"), f("in_zone_rate", "In-zone rate", "percent"), f("strike_zone_gap", "S minus zone", "pp"), f("top_pitch_share", "Top-pitch share", "percent"), f("n", "Pitches", "number", 0)], "label", "Exact count"), formula: "descriptive gap = separately denominated strike_rate_type_S - in_zone_rate; top-pitch share = top_pitch_pct / 100", interpretation: "Positive values mean the separately denominated S-event rate is numerically larger than the in-zone rate in that count; it is a broad outcome-zone proxy rather than a same-base event difference or swing-decision metric.", references: MLB, asOf: counts.as_of, novelty: "Derived analysis" },
  ];
}

function tennisAnalyses(): ResearchAnalysis[] {
  const data = snapshot<{ combos: Record<string, SurfaceCombo> }>("tennis_surface_transfer");
  const combos = Object.entries(data.combos).map(([key, c]) => ({ key, label: key.replace(/_/g, " ").toUpperCase(), snapshot_n: c.n_players_in_snapshot, clay_n: c.clay_hard_gap.n_qualifying, grass_n: c.grass_adaptability.n_qualifying, clay_support: supportRate(c.clay_hard_gap.n_qualifying, c.n_players_in_snapshot), grass_support: supportRate(c.grass_adaptability.n_qualifying, c.n_players_in_snapshot), clay: c.clay_hard_gap.distribution, grass: c.grass_adaptability.distribution }));
  const shared = { sport: "tennis" as const, category: "Surface matchup context", source: "tennis_surface_transfer", status: "Descriptive", references: ITF, novelty: "Derived analysis" as const };
  return [
    { ...shared, id: "tennis-surface-support", title: "Surface Evidence Support", description: "Measures how much of each tour-window snapshot survives the source's minimum-match floors for clay-hard and grass comparisons.", scope: "ATP/WTA career and recent-form snapshots; clay-hard requires at least 25 matches on each surface and grass requires at least 15 grass matches.", caveat: "A zero qualifying count is retained as zero; the derived support rate is zero when the snapshot denominator is positive. Coverage differences can reflect source depth rather than player characteristics.", fields: [f("clay_support", "Clay-hard support", "percent"), f("grass_support", "Grass support", "percent"), f("clay_n", "Clay-hard qualifiers", "number", 0), f("grass_n", "Grass qualifiers", "number", 0), f("snapshot_n", "Snapshot players", "number", 0)], rows: labRows(combos, [f("clay_support", "Clay-hard support", "percent"), f("grass_support", "Grass support", "percent"), f("clay_n", "Clay-hard qualifiers", "number", 0), f("grass_n", "Grass qualifiers", "number", 0), f("snapshot_n", "Snapshot players", "number", 0)], "label", "Published cohorts"), formula: "support rate = n qualifying at the source floor / n players in snapshot", interpretation: "Use this before comparing surface effects: low support means few players have enough matches for that surface contrast.", },
    { ...shared, id: "tennis-surface-spread", title: "Surface Specialization Spread", description: "Compares the central 80% width and standard deviation of qualifying players' clay-minus-hard and grass-minus-overall win-rate differences.", scope: "Published distribution summaries for four tour-window cohorts; WTA rows remain present with null metrics because no player cleared either floor.", caveat: "These are distributions of historical player rates with unequal match counts, not paired predictions. Null means no qualifying distribution; it is not zero variation.", fields: [f("clay_width", "Clay-hard P90-P10", "pp"), f("clay_std", "Clay-hard SD", "pp"), f("grass_width", "Grass P90-P10", "pp"), f("grass_std", "Grass SD", "pp")], rows: labRows(combos.map(c => ({ ...c, clay_width: c.clay ? c.clay.p90 - c.clay.p10 : null, clay_std: c.clay?.std ?? null, grass_width: c.grass ? c.grass.p90 - c.grass.p10 : null, grass_std: c.grass?.std ?? null })), [f("clay_width", "Clay-hard P90-P10", "pp"), f("clay_std", "Clay-hard SD", "pp"), f("grass_width", "Grass P90-P10", "pp"), f("grass_std", "Grass SD", "pp")], "label", "Published cohorts"), formula: "central width = p90(surface win-rate difference) - p10(surface win-rate difference); SD = published cohort standard deviation", interpretation: "Wider distributions indicate more separation among qualifying players' historical surface profiles in that cohort.", },
    { ...shared, id: "tennis-surface-balance", title: "Surface Lean Balance", description: "Shows how frequently qualifying players have positive clay-hard or grass-overall differences and how far that share sits from an even split.", scope: "Only cohorts with a published qualifying distribution contribute numeric rates; all four cohort rows remain visible.", caveat: "Positive-share balance counts players, not matches, and does not measure the magnitude or persistence of a player's surface difference.", fields: [f("clay_positive", "Clay-positive players", "percent"), f("clay_balance", "Clay share minus 50%", "pp"), f("grass_positive", "Grass-positive players", "percent"), f("grass_balance", "Grass share minus 50%", "pp")], rows: labRows(combos.map(c => ({ ...c, clay_positive: c.clay?.share_positive ?? null, clay_balance: c.clay ? c.clay.share_positive - 0.5 : null, grass_positive: c.grass?.share_positive ?? null, grass_balance: c.grass ? c.grass.share_positive - 0.5 : null })), [f("clay_positive", "Clay-positive players", "percent"), f("clay_balance", "Clay share minus 50%", "pp"), f("grass_positive", "Grass-positive players", "percent"), f("grass_balance", "Grass share minus 50%", "pp")], "label", "Published cohorts"), formula: "positive share = published qualifying-player fraction above zero; balance = positive share - 0.5", interpretation: "A positive balance means surface-positive profiles outnumber surface-negative profiles among players who clear the stated floor.", },
  ];
}

function soccerAnalyses(): ResearchAnalysis[] {
  const home = snapshot<{ generated_at: string; observation_window: { first_date: string; last_date: string; n_matches_played: number }; venue: Record<string, SourceRow>; by_tournament_type: SourceRow[] }>("soccer_home_advantage");
  const form = snapshot<{ generated_at: string; concordance: { n_overlap: number; points: { team: string; form: number; strength: number }[] } }>("soccer_form_stability");
  const venue = Object.entries(home.venue).map(([label, row]) => ({ ...row, ...outcomeBalance(row), label: label.replace(/_/g, " ") }));
  const tournaments = home.by_tournament_type.map(r => ({ ...r, label: String(r.bucket), true_home_share: safeDivide(r.true_home_n, r.n), neutral_share: safeDivide(r.neutral_n, r.n), support_ratio: safeDivide(r.true_home_n, r.neutral_n) }));
  const teams = form.concordance.points.map(r => ({ ...r, label: r.team, form_centered: r.form - 0.5, same_direction: r.form === 0.5 || r.strength === 0 ? null : Number((r.form - 0.5) * r.strength > 0), note: "same_direction is null when either lens is exactly neutral." }));
  return [
    { id: "soccer-venue-outcome-balance", title: "Venue Outcome Balance", sport: "soccer", category: "Venue matchup context", source: "soccer_home_advantage", description: "Separates decisive-match frequency and the home-away win-rate margin for true-home and neutral-site matches.", scope: `${home.observation_window.n_matches_played.toLocaleString("en-US")} international matches from ${home.observation_window.first_date} through ${home.observation_window.last_date}.`, caveat: "Venue assignment is not random and team strength, competition, era, and travel remain confounded. Rates describe selected historical populations and do not cause outcomes.", status: "Descriptive", fields: [f("home_win_rate", "Home win rate", "percent"), f("draw_rate", "Draw rate", "percent"), f("away_win_rate", "Away win rate", "percent"), f("decisiveRate", "Decisive rate", "percent"), f("homeAwayMargin", "Home-away margin", "pp"), f("n", "Matches", "number", 0)], rows: labRows(venue, [f("home_win_rate", "Home win rate", "percent"), f("draw_rate", "Draw rate", "percent"), f("away_win_rate", "Away win rate", "percent"), f("decisiveRate", "Decisive rate", "percent"), f("homeAwayMargin", "Home-away margin", "pp"), f("n", "Matches", "number", 0)], "label", "Venue flag"), formula: "decisive rate = 1 - draw rate; home-away margin = home win rate - away win rate", interpretation: "The pair distinguishes how often matches avoid draws from which listed side wins more often within each venue population.", references: IFAB, asOf: home.generated_at, novelty: "Derived analysis" },
    { id: "soccer-tournament-venue-support", title: "Tournament Venue Support", sport: "soccer", category: "Venue matchup context", source: "soccer_home_advantage", description: "Quantifies the true-home versus neutral-site composition behind each tournament-type venue comparison.", scope: "Three published tournament buckets from the same international-results corpus and observation window.", caveat: "The support ratio can be large when neutral matches are scarce; it describes sample composition, not a venue effect. Comparisons remain observational.", status: "Descriptive", fields: [f("true_home_share", "True-home share", "percent"), f("neutral_share", "Neutral share", "percent"), f("support_ratio", "True-home / neutral n", "number"), f("effect_goal_diff", "Goal-difference contrast", "number")], rows: labRows(tournaments, [f("true_home_share", "True-home share", "percent"), f("neutral_share", "Neutral share", "percent"), f("support_ratio", "True-home / neutral n", "number"), f("effect_goal_diff", "Goal-difference contrast", "number")], "label", "Tournament bucket"), formula: "true-home share = true_home_n / n; neutral share = neutral_n / n; support ratio = true_home_n / neutral_n", interpretation: "Read the sample balance beside the published goal-difference contrast before comparing tournament contexts.", references: IFAB, asOf: home.generated_at, novelty: "Derived analysis" },
    { id: "soccer-form-strength-alignment", title: "Cross-Source Form-Strength Direction", sport: "soccer", category: "Team matchup context", source: "soccer_form_stability", description: "Compares the sign of trailing-10 win rate relative to 50% with the sign of net-xG strength for each shared national team.", scope: `${form.concordance.n_overlap} teams above both source floors; form is trailing-10 as of each team's corpus endpoint, while strength is the 2026-06-28 snapshot.`, caveat: "The two lenses have unmatched as-of definitions, and team-specific form endpoint dates are not exposed. This is cross-source directional agreement, not a synchronized snapshot, temporal validation, or forecast. Trailing-10 form is coarse and heavily tied; exact-neutral cases remain null.", status: "Descriptive", fields: [f("form", "Trailing-10 win rate", "percent"), f("form_centered", "Form minus 50%", "pp"), f("strength", "Net-xG strength", "number"), f("same_direction", "Directional agreement", "number", 0)], rows: labRows(teams, [f("form", "Trailing-10 win rate", "percent"), f("form_centered", "Form minus 50%", "pp"), f("strength", "Net-xG strength", "number"), f("same_direction", "Directional agreement", "number", 0)], "label", "Shared teams"), formula: "form-centered = trailing-10 win rate - 0.5; agreement = 1 when form-centered and net-xG strength have the same non-zero sign, 0 when signs differ, null when either is zero", interpretation: "The flag records whether these unmatched cross-source lenses point in the same direction; inspect magnitudes and do not treat it as a ranking.", references: IFAB, asOf: form.generated_at, novelty: "Experimental formulation" },
  ];
}

export function multisportResearch(): ResearchAnalysis[] {
  return [...mlbAnalyses(), ...tennisAnalyses(), ...soccerAnalyses()];
}
