import type { LabField, LabRow } from "./labTypes";
import { field as f, snapshot, type SourceRow } from "./labHelpers";
import type { ResearchAnalysis, ResearchReference } from "./researchTypes";

const NBA: ResearchReference[] = [
  { title: "NBA Stats glossary", url: "https://www.nba.com/stats/help/glossary" },
  { title: "NBA statistical minimums", url: "https://www.nba.com/stats/help/statminimums" },
];
const n = (value: unknown): number | null => typeof value === "number" && Number.isFinite(value) ? value : null;
const calc = (values: Array<number | null>, fn: (...xs: number[]) => number): number | null => {
  if (!values.every(v => v !== null)) return null;
  const result = fn(...values as number[]);
  return Number.isFinite(result) ? result : null;
};
const row = (id: string, label: string, group: string, values: Record<string, number | null>, note?: string): LabRow => ({ id, label, group, values, note });
const analysis = (base: Omit<ResearchAnalysis, "sport" | "references" | "novelty">): ResearchAnalysis => ({
  ...base, sport: "nba", references: NBA, novelty: "Derived analysis",
});

export function basketballResearch(): ResearchAnalysis[] {
  const consistency = snapshot<{ as_of: string; most_consistent_top15: SourceRow[]; least_consistent_top15: SourceRow[] }>("nba_consistency_profiles");
  const consistencyFields = [f("cv_range", "Variability range", "number", 4), f("cv_max", "Highest stat CV", "number", 4), f("cv_min", "Lowest stat CV", "number", 4), f("pts_cv", "Points CV", "number", 4), f("reb_cv", "Rebound CV", "number", 4), f("ast_cv", "Assist CV", "number", 4), f("games", "Games", "number", 0)];
  const consistencyRows = [...consistency.most_consistent_top15, ...consistency.least_consistent_top15].map((r, i) => {
    const cvs = [n(r.pts_cv_shrunk), n(r.reb_cv_shrunk), n(r.ast_cv_shrunk)];
    const valid = cvs.filter((v): v is number => v !== null);
    const hi = valid.length === 3 ? Math.max(...valid) : null; const lo = valid.length === 3 ? Math.min(...valid) : null;
    return row(`consistency-${i}`, String(r.player_name), i < 15 ? "Published low-CV subset" : "Published high-CV subset", { cv_range: calc([hi, lo], (a, b) => a - b), cv_max: hi, cv_min: lo, pts_cv: cvs[0], reb_cv: cvs[1], ast_cv: cvs[2], games: n(r.games) });
  });

  const lineups = snapshot<{ season: string; n_qualified: number; top: SourceRow[]; bottom: SourceRow[] }>("lineup_synergy");
  const lineupFields = [f("reversal", "Expected/observed sign reversal", "number", 0), f("residual", "Observed minus expected / 48"), f("observed", "Observed net / 48"), f("expected", "Expected net / 48"), f("minutes", "Minutes"), f("games", "Games", "number", 0)];
  const lineupRows = [...lineups.top, ...lineups.bottom].map((r, i) => { const observed = n(r.net_per48); const expected = n(r.expected_net_per48); return row(`lineup-${i}`, (r.members as string[]).map(x => x.split(" ").at(-1)).join(" / "), i < lineups.top.length ? "Positive residuals" : "Negative residuals", { reversal: calc([observed, expected], (a, b) => Number(Math.sign(a) !== Math.sign(b))), residual: calc([observed, expected], (a, b) => a - b), observed, expected, minutes: n(r.min), games: n(r.n_games) }, (r.members as string[]).join(", ")); });

  const rim = snapshot<{ seasons: { season: string; n_qualified: number; leaders: SourceRow[] }[] }>("rim_deterrence");
  const rimFields = [f("two_axis_pressure", "Equal-weight rim index", "pp"), f("frequency_reduction", "Rim-frequency reduction", "pp"), f("efg_reduction", "Rim eFG reduction", "pp"), f("share_on", "Rim share on court", "percent"), f("share_off", "Rim share off court", "percent"), f("minutes", "Minutes")];
  const rimRows = rim.seasons.flatMap(s => s.leaders.map((r, i) => { const delta = n(r.delta); const efg = n(r.rim_efg_delta); return row(`${s.season}-${i}`, String(r.player_name), s.season, { two_axis_pressure: calc([delta, efg], (a, b) => (-a + -b) / 2), frequency_reduction: calc([delta], a => -a), efg_reduction: calc([efg], a => -a), share_on: n(r.rim_share_allowed_on), share_off: n(r.rim_share_allowed_off), minutes: n(r.min_on) }); }));

  const q4 = snapshot<{ observation_window: { n_games: number; seasons: string }; n_qualified: number; pts_shift: { top_risers: SourceRow[]; top_fallers: SourceRow[] }; reb_shift: { top_risers: SourceRow[] }; ast_shift: { top_risers: SourceRow[] } }>("nba_q4_shift");
  const q4Fields = [f("relative_shift", "Q4 relative shift", "percent"), f("shift", "Q4 minus Q1-Q3 / 36"), f("q4_rate", "Q4 rate / 36"), f("early_rate", "Q1-Q3 rate / 36"), f("q4_games", "Q4 appearances", "number", 0)];
  const q4Sets: [string, string, SourceRow[]][] = [["pts", "Scoring", [...q4.pts_shift.top_risers, ...q4.pts_shift.top_fallers]], ["reb", "Rebounding", q4.reb_shift.top_risers], ["ast", "Playmaking", q4.ast_shift.top_risers]];
  const q4Rows = q4Sets.flatMap(([key, group, rows]) => rows.map((r, i) => { const late = n(r[`q4_${key}_per36`]); const early = n(r[`q13_${key}_per36`]); return row(`${key}-${i}`, String(r.player_name), group, { relative_shift: calc([late, early], (a, b) => b === 0 ? NaN : (a - b) / Math.abs(b)), shift: calc([late, early], (a, b) => a - b), q4_rate: late, early_rate: early, q4_games: n(r.q4_games) }); }));

  const form = snapshot<{ methodology: { window_games: number }; input_coverage: { movers_eligible: number }; top_movers_risers: SourceRow[]; top_movers_fallers: SourceRow[] }>("nba_form_curves");
  const formFields = [f("relative_change", "Endpoint relative change", "percent"), f("delta", "Last minus first composite"), f("first", "First 10-game composite"), f("last", "Last 10-game composite"), f("last_percentile", "Last league percentile", "percent"), f("games", "Qualifying games", "number", 0)];
  const formRows = [...form.top_movers_risers, ...form.top_movers_fallers].map((r, i) => { const first = n(r.first_form); const last = n(r.last_form); return row(`form-${i}`, String(r.player_name), i < form.top_movers_risers.length ? "Published risers" : "Published fallers", { relative_change: calc([first, last], (a, b) => a === 0 ? NaN : (b - a) / Math.abs(a)), delta: calc([first, last], (a, b) => b - a), first, last, last_percentile: calc([n(r.last_form_league_pctile)], a => a / 100), games: n(r.n_qual_games) }, `${r.first_date} to ${r.last_date}`); });

  const schedule = snapshot<{ input_coverage: { team_seasons_reported: number }; per_team_season_frequencies: SourceRow[] }>("schedule_density");
  const scheduleFields = [f("compression", "Equal-weight compression index", "percent"), f("b2b", "Back-to-back frequency", "percent"), f("three_in_four", "3-in-4 frequency", "percent"), f("four_in_six", "4-in-6 frequency", "percent"), f("games", "Team games", "number", 0)];
  const scheduleRows = schedule.per_team_season_frequencies.map((r, i) => { const b2b = n(r.b2b_freq); const three = n(r.freq_3in4); const four = n(r.freq_4in6); return row(`schedule-${i}`, String(r.team), String(r.season), { compression: calc([b2b, three, four], (a, b, c) => (a + b + c) / 3), b2b, three_in_four: three, four_in_six: four, games: n(r.games) }); });

  const matchups = snapshot<{ input_coverage: { games_total: number; date_max: string }; mask: { min_meetings: number; pairings_kept: number }; pairings: SourceRow[] }>("nba_matchup_grid");
  const teamAtlas = snapshot<{ entries: { entity: string; key_numbers: { team_full_name: string } }[] }>("atlas_nba_teams_manifest");
  const teamNames = new Map(teamAtlas.entries.map(entry => [entry.entity, entry.key_numbers.team_full_name]));
  const uniquePairs = matchups.pairings.filter(r => String(r.row) < String(r.col));
  const totalMeetings = uniquePairs.reduce((sum, r) => sum + (n(r.n_meetings) ?? 0), 0);
  const leagueTotal = uniquePairs.reduce((sum, r) => sum + (n(r.mean_total) ?? 0) * (n(r.n_meetings) ?? 0), 0) / totalMeetings;
  const matchupFields = [f("total_vs_pool", "Total vs pooled matchup mean"), f("mean_total", "Mean combined points"), f("mean_margin", "Mean row-team margin"), f("absolute_margin", "Absolute mean margin"), f("meetings", "Meetings", "number", 0), f("pool_mean", "Pooled matchup mean")];
  const matchupRows = uniquePairs.map((r, i) => { const total = n(r.mean_total); const margin = n(r.mean_margin); const rowCode = String(r.row), colCode = String(r.col); const rowName = teamNames.get(rowCode), colName = teamNames.get(colCode); return row(`matchup-${i}`, `${rowCode} vs ${colCode}`, "Historical matchup profile", { total_vs_pool: calc([total, leagueTotal], (a, b) => a - b), mean_total: total, mean_margin: margin, absolute_margin: calc([margin], Math.abs), meetings: n(r.n_meetings), pool_mean: leagueTotal }, rowName && colName ? `${rowName} vs ${colName}` : undefined); });

  return [
    analysis({ id: "nba-variability-imbalance", title: "Which box-score role is least stable?", category: "Player profiles", source: "nba_consistency_profiles", description: "Separates a player's widest and narrowest shrunk variability dimensions instead of hiding them in one composite.", scope: "Published 15 lowest- and 15 highest-composite-CV players from 579 eligible players, 2023-24 through 2025-26.", caveat: "Selected extremes only. CV depends on the stat mean; variability is neither skill nor forecast uncertainty.", status: "Descriptive subset", fields: consistencyFields, rows: consistencyRows, formula: "CV range = max(points CV, rebounds CV, assists CV) - min(points CV, rebounds CV, assists CV).", interpretation: "A larger range flags players whose game-to-game steadiness differs sharply by box-score role.", asOf: consistency.as_of }),
    analysis({ id: "nba-lineup-expectation-reversals", title: "When does a lineup reverse its player baseline?", category: "Lineup support", source: "lineup_synergy", description: "Flags selected five-player units whose observed net result crosses zero relative to the player-based expectation.", scope: `23 published residual extremes among ${lineups.n_qualified} qualifying lineups in ${lineups.season}.`, caveat: "Selected extremes, about 100-minute minimum, one season, opponent-raw. Player on/off baselines and lineup outcomes are roster-confounded.", status: "Descriptive subset", fields: lineupFields, rows: lineupRows, formula: "Residual = observed net/48 - expected net/48; reversal = 1 when their signs differ, else 0.", interpretation: "A reversal highlights units where the direction of the observed result differs from the additive player baseline; it does not establish chemistry or causality." }),
    analysis({ id: "nba-rim-two-axis-pressure", title: "Rim deterrence versus rim finishing", category: "Defensive profiles", source: "rim_deterrence", description: "Shows whether lower opponent rim frequency coincides with lower opponent rim efficiency.", scope: "Published top-15 rim-frequency deterrence leaders in each of 2024-25 and 2025-26; 500 on-court-minute floor.", caveat: "Selected leaderboards and raw on/off associations. Teammates, schemes, opponents and shot quality are uncontrolled. The equal weights are a presentation choice, not a validated defensive scale.", status: "Experimental descriptive", fields: rimFields, rows: rimRows, formula: "Equal-weight rim index = ((off rim share - on rim share) + (off rim eFG - on rim eFG)) / 2.", interpretation: "Positive means the equally weighted average is positive; either component can offset the other, so inspect both component columns." }),
    analysis({ id: "nba-q4-role-redistribution", title: "How large is the fourth-quarter role shift?", category: "Game phase", source: "nba_q4_shift", description: "Scales published Q4 per-36 changes by each player's earlier-quarter rate so unlike box-score roles can be compared.", scope: `Published scoring risers/fallers and rebound/assist risers among ${q4.n_qualified} qualified players across ${q4.observation_window.n_games} cached games (${q4.observation_window.seasons}).`, caveat: "Selected extremes only. Per-36 rates do not control lineup, score state, opponent or garbage time; this is not clutch skill.", status: "Descriptive subset", fields: q4Fields, rows: q4Rows, formula: "Relative shift = (Q4 per-36 - Q1-Q3 per-36) / abs(Q1-Q3 per-36).", interpretation: "The fraction distinguishes a large raw change from a large change relative to the player's earlier scoring, rebounding or assist role." }),
    analysis({ id: "nba-form-endpoint-elasticity", title: "How large is endpoint form movement?", category: "Player trends", source: "nba_form_curves", description: "Expresses the difference between a player's first and last retained 10-game windows relative to the first window.", scope: `Published 15 largest risers and 15 largest fallers from ${form.input_coverage.movers_eligible} eligible movers, pooled 2023-24 through 2025-26.`, caveat: "Endpoint selection is sensitive to injuries, roles and schedule. Overlapping rolling windows are not independent and this is not a forecast.", status: "Descriptive subset", fields: formFields, rows: formRows, formula: "Relative endpoint change = (last 10-game composite - first 10-game composite) / abs(first composite).", interpretation: "This puts the raw composite movement in the context of the player's starting level while retaining both endpoints." }),
    analysis({ id: "nba-schedule-compression-profile", title: "Which schedules concentrate compressed stretches?", category: "Schedule context", source: "schedule_density", description: "Summarizes three overlapping schedule-compression frequencies with an equal-weight index.", scope: `${schedule.input_coverage.team_seasons_reported} published team-seasons, 2023-24 through 2025-26; team-season floor of 20 games.`, caveat: "The three classes overlap, so the index is not a share of distinct games. Equal weights are a presentation choice; the index measures schedule shape, not fatigue or performance effect.", status: "Experimental descriptive", fields: scheduleFields, rows: scheduleRows, formula: "Equal-weight compression index = (back-to-back frequency + 3-in-4 frequency + 4-in-6 frequency) / 3.", interpretation: "Higher values identify team-seasons with a larger equal-weight average across the three published congestion lenses." }),
    analysis({ id: "nba-matchup-profile-contrast", title: "Which historical matchups run high or close?", category: "Matchup explorer", source: "nba_matchup_grid", description: "Contrasts each unique team pairing's historical combined scoring with the meeting-weighted pool and keeps directional margin separate.", scope: `${uniquePairs.length} unique pairings from ${matchups.input_coverage.games_total} games, 2023-24 through ${matchups.input_coverage.date_max}; at least ${matchups.mask.min_meetings} meetings per pairing. Full-name search aliases come from atlas_nba_teams_manifest.`, caveat: "Raw historical means pool seasons and venues, and do not adjust rosters, opponent strength or recency. They are not forecasts.", status: "Descriptive", fields: matchupFields, rows: matchupRows, formula: "Total contrast = pairing mean total - meeting-weighted mean across unique pairings; closeness = abs(mean row-team margin).", interpretation: "Use total contrast and absolute margin as separate historical style lenses; the signed margin retains which alphabetically listed row team led on average.", asOf: matchups.input_coverage.date_max }),
  ];
}
