import type { Sport } from "./dashboardTypes";
import { field as f, snapshot } from "./labHelpers";
import type { LabField, LabRow } from "./labTypes";
import type { ResearchAnalysis, ResearchReference } from "./researchTypes";

type NumberMap = Record<string, number>;
type Bin = { n: number; n_games: number; mean_p: number; mean_y: number; gap_ci: [number, number] };
type Side = { brier: number; bins: Bin[] };
type Stability = { as_of: string; sports: Record<string, { n_rows: number; n_games: number; sides: Record<string, Side> }> };
const scoring: ResearchReference = { title: "Gneiting & Raftery (2007), Strictly Proper Scoring Rules, Prediction, and Estimation", url: "https://doi.org/10.1198/016214506000001437" };
const calibration: ResearchReference = { title: "Nixon et al. (2019), Measuring Calibration in Deep Learning", url: "https://openaccess.thecvf.com/content_CVPRW_2019/html/Nixon_Measuring_Calibration_in_Deep_Learning_CVPRW_2019_paper.html" };
const shannon: ResearchReference = { title: "Shannon (1948), A Mathematical Theory of Communication", url: "https://doi.org/10.1002/j.1538-7305.1948.tb00917.x" };
const rounded = (value: number): number => Number(value.toFixed(6));
const safeDivide = (a: number, b: number) => Number.isFinite(a) && Number.isFinite(b) && b !== 0 ? rounded(a / b) : null;
const sport = (key: string): Sport => key.startsWith("soccer") ? "soccer" : key.startsWith("basketball") ? "nba" : key as Sport;
const row = (id: string, label: string, group: string, values: Record<string, number | null>, note?: string): LabRow => ({ id, label, group, values, note });
const analysis = (base: Omit<ResearchAnalysis, "novelty">): ResearchAnalysis => ({ ...base, novelty: "Derived analysis" });
const weighted = (bins: Bin[], key: "mean_p" | "mean_y") => safeDivide(bins.reduce((s, b) => s + b.n * b[key], 0), bins.reduce((s, b) => s + b.n, 0));

export function validationResearch(): ResearchAnalysis[] {
  const output: ResearchAnalysis[] = [];
  const market = snapshot<{ market_types: Record<string, { scored: boolean; description: string; n_rows: number; model_brier?: number; market_brier?: number }> }>("calibration_by_market_type");
  const marketFields = [f("model_brier", "Model Brier", "number", 4), f("market_brier", "Market Brier", "number", 4), f("gap", "Model-minus-market Brier", "number", 4), f("relative_gap", "Gap / market Brier", "percent", 1), f("n_rows", "Scored rows", "number", 0)];
  const marketRows = Object.entries(market.market_types).filter(([, v]) => v.scored).map(([key, v]) => {
    const gap = typeof v.model_brier === "number" && typeof v.market_brier === "number" ? rounded(v.model_brier - v.market_brier) : null;
    return row(key, v.description, sport(key), { model_brier: v.model_brier ?? null, market_brier: v.market_brier ?? null, gap, relative_gap: gap === null ? null : safeDivide(gap, v.market_brier!), n_rows: v.n_rows });
  });
  output.push(analysis({ id: "brier-relative-gap", title: "Relative probability-score gap", sport: "all", category: "Calibration diagnostics", source: "calibration_by_market_type", description: "Compare each scored model Brier value with its same-corpus reference in absolute and relative terms.", scope: "Published labeled in-game corpora only; each row retains the two Brier operands and row count.", caveat: "Lower Brier is better. The relative gap is descriptive and inherits repeated within-game observations; it is not a significance test or independent OOS validation.", status: "Derived descriptive", fields: marketFields, rows: marketRows, formula: "gap = model Brier - reference Brier; relative gap = gap / reference Brier", interpretation: "Positive values mean larger squared probability error than the same-corpus reference.", references: [scoring] }));

  const stability = snapshot<Stability>("calibration_stability");
  const directionFields = [f("mean_p", "Row-weighted mean forecast", "percent"), f("mean_y", "Row-weighted observed rate", "percent"), f("signed_gap", "Observed-minus-forecast", "pp"), f("n_rows", "Rows", "number", 0), f("n_games", "Distinct games", "number", 0)];
  const directionRows: LabRow[] = [];
  for (const [sp, corpus] of Object.entries(stability.sports)) for (const [sideKey, side] of Object.entries(corpus.sides)) {
    const meanP = weighted(side.bins, "mean_p"), meanY = weighted(side.bins, "mean_y");
    directionRows.push(row(`${sp}-${sideKey}`, sideKey === "model_prob" ? "Model" : "Market", sport(sp), { mean_p: meanP, mean_y: meanY, signed_gap: meanP === null || meanY === null ? null : rounded(meanY - meanP), n_rows: corpus.n_rows, n_games: corpus.n_games }));
  }
  output.push(analysis({ id: "signed-calibration-direction", title: "Signed calibration direction", sport: "all", category: "Calibration diagnostics", source: "calibration_stability", description: "Restore the direction hidden by absolute calibration error by aggregating observed-minus-forecast gaps.", scope: "Ten published reliability bins per forecast source, weighted by bin row count.", caveat: "Repeated ticks share game outcomes, so row weighting describes this snapshot rather than independent evidence. Aggregation can also cancel opposing bin-level errors.", status: "Derived descriptive", fields: directionFields, rows: directionRows, formula: "signed gap = sum_b n_b(mean_y_b - mean_p_b) / sum_b n_b", interpretation: "Positive means observed outcomes were more frequent than forecast on average; negative means less frequent.", references: [calibration], asOf: stability.as_of }));

  const history = snapshot<Record<string, Record<string, { n: number; model_brier: number; market_brier: number; model_ece: number; market_ece: number }>>>("calibration_over_time");
  const shiftFields = [f("early_model_brier", "Earlier model Brier", "number", 4), f("late_model_brier", "Later model Brier", "number", 4), f("model_shift", "Model Brier shift", "number", 4), f("market_shift", "Market Brier shift", "number", 4), f("ece_shift", "Model ECE shift", "pp"), f("early_n", "Earlier rows", "number", 0), f("late_n", "Later rows", "number", 0)];
  const shiftRows = Object.entries(history).map(([sp, months]) => { const keys = Object.keys(months).sort(), a = months[keys[0]], b = months[keys.at(-1)!]; return row(sp, sp === "soccer_intl" ? "Soccer international" : sp.toUpperCase(), `${keys[0]} to ${keys.at(-1)}`, { early_model_brier: a.model_brier, late_model_brier: b.model_brier, model_shift: rounded(b.model_brier - a.model_brier), market_shift: rounded(b.market_brier - a.market_brier), ece_shift: rounded(b.model_ece - a.model_ece), early_n: a.n, late_n: b.n }); });
  output.push(analysis({ id: "observed-cohort-shift", title: "Observed monthly calibration shift", sport: "all", category: "Stability diagnostics", source: "calibration_over_time", description: "Measure how published Brier and calibration summaries changed between the first and last available month.", scope: "June-to-July 2026 snapshots for MLB and international soccer.", caveat: "Months are different observed cohorts with unequal support. The difference does not identify drift, causality, or future performance.", status: "Derived descriptive", fields: shiftFields, rows: shiftRows, formula: "shift = later-month metric - earlier-month metric", interpretation: "Positive score shifts indicate worse observed error in the later cohort; the support columns show the cohort-size change.", references: [scoring, calibration] }));

  const widthFields = [f("weighted_width", "Row-weighted CI width", "pp"), f("widest_width", "Widest bin CI", "pp"), f("min_games", "Fewest games in a bin", "number", 0), f("bins", "Eligible bins", "number", 0)];
  const widthRows: LabRow[] = [];
  const supportFields = [f("largest_bin_share", "Rows in largest bin", "percent"), f("sparse_row_share", "Rows in bins under 30 games", "percent"), f("sparse_rows", "Sparse-bin rows", "number", 0), f("n_rows", "Rows", "number", 0), f("n_games", "Distinct games", "number", 0)];
  const supportRows: LabRow[] = [];
  for (const [sp, corpus] of Object.entries(stability.sports)) for (const [sideKey, side] of Object.entries(corpus.sides)) {
    const total = side.bins.reduce((s, b) => s + b.n, 0), widths = side.bins.map(b => rounded(b.gap_ci[1] - b.gap_ci[0]));
    const sparseRows = side.bins.filter(b => b.n_games < 30).reduce((s, b) => s + b.n, 0);
    const label = sideKey === "model_prob" ? "Model" : "Market";
    widthRows.push(row(`${sp}-${sideKey}`, label, sport(sp), { weighted_width: safeDivide(side.bins.reduce((s, b, i) => s + b.n * widths[i], 0), total), widest_width: rounded(Math.max(...widths)), min_games: Math.min(...side.bins.map(b => b.n_games)), bins: side.bins.length }));
    supportRows.push(row(`${sp}-${sideKey}`, label, sport(sp), { largest_bin_share: safeDivide(Math.max(...side.bins.map(b => b.n)), total), sparse_row_share: safeDivide(sparseRows, total), sparse_rows: sparseRows, n_rows: total, n_games: corpus.n_games }));
  }
  output.push(analysis({ id: "cluster-interval-width", title: "Cluster-bootstrap uncertainty width", sport: "all", category: "Uncertainty diagnostics", source: "calibration_stability", description: "Summarize how wide the published game-cluster bootstrap intervals are across reliability bins.", scope: "Published 95% gap intervals from 1,000 game-level bootstrap resamples.", caveat: "The weighted width is a descriptive summary of bin intervals, not a pooled confidence interval. It must not be read as row-independent uncertainty.", status: "Derived descriptive", fields: widthFields, rows: widthRows, formula: "width_b = upper_b - lower_b; weighted width = sum_b n_b width_b / sum_b n_b", interpretation: "Wider values flag less precise reliability-bin estimates; minimum game support helps explain width.", references: [calibration], asOf: stability.as_of }));
  output.push(analysis({ id: "calibration-support-concentration", title: "Calibration support concentration", sport: "all", category: "Coverage diagnostics", source: "calibration_stability", description: "Show whether reliability summaries depend on one dense bin or on bins backed by fewer than 30 distinct games.", scope: "Published ten-bin reliability maps; sparse is transparently defined here as fewer than 30 distinct games.", caveat: "Thirty games is a descriptive review threshold, not a power guarantee. Row shares remain affected by repeated ticks within games.", status: "Experimental diagnostic", fields: supportFields, rows: supportRows, formula: "largest share = max_b(n_b)/sum_b n_b; sparse share = sum_{games_b<30} n_b/sum_b n_b", interpretation: "High concentration or sparse-bin share identifies regions where aggregate calibration summaries deserve closer bin-level inspection.", references: [calibration], asOf: stability.as_of }));

  const ledger = snapshot<{ as_of: string; summary: { n_families: number; by_status: NumberMap; by_status_per_sport: Record<string, NumberMap> } }>("fwd_claim_scoreboard");
  const entropyFields = [f("entropy_bits", "Verdict entropy", "number", 3), f("normalized_entropy", "Entropy / log2(5)", "percent", 1), f("largest_share", "Largest verdict share", "percent", 1), f("families", "Claim families", "number", 0)];
  const entropyRows = Object.entries(ledger.summary.by_status_per_sport).map(([sp, counts]) => { const n = Object.values(counts).reduce((a, b) => a + b, 0), h = rounded(-Object.values(counts).reduce((s, c) => c ? s + (c / n) * Math.log2(c / n) : s, 0)); return row(sp, sp.replace("basketball_nba", "NBA").toUpperCase(), sport(sp), { entropy_bits: h, normalized_entropy: safeDivide(h, Math.log2(5)), largest_share: safeDivide(Math.max(...Object.values(counts)), n), families: n }); });
  output.push(analysis({ id: "verdict-mix-entropy", title: "Verdict-mix diversity", sport: "all", category: "Research quality", source: "fwd_claim_scoreboard", description: "Quantify how concentrated each sport's current claim-family verdict mix is across five possible status classes.", scope: "Latest status per published claim family; normalized against five fixed classes: verified, provisional, null, not testable, and retracted.", caveat: "Entropy measures mix diversity, not research quality by itself. A high or low value is neither success nor failure and does not establish predictive validity.", status: "Experimental diagnostic", fields: entropyFields, rows: entropyRows, formula: "H = -sum_s p_s log2(p_s); normalized H = H/log2(5)", interpretation: "Higher values mean verdicts are spread more evenly across status classes; largest share exposes the dominant class.", references: [shannon], asOf: ledger.as_of }));

  const frictionFields = [f("not_testable_share", "Not-testable share", "percent", 1), f("retracted_share", "Retracted share", "percent", 1), f("not_testable", "Not testable", "number", 0), f("retracted", "Retracted", "number", 0), f("families", "Claim families", "number", 0)];
  const frictionRows = Object.entries(ledger.summary.by_status_per_sport).map(([sp, c]) => { const n = Object.values(c).reduce((a, b) => a + b, 0); return row(sp, sp.replace("basketball_nba", "NBA").toUpperCase(), sport(sp), { not_testable_share: safeDivide(c.not_testable ?? 0, n), retracted_share: safeDivide(c.retracted ?? 0, n), not_testable: c.not_testable ?? 0, retracted: c.retracted ?? 0, families: n }); });
  output.push(analysis({ id: "verdict-friction-share", title: "Untestable and retracted claim share", sport: "all", category: "Research quality", source: "fwd_claim_scoreboard", description: "Expose the share of claim families whose current status cannot be tested with available evidence or has been retracted.", scope: "Latest status per published claim family, split by sport.", caveat: "A zero is a recorded zero in the source status tally. This is workflow coverage, not evidence that the remaining claims are correct or independently replicated.", status: "Derived descriptive", fields: frictionFields, rows: frictionRows, formula: "status share = status-family count / all claim families in sport", interpretation: "Higher not-testable share identifies evidence-acquisition gaps; retracted share records corrected claims without erasing them.", references: [], asOf: ledger.as_of }));

  const qa = snapshot<{ generated_at: string; qa_regression_bank: { n_entries: number; n_pass: number }; coverage_stress: { n_expects_answer_true: number; n_expects_answer_true_ok: number } }>("qa_coverage_stats");
  const coverageFields: LabField[] = [f("covered", "Covered / passed", "number", 0), f("eligible", "Eligible", "number", 0), f("rate", "Observed rate", "percent", 1), f("gap", "Uncovered / failed", "number", 0)];
  const coverageRows = [row("stress", "Answerable stress prompts", "Coverage stress", { covered: qa.coverage_stress.n_expects_answer_true_ok, eligible: qa.coverage_stress.n_expects_answer_true, rate: safeDivide(qa.coverage_stress.n_expects_answer_true_ok, qa.coverage_stress.n_expects_answer_true), gap: qa.coverage_stress.n_expects_answer_true - qa.coverage_stress.n_expects_answer_true_ok }), row("regression", "Regression-bank checks", "Fail-closed QA", { covered: qa.qa_regression_bank.n_pass, eligible: qa.qa_regression_bank.n_entries, rate: safeDivide(qa.qa_regression_bank.n_pass, qa.qa_regression_bank.n_entries), gap: qa.qa_regression_bank.n_entries - qa.qa_regression_bank.n_pass })];
  output.push(analysis({ id: "answer-evidence-coverage", title: "Answer evidence coverage", sport: "all", category: "Coverage diagnostics", source: "qa_coverage_stats", description: "Keep the answerable-prompt coverage denominator beside the separate fail-closed regression-bank pass rate.", scope: "Published QA stress and regression-bank snapshots; each row uses its own explicitly eligible denominator.", caveat: "These rates answer different questions and must not be pooled. Regression passes include correct refusals; stress coverage includes only prompts marked as expecting an answer.", status: "Derived descriptive", fields: coverageFields, rows: coverageRows, formula: "rate = covered / eligible; gap = eligible - covered", interpretation: "The stress row measures available answer coverage; the regression row measures conformance to expected answer or refusal behavior.", references: [], asOf: qa.generated_at }));
  return output;
}
