import type { ResearchAnalysis } from "./researchTypes";
import { field as f, labRows, snapshot, type SourceRow } from "./labHelpers";
import { safeDivide } from "./researchMultisportHelpers";

const MLB = [{ title: "MLB Statcast velocity glossary", url: "https://www.mlb.com/glossary/statcast/velocity" }];
const SHRINKAGE = [{ title: "Efron (2014), Two Modeling Strategies for Empirical Bayes Estimation", url: "https://arxiv.org/abs/1409.2677" }];
const SCORING = [{ title: "Gneiting & Raftery (2007), Strictly Proper Scoring Rules", url: "https://doi.org/10.1198/016214506000001437" }];

const analysis = (base: Omit<ResearchAnalysis, "novelty">): ResearchAnalysis => ({ ...base, novelty: "Derived analysis" });

function mlbDepth(): ResearchAnalysis[] {
  const velo = snapshot<{ n_analyzed: number; velo_band_shares_by_pitch_type: Array<{ pitch_type: string; n: number; median_velo: number; band_share_pct: Record<string, number> }> }>("mlb_velo_bands");
  const shrinkage = snapshot<{ observation_window: { as_of: string; seasons: string }; groups: Array<{ label: string; biggest_regressors: Array<{ name: string; n: number; raw_rate: number; shrunk_rate: number; regression: number }> }> }>("mlb_shrinkage");
  const bands = velo.velo_band_shares_by_pitch_type.map(row => {
    const largest = Object.entries(row.band_share_pct).reduce((best, item) => item[1] > best[1] ? item : best, ["unavailable", 0]);
    const largestShare = largest[1] / 100;
    return { ...row, label: row.pitch_type, largest_band: largest[0], largest_share: largestShare, largest_band_pitch_estimate: row.n * largestShare, published_band_count: Object.keys(row.band_share_pct).length };
  });
  const regressors = shrinkage.groups.flatMap(group => group.biggest_regressors.map(row => {
    const regression = row.shrunk_rate - row.raw_rate;
    return { ...row, label: row.name, group: group.label, regression, absolute_regression: Math.abs(regression) };
  }));
  return [
    analysis({ id: "mlb-velocity-band-concentration", title: "Pitch Velocity Band Concentration", sport: "mlb", category: "Pitch context", source: "mlb_velo_bands", description: "Identifies the published velocity band holding the largest share of each pitch type's recorded pitches.", scope: `${velo.n_analyzed.toLocaleString("en-US")} analyzed pitches in the public velocity-band snapshot; each pitch type keeps its published pitch count.`, caveat: "Bands are fixed descriptive bins over a mixed league population. The estimated winning-band count uses rounded published shares and is not an exact event count, pitcher-level location, arsenal, or forecast.", status: "Descriptive", fields: [f("largest_share", "Largest band share", "percent"), f("largest_band_pitch_estimate", "Estimated pitches in largest band", "number", 0), f("published_band_count", "Published bands", "number", 0), f("n", "Pitches", "number", 0), f("median_velo", "Median velocity", "mph")], rows: labRows(bands, [f("largest_share", "Largest band share", "percent"), f("largest_band_pitch_estimate", "Estimated pitches in largest band", "number", 0), f("published_band_count", "Published bands", "number", 0), f("n", "Pitches", "number", 0), f("median_velo", "Median velocity", "mph")], "label", row => `Largest band: ${row.largest_band}`), formula: "largest band share = max over published band shares; estimated winning-band pitches = published pitch count * largest share", interpretation: "A larger share means more of this snapshot's pitches fell in one fixed velocity interval; inspect the interval, rounded-share estimate, all-band count, and pitch count together.", references: MLB }),
    analysis({ id: "mlb-shrinkage-displacement", title: "Published Shrinkage Displacement", sport: "mlb", category: "Rate support", source: "mlb_shrinkage", description: "Shows how far the published empirical-Bayes rate moves from the raw rate for the snapshot's listed largest regressors.", scope: `Fixed ${shrinkage.observation_window.seasons.replace("_", "-")} source slice; listed largest regressors from ${shrinkage.groups.length} public rate groups, not every eligible entity.`, caveat: "The source's selected regressors and prior are retained. Movement toward a pooled mean is a presentation of the published shrinkage, not proof that a raw rate is wrong or a future estimate.", status: "Descriptive subset", fields: [f("absolute_regression", "Absolute movement", "pp"), f("regression", "Shrunk minus raw", "pp"), f("raw_rate", "Raw rate", "percent"), f("shrunk_rate", "Shrunk rate", "percent"), f("n", "Source events", "number", 0)], rows: labRows(regressors, [f("absolute_regression", "Absolute movement", "pp"), f("regression", "Shrunk minus raw", "pp"), f("raw_rate", "Raw rate", "percent"), f("shrunk_rate", "Shrunk rate", "percent"), f("n", "Source events", "number", 0)], "label", row => String(row.group)), formula: "derived shift = shrunk rate - raw rate; absolute movement = abs(derived shift)", interpretation: "The sign shows whether the derived shrunk-minus-raw difference is upward or downward; the absolute value shows its size without discarding either rate.", references: SHRINKAGE, asOf: shrinkage.observation_window.as_of }),
  ];
}

function soccerDepth(): ResearchAnalysis[] {
  const soccer = snapshot<{ n_rows: number; minute_ece: { n: number; buckets: Array<{ minute_lo: number; minute_hi: number; n: number; mean_p: number; mean_y: number; ece: number }> } }>("soccer_calibration_pack");
  const rows = soccer.minute_ece.buckets.map(row => ({ ...row, label: `${row.minute_lo}-${row.minute_hi} minutes`, support_share: safeDivide(row.n, soccer.minute_ece.n), signed_gap: row.mean_y - row.mean_p }));
  return [analysis({ id: "soccer-minute-calibration-support", title: "Minute-Bucket Calibration Support", sport: "soccer", category: "Outcome calibration", source: "soccer_calibration_pack", description: "Places each published minute bucket's support beside its mean forecast-outcome gap and recorded calibration error.", scope: `${soccer.minute_ece.n.toLocaleString("en-US")} published rows across minute buckets from a ${soccer.n_rows.toLocaleString("en-US")}-row soccer snapshot.`, caveat: "Rows can be repeated observations within matches. These bucket summaries are recorded calibration diagnostics, not independent samples, a causal time effect, or a betting result.", status: "Descriptive", fields: [f("signed_gap", "Outcome minus forecast", "pp"), f("support_share", "Share of bucket rows", "percent"), f("mean_p", "Mean forecast", "percent"), f("mean_y", "Mean outcome", "percent"), f("ece", "Published absolute calibration error", "pp"), f("n", "Rows", "number", 0)], rows: labRows(rows, [f("signed_gap", "Outcome minus forecast", "pp"), f("support_share", "Share of bucket rows", "percent"), f("mean_p", "Mean forecast", "percent"), f("mean_y", "Mean outcome", "percent"), f("ece", "Published absolute calibration error", "pp"), f("n", "Rows", "number", 0)], "label", "Published minute buckets"), formula: "support share = bucket rows / all minute-bucket rows; signed gap = mean outcome - mean forecast", interpretation: "Use support to judge how much each bucket contributes to the snapshot; signed gap preserves direction while the source ECE remains an absolute-error summary.", references: SCORING })];
}

function tennisDepth(): ResearchAnalysis[] {
  const tennis = snapshot<{ ingame_surface_context: { tours: Record<string, { n_states_joined: number; pooled_brier_h0_blind: number; pooled_brier_h1_surface: number; pooled_delta_h1_minus_h0: number; n_folds: Array<{ n_test: number; brier_h0: number; brier_h1: number }> }> } }>("tennis_showcase");
  const rows: SourceRow[] = Object.entries(tennis.ingame_surface_context.tours).map(([tour, row]) => { const higherErrorFolds = row.n_folds.filter(fold => fold.brier_h1 > fold.brier_h0).length; return { label: tour.toUpperCase(), n: row.n_states_joined, blind_brier: row.pooled_brier_h0_blind, surface_brier: row.pooled_brier_h1_surface, delta: row.pooled_delta_h1_minus_h0, higher_error_folds: higherErrorFolds, n_folds: row.n_folds.length, fold_test_states: row.n_folds.reduce((sum, fold) => sum + fold.n_test, 0), fold_positive_share: safeDivide(higherErrorFolds, row.n_folds.length) }; });
  return [analysis({ id: "tennis-surface-prior-brier-delta", title: "Surface-Prior Brier Delta", sport: "tennis", category: "Surface evidence", source: "tennis_showcase", description: "Keeps the published surface-specific versus surface-blind Brier comparison and its fold direction count together for each tour.", scope: "Two tour rows from the public in-game surface-context receipt; each preserves its joined-state count and published folds.", caveat: "This is the source's rejected calibration comparison, not a player surface effect, match forecast, or market result. Brier differences are recorded for the stated held-out design only.", status: "Descriptive reject", fields: [f("delta", "Surface minus blind Brier", "number", 6), f("blind_brier", "Surface-blind Brier", "number", 6), f("surface_brier", "Surface-specific Brier", "number", 6), f("higher_error_folds", "Folds with higher surface Brier", "number", 0), f("n_folds", "Published folds", "number", 0), f("fold_test_states", "Fold test states", "number", 0), f("fold_positive_share", "Higher-error fold share", "percent"), f("n", "Joined states", "number", 0)], rows: labRows(rows, [f("delta", "Surface minus blind Brier", "number", 6), f("blind_brier", "Surface-blind Brier", "number", 6), f("surface_brier", "Surface-specific Brier", "number", 6), f("higher_error_folds", "Folds with higher surface Brier", "number", 0), f("n_folds", "Published folds", "number", 0), f("fold_test_states", "Fold test states", "number", 0), f("fold_positive_share", "Higher-error fold share", "percent"), f("n", "Joined states", "number", 0)], "label", "Published tours"), formula: "delta = pooled surface-specific Brier - pooled surface-blind Brier; fold share = higher-error folds / published folds", interpretation: "Positive delta and a high fold share mean the surface-specific variant had larger recorded squared probability error in this receipt; they do not establish a general surface effect.", references: SCORING })];
}

export function getMultisportDepthResearch(): ResearchAnalysis[] {
  return [...mlbDepth(), ...soccerDepth(), ...tennisDepth()];
}
