"""DATA module for system_map.py (spec-exempt from the 300-LOC cap, per
docs/PLATFORM.md conventions -- data-only, no logic). A CURATED, hand-reviewed
dataflow graph: nodes are writers/daemons/producers/stores/resolvers/webapp
routes; edges say who writes/reads/serves/registers what. This is a declared
map, not introspection -- every path here gets a disk-existence check at
build time in system_map.py; nothing here is trusted just because it's listed.

Node kinds: writer | daemon | producer | store | resolver | webapp | consumer
Edge relations: writes | reads | serves | registers
"""
from __future__ import annotations

NODES = [
    # -- ledger writers --------------------------------------------------
    {"id": "clv_ledger_writer", "kind": "writer",
     "path": "scripts/platformkit/clv_ledger.py",
     "description": "clv_ledger.record_bet -- appends every paper bet's CLV row"},
    {"id": "grade_predictions_writer", "kind": "writer",
     "path": "scripts/platformkit/paper/grade_predictions.py",
     "description": "grades pending pregame predictions once games settle"},
    {"id": "ingame_realized_clv_writer", "kind": "writer",
     "path": "scripts/platformkit/clv_grading/ingame_realized_clv.py",
     "description": "grades in-game bets against realized close, appends CLV rows"},
    # -- ledger artifacts (data/frontend, gitignored) --------------------
    {"id": "clv_ledger_jsonl", "kind": "store",
     "path": "data/frontend/clv_ledger.jsonl",
     "description": "append-only CLV ledger (pregame + in-game bets, claim_tags)"},
    {"id": "paper_predictions_graded_jsonl", "kind": "store",
     "path": "data/frontend/paper_predictions_graded.jsonl",
     "description": "settled paper predictions with grade + outcome"},
    {"id": "ingame_realized_clv_jsonl", "kind": "store",
     "path": "data/frontend/ingame_realized_clv.jsonl",
     "description": "realized in-game CLV per bet, close-anchored"},
    # -- claims engine chain ---------------------------------------------
    {"id": "card_registry", "kind": "producer",
     "path": "scripts/platformkit/claims/card_registry.py",
     "description": "declares the claim-card catalog (condition + family per card)"},
    {"id": "card_grader", "kind": "writer",
     "path": "scripts/platformkit/claims/card_grader.py",
     "description": "grades a card's condition against live data, appends to card_ledger"},
    {"id": "card_ledger_jsonl", "kind": "store",
     "path": "data/cache/claims/card_ledger.jsonl",
     "description": "append-only per-card grade history (n_fired, detail)"},
    {"id": "card_consumer", "kind": "resolver",
     "path": "scripts/platformkit/claims/card_consumer.py",
     "description": "reads latest card_ledger row per card_id for downstream consumers"},
    # -- analytics_verify producers --------------------------------------
    {"id": "attribution_producer", "kind": "producer",
     "path": "scripts/platformkit/analytics_verify/attribution.py",
     "description": "per-family/per-card CLV attribution rollup from the 3 ledgers + cards"},
    {"id": "regrader_producer", "kind": "producer",
     "path": "scripts/platformkit/analytics_verify/regrader.py",
     "description": "re-scores validated cards on post-validation CLV -> claim_survival.json"},
    {"id": "sentinel_producer", "kind": "producer",
     "path": "scripts/platformkit/analytics_verify/sentinel.py",
     "description": "independently re-derives served stats, flags DISCREPANT/STALE"},
    {"id": "contradiction_producer", "kind": "producer",
     "path": "scripts/platformkit/analytics_verify/contradiction.py",
     "description": "cross-claim consistency scan (SIGN/RANK/VALUE/STALE conflicts)"},
    {"id": "attribution_rollup_json", "kind": "store",
     "path": "data/cache/analytics_verify/attribution_rollup.json",
     "description": "attribution_producer's output artifact"},
    {"id": "claim_survival_json", "kind": "store",
     "path": "data/cache/analytics_verify/claim_survival.json",
     "description": "regrader_producer's output artifact"},
    {"id": "sentinel_report_json", "kind": "store",
     "path": "data/cache/analytics_verify/sentinel_report.json",
     "description": "sentinel_producer's output artifact"},
    {"id": "contradiction_report_json", "kind": "store",
     "path": "data/cache/analytics_verify/contradiction_report.json",
     "description": "contradiction_producer's output artifact"},
    # -- id bridge / cycle -------------------------------------------------
    {"id": "id_bridge", "kind": "producer",
     "path": "scripts/platformkit/analytics_verify/id_bridge.py",
     "description": "cross-store event_id/card_id linkage used by attribution's link_method_mix"},
    {"id": "analytics_cycle", "kind": "daemon",
     "path": "scripts/platformkit/analytics_verify/cycle.py",
     "description": "orchestrates attribution/regrader/sentinel/contradiction on a cadence"},
    # -- consumers: resolvers ---------------------------------------------
    {"id": "analytics_answers_resolver", "kind": "resolver",
     "path": "scripts/platformkit/analytics_verify/answers.py",
     "description": "fail-closed resolvers over the 4 analytics_verify artifacts (LANE E)"},
    {"id": "resolver_registry", "kind": "resolver",
     "path": "scripts/platformkit/answers/resolver_registry.py",
     "description": "top-level dispatch: classify(query) -> RESOLVERS[category]"},
    {"id": "system_map_resolver", "kind": "resolver",
     "path": "scripts/platformkit/analytics_verify/answers.py",
     "description": "system_map() resolver -- this module's own answer to 'how does the system work'"},
    {"id": "system_map_json", "kind": "store",
     "path": "data/cache/analytics_verify/system_map.json",
     "description": "this graph's own build artifact -- the thing system_map_resolver serves"},
    # -- other consumers ----------------------------------------------------
    {"id": "improvement_finder", "kind": "consumer",
     "path": "scripts/platformkit/meta/improvement_finder.py",
     "description": "reads analytics_verify + ledger artifacts to propose next fixes"},
    {"id": "bestbets_compute_runner", "kind": "producer",
     "path": "scripts/platformkit/bestbets/bestbets_compute_runner.py",
     "description": "m10 -- computes the best_bets digest served to the webapp"},
    {"id": "best_bets_json", "kind": "store",
     "path": "data/frontend/best_bets.json",
     "description": "m10 best_bets digest artifact"},
    {"id": "exec_evidence_daemon", "kind": "daemon",
     "path": "scripts/platformkit/evidence/exec_evidence_daemon.py",
     "description": "m44 -- hourly exec-evidence tick (CLV/gate/latency/prop-calibration)"},
    {"id": "exec_evidence_series_jsonl", "kind": "store",
     "path": "data/frontend/exec_evidence_series.jsonl",
     "description": "m44 append-only exec-evidence vintages"},
    # -- webapp routes --------------------------------------------------
    {"id": "webapp_paper_trading", "kind": "webapp",
     "path": "webapp/app/paper-trading/page.tsx",
     "description": "reads clv_ledger / graded predictions for the paper-trading view"},
    {"id": "webapp_p6", "kind": "webapp",
     "path": "webapp/app/p6/page.tsx",
     "description": "per-game claim-card detail view (card_consumer-backed)"},
    {"id": "webapp_progress", "kind": "webapp",
     "path": "webapp/app/progress/page.tsx",
     "description": "coverage + completeness + engine-readiness progress view"},
]

EDGES = [
    {"src": "clv_ledger_writer", "dst": "clv_ledger_jsonl", "relation": "writes"},
    {"src": "grade_predictions_writer", "dst": "paper_predictions_graded_jsonl", "relation": "writes"},
    {"src": "ingame_realized_clv_writer", "dst": "ingame_realized_clv_jsonl", "relation": "writes"},
    {"src": "card_registry", "dst": "card_grader", "relation": "serves"},
    {"src": "card_grader", "dst": "card_ledger_jsonl", "relation": "writes"},
    {"src": "card_consumer", "dst": "card_ledger_jsonl", "relation": "reads"},
    {"src": "attribution_producer", "dst": "clv_ledger_jsonl", "relation": "reads"},
    {"src": "attribution_producer", "dst": "paper_predictions_graded_jsonl", "relation": "reads"},
    {"src": "attribution_producer", "dst": "ingame_realized_clv_jsonl", "relation": "reads"},
    {"src": "attribution_producer", "dst": "card_ledger_jsonl", "relation": "reads"},
    {"src": "attribution_producer", "dst": "id_bridge", "relation": "reads"},
    {"src": "attribution_producer", "dst": "attribution_rollup_json", "relation": "writes"},
    {"src": "regrader_producer", "dst": "card_ledger_jsonl", "relation": "reads"},
    {"src": "regrader_producer", "dst": "claim_survival_json", "relation": "writes"},
    {"src": "sentinel_producer", "dst": "attribution_rollup_json", "relation": "reads"},
    {"src": "sentinel_producer", "dst": "sentinel_report_json", "relation": "writes"},
    {"src": "contradiction_producer", "dst": "card_ledger_jsonl", "relation": "reads"},
    {"src": "contradiction_producer", "dst": "contradiction_report_json", "relation": "writes"},
    {"src": "analytics_cycle", "dst": "attribution_producer", "relation": "registers"},
    {"src": "analytics_cycle", "dst": "regrader_producer", "relation": "registers"},
    {"src": "analytics_cycle", "dst": "sentinel_producer", "relation": "registers"},
    {"src": "analytics_cycle", "dst": "contradiction_producer", "relation": "registers"},
    {"src": "analytics_answers_resolver", "dst": "attribution_rollup_json", "relation": "reads"},
    {"src": "analytics_answers_resolver", "dst": "claim_survival_json", "relation": "reads"},
    {"src": "analytics_answers_resolver", "dst": "sentinel_report_json", "relation": "reads"},
    {"src": "analytics_answers_resolver", "dst": "contradiction_report_json", "relation": "reads"},
    {"src": "resolver_registry", "dst": "analytics_answers_resolver", "relation": "registers"},
    {"src": "resolver_registry", "dst": "system_map_resolver", "relation": "registers"},
    {"src": "system_map_resolver", "dst": "system_map_json", "relation": "reads"},
    {"src": "improvement_finder", "dst": "attribution_rollup_json", "relation": "reads"},
    {"src": "improvement_finder", "dst": "sentinel_report_json", "relation": "reads"},
    {"src": "bestbets_compute_runner", "dst": "best_bets_json", "relation": "writes"},
    {"src": "webapp_paper_trading", "dst": "clv_ledger_jsonl", "relation": "reads"},
    {"src": "webapp_p6", "dst": "card_ledger_jsonl", "relation": "reads"},
    {"src": "exec_evidence_daemon", "dst": "exec_evidence_series_jsonl", "relation": "writes"},
]
