// Analytics product (Product 2) OWN root layout -- DESIGN_ANALYTICS Sec. 13.
// A separate route-group root: it owns its <html>, fonts, theme-init, and tokens
// with zero CSS bleed from the terminal (globals.css is never imported here). URLs
// are unchanged; pages live at app/(analytics)/analytics/* -> /analytics/*.
import "./analytics.css";
import "./brand.css";
import "./analytics/measurement-position.css";

import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { analyticsFontVars } from "@/lib/analytics/fonts";
import { CommandPalette } from "@/components/analytics/CommandPalette";
import { PaletteTrigger } from "@/components/analytics/PaletteTrigger";
import { AnalyticsNavigation } from "@/components/analytics/AnalyticsNavigation";
import { BrandMark } from "@/components/analytics/BrandMark";

// Static-export builds serve at basePath /court-vision; next/font + <Link> auto-
// prefix, but the metadata icon URLs do NOT (same landmine as the terminal layout).
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || "";

// Social scrapers need ABSOLUTE og:image URLs. The public export is the GitHub Pages
// project site (neeljshah/court-vision -- see next.config.mjs); resolve card images
// against that origin, overridable with NEXT_PUBLIC_SITE_URL for any other host.
const SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_URL || "https://neeljshah.github.io";
const SITE_DESC =
  "Forecast calibration against published outcomes and devigged closing markets across basketball, baseball, soccer, and tennis. Every number links to its source artifact.";
// The social share card is a purpose-built 1200x630 image (brand/og-analytics.png,
// generated by scripts/platformkit/analytics_showcase/make_og_card.py). A landscape
// card at the 1.91:1 ratio is what summary_large_image expects, so the Twitter card
// below is back to large_image instead of the square-thumbnail summary fallback.
// BASE_PATH-prefixed so it resolves under /court-vision in the export.
const OG_IMAGE = `${BASE_PATH}/brand/og-analytics.png`;

// Pre-paint theme init: set data-theme from the analytics-scoped key before first
// paint so there is no flash of wrong theme. A stored analytics choice wins;
// otherwise follow the operating system preference. Independent of the terminal.
const THEME_INIT = `(function(){try{var t=localStorage.getItem('cv-analytics-theme');var d=t==='dark'||(t!=='light'&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.setAttribute('data-theme',d?'dark':'light');}catch(e){document.documentElement.setAttribute('data-theme',window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');}})();`;

// Post-hydration chrome: wire the theme toggle + mark the active nav pillar from the
// current path. Vanilla JS keeps the root layout a server component (no client file,
// no bundle) -- both are progressive enhancements over server-rendered links.
const CHROME_JS = `(function(){var r=document.documentElement;var b=document.getElementById('a-theme-toggle');if(b){b.addEventListener('click',function(){var n=r.getAttribute('data-theme')==='dark'?'light':'dark';r.setAttribute('data-theme',n);try{localStorage.setItem('cv-analytics-theme',n);}catch(e){}});}})();`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_ORIGIN),
  manifest: `${BASE_PATH}/manifest.webmanifest`,
  title: {
    template: "%s | CourtVision Analytics",
    default: "CourtVision Analytics",
  },
  description: SITE_DESC,
  icons: {
    icon: [
      { url: `${BASE_PATH}/brand/favicon.ico`, sizes: "any" },
      { url: `${BASE_PATH}/brand/favicon-32.png`, sizes: "32x32", type: "image/png" },
      { url: `${BASE_PATH}/brand/favicon-192.png`, sizes: "192x192", type: "image/png" },
      { url: `${BASE_PATH}/brand/favicon-512.png`, sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: `${BASE_PATH}/brand/apple-touch-icon.png` }],
  },
  openGraph: {
    type: "website",
    siteName: "CourtVision Analytics",
    title: "CourtVision Analytics",
    description: SITE_DESC,
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: "CourtVision Analytics -- inspect each result's source and method." }],
  },
  twitter: {
    // Purpose-built 1200x630 landscape card now exists (brand/og-analytics.png),
    // so this is back to the large image treatment instead of the square summary.
    card: "summary_large_image",
    title: "CourtVision Analytics",
    description: SITE_DESC,
    images: [OG_IMAGE],
  },
};

// Primary customer workflows. Specialist research pages remain in the footer.
const PILLARS: Array<{ href: string; label: string }> = [
  { href: "/analytics", label: "Overview" },
  { href: "/analytics/lab", label: "Measurement lab" },
  { href: "/analytics/compare", label: "Compare" },
  { href: "/analytics/browse", label: "Library" },
  { href: "/analytics/evidence", label: "Evidence" },
  { href: "/analytics/ask", label: "Ask Scout" },
];

// Footer secondary links -- keep About / Explainers / Retractions reachable from
// every page (they are not top-nav pillars but must not be orphaned URLs).
const FOOT_LINKS: Array<{ href: string; label: string }> = [
  { href: "/analytics/calibration", label: "Calibration" },
  { href: "/analytics/forecaster", label: "Forecaster" },
  { href: "/analytics/the-loop", label: "Research loop" },
  { href: "/analytics/novel", label: "Experimental metrics" },
  { href: "/analytics/pitch-sequencing", label: "Pitch sequencing" },
  { href: "/analytics/score-decomposition", label: "Score decomposition" },
  { href: "/analytics/players", label: "All entities" },
  { href: "/analytics/about", label: "About" },
  { href: "/analytics/explainers", label: "Explainers" },
  { href: "/analytics/findings", label: "Findings" },
  { href: "/analytics/observation-dependence", label: "Observation dependence" },
];

export default function AnalyticsRootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme="light" className={analyticsFontVars} suppressHydrationWarning>
      <head>
        {/* eslint-disable-next-line react/no-danger */}
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT }} />
      </head>
      <body>
        <a href="#analytics-main" className="a-skip">Skip to content</a>
        <nav className="a-nav" aria-label="Analytics">
          <div className="wrap a-navrow">
            <Link href="/analytics" className="a-lockup" aria-label="CourtVision Analytics home" prefetch={false}>
              <span className="a-mark"><BrandMark /></span>
              <span>
                <span className="a-name">CourtVision</span>{" "}
                <span className="a-kicker">ANALYTICS</span>
              </span>
            </Link>
            <AnalyticsNavigation links={PILLARS} />
            <PaletteTrigger />
            <button id="a-theme-toggle" className="a-theme" type="button" aria-label="Toggle light or dark theme">
              <svg className="sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">
                <circle cx="12" cy="12" r="4" />
                <path strokeLinecap="round" d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M19.1 4.9L17 7M7 17l-2.1 2.1" />
              </svg>
              <svg className="moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" d="M20 14.5A8 8 0 0 1 9.5 4a7 7 0 1 0 10.5 10.5z" />
              </svg>
            </button>
          </div>
        </nav>

        <main id="analytics-main">{children}</main>

        <footer className="a-footer">
          <div className="wrap">
            <div className="a-foot-top">
              <span className="a-foot-mark"><BrandMark /></span>
              <span className="a-foot-name">CourtVision Analytics</span>
            </div>
            <p className="a-honesty">
              <span className="k">Scope and sources</span>{" "}
              This reader publishes descriptive historical measurements of forecast calibration
              against outcomes and devigged closing markets. Every number links to the source
              artifact that produced it; the snapshot is dated and contains no live data.
            </p>
            <p className="a-meta">
              dated static snapshot &middot; published source artifacts &middot; no live data
            </p>
            {/* Primary onward nav from the foot of long pages: the mobile top nav
                is non-sticky by design (it scrolls away), so a reader at the bottom
                needs the six pillars here to jump on without scrolling back up. */}
            <nav className="a-foot-links a-foot-pillars" aria-label="Sections">
              {PILLARS.map((p) => (
                <Link key={p.href} href={p.href} prefetch={false}>
                  {p.label}
                </Link>
              ))}
            </nav>
            <nav className="a-foot-links" aria-label="Secondary">
              {FOOT_LINKS.map((l) => (
                <Link key={l.href} href={l.href} prefetch={false}>
                  {l.label}
                </Link>
              ))}
            </nav>
            {/* Cross-product jump: leaves the Reading Room for the dark quant
                terminal (own theme, full reload). The up-right glyph marks it as
                leaving this product, not in-product navigation. */}
            <Link href="/" className="a-xlink" target="_blank" rel="noopener">
              Looking for the live quant terminal? Open CourtVision Terminal &#8599;
            </Link>
          </div>
        </footer>

        {/* eslint-disable-next-line react/no-danger */}
        <script dangerouslySetInnerHTML={{ __html: CHROME_JS }} />
        <CommandPalette />
      </body>
    </html>
  );
}
