"""brain_activity.py -- LIVE-system activity hubs for the Obsidian brain.

Turns the read-only ``activity_sources.collect_activity`` snapshot into a small set
of BACKBONE hub notes that show WHAT THE AI IS DOING right now -- so opening the
graph view shows not just static concepts but the live layer:

  * ``_Organized/_Index/_Whats_Happening.md`` -- ONE master map of the live system:
    supervised services, what's predicting per sport, the calibration/CLV track
    record, the SHIP / HOLD / REJECT self-improvement ledger, what's paper-trading
    (pregame props + in-game), and the signal edge registry -- each linking DOWN to
    the detail (per-sport ``_Activity`` notes + the existing cross-sport hubs).
  * ``_Organized/<SPORT>/_Activity.md`` -- per-sport calibration + ship/reject +
    live-trading state (honest-empty where a sport has no live activity).

Both locations sit in the GRAPH BACKBONE scope (``_Index/`` and ``<SPORT>/_*``), so
they appear in the small default graph and link down -- the graph stays small.

PERSON-FREE (counts/sport-keys/verdicts/service-names only -- never a player, team,
or matchup), UNITS-ONLY (CLV is the yardstick; no $ and no edge claim), ASCII, and
honest-empty. Idempotent for a fixed snapshot (stamps come from the stores).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set

_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.platformkit.activity_sources import collect_activity  # noqa: E402

_BANNER = (
    "> **Live activity map** -- auto-generated by `scripts/platformkit/brain_activity.py` "
    "from the on-disk system stores. Intelligence map only; markets efficient; "
    "calibration is not edge. **Units only -- no dollars, no edge claimed.** An honest "
    "REJECT or empty section is a real result, not a gap."
)
_DISCLAIM = ("Intelligence MAP -- markets efficient; calibration, not a dollar edge; "
             "units only.")


def _n(x) -> str:
    return "n/a" if x is None else str(x)


def _pct(x) -> str:
    try:
        return f"{float(x):+.3f}%"
    except (TypeError, ValueError):
        return "n/a"


def _services_md(s: Dict) -> List[str]:
    if not s.get("present"):
        return ["## Services (supervised daemons)", "",
                "_No supervisor status on disk (stack not running)._", ""]
    out = ["## Services (supervised daemons)", "",
           f"- **Ready:** {s['n_ready']} / {s['n_total']}"
           f"  |  **Failed:** {s['n_failed']}  |  **all_ready:** {s['all_ready']}",
           f"- **Restarts (cumulative):** {s['restarts_total']}"
           f"  |  **Profile:** {_n(s.get('profile'))}  |  **as of** {_n(s.get('updated_at'))}",
           ""]
    not_ready = [p for p in s["procs"] if not p["ready"]]
    if not_ready:
        out.append("Not-ready services: " + ", ".join(f"{p['name']} ({p['state']})"
                                                       for p in not_ready))
    else:
        out.append("All supervised services report ready.")
    out += ["", "Service roster: " + ", ".join(p["name"] for p in s["procs"]), ""]
    return out


def _predict_md(p: Dict, keys: Optional[Set[str]] = None) -> List[str]:
    out = ["## What's predicting", ""]
    if not p.get("present"):
        return out + ["_No autonomy/loop status on disk._", ""]
    if keys is None:
        out += [f"- **Loop overall:** {_n(p.get('overall'))}"
                f"  |  **idle:** {_n(p.get('idle_reason'))}",
                f"- **Self-improve ratchet:** state {_n(p.get('ratchet_state'))}, "
                f"ships {_n(p.get('n_ships'))}",
                f"- **Live in-game now:** {p.get('n_live_now', 0)} game(s)"
                + (("  (" + ", ".join(f"{k}={v}" for k, v in sorted(
                    p.get('live_by_sport', {}).items())) + ")")
                   if p.get("live_by_sport") else ""), ""]
    items = p.get("per_sport", {})
    if keys is not None:
        items = {k: v for k, v in items.items() if k in keys}
    if items:
        out += ["| sport | last decision | games seen |",
                "|---|---|---|"]
        for sp, rec in sorted(items.items()):
            out.append(f"| {sp} | {_n(rec.get('last_decision'))} | {_n(rec.get('n_seen'))} |")
        out.append("")
    elif keys is not None:
        out += ["_No loop decisions recorded for this sport yet._", ""]
    return out


def _calib_md(c: Dict, keys: Optional[Set[str]] = None) -> List[str]:
    out = ["## Calibration / CLV track record", ""]
    if not c.get("present"):
        return out + ["_No graded settlements yet (CLV is the honest yardstick "
                      "once samples accrue)._", ""]
    if keys is None:
        out += [f"- **Settled:** {_n(c.get('n_settled'))}  |  **with true close (CLV):** "
                f"{_n(c.get('n_clv'))}  |  **proxy-close:** {_n(c.get('n_proxy_close'))}",
                f"- **Mean CLV:** {_pct(c.get('mean_clv_pct'))}  |  **beat close:** "
                f"{_n(c.get('pct_beat_close'))}%  |  **flat W-L:** "
                f"{_n(c.get('flat_unit_wins'))}-{_n(c.get('flat_unit_losses'))}",
                f"- _as of {_n(c.get('as_of'))}. CLV mean over true-close rows only; "
                "edge_claimed=false; UNPROVEN until replicated cross-corpus._", ""]
        return out
    rows = {sp: r for sp, r in (c.get("by_sport", {}) or {}).items() if sp in keys}
    if not rows:
        return out + ["_No settled CLV sample for this sport yet._", ""]
    out += ["| sport | settled | n_clv | mean CLV | beat close | flat W-L |",
            "|---|---|---|---|---|---|"]
    for sp, r in sorted(rows.items()):
        out.append(f"| {sp} | {_n(r.get('n_settled'))} | {_n(r.get('n_clv'))} | "
                   f"{_pct(r.get('mean_clv_pct'))} | {_n(r.get('pct_beat_close'))}% | "
                   f"{_n(r.get('flat_unit_wins'))}-{_n(r.get('flat_unit_losses'))} |")
    out += ["", "_CLV is the yardstick, not an edge; edge_claimed=false._", ""]
    return out


def _verdict_line(label: str, recs: Dict[str, dict], keys: Optional[Set[str]]) -> List[str]:
    items = recs if keys is None else {k: v for k, v in recs.items() if k in keys}
    if not items:
        return [f"- **{label}:** _none recorded yet._"]
    parts = [f"{sp}={_n(r.get('verdict'))} (n={_n(r.get('n_settled'))})"
             for sp, r in sorted(items.items())]
    return [f"- **{label}:** " + "  |  ".join(parts)]


def _improve_md(im: Dict, keys: Optional[Set[str]] = None) -> List[str]:
    out = ["## Self-improvement: SHIP / HOLD / REJECT", "",
           "Leak-free walk-forward recalibration gated by a planted-null do-no-harm "
           "check. An honest REJECT / INSUFFICIENT_DATA is the expected, correct result.",
           ""]
    out += _verdict_line("Game win-prob ratchet", im.get("game_winprob", {}), keys)
    out += _verdict_line("Prop calibration ratchet", im.get("props", {}), keys)
    meta = im.get("history_meta", {}) or {}
    groups = meta.get("groups", []) or []
    if keys is not None:
        groups = [g for g in groups if g.get("sport") in keys]
    if groups:
        out += ["", "Prop-history replication (>=2 independent folds to confirm):", "",
                "| sport | stat | folds | replicated verdict | med dBrier | null-leak |",
                "|---|---|---|---|---|---|"]
        for g in sorted(groups, key=lambda r: (str(r.get("sport")), str(r.get("stat")))):
            mdb = g.get("median_delta_brier")
            mdb = f"{float(mdb):+.4f}" if isinstance(mdb, (int, float)) else "n/a"
            out.append(f"| {_n(g.get('sport'))} | {_n(g.get('stat'))} | "
                       f"{_n(g.get('n_folds'))} | {_n(g.get('replicated_verdict'))} | "
                       f"{mdb} | {_n(g.get('any_planted_null_leak'))} |")
    out.append("")
    return out


def _paper_md(pp: Dict, keys: Optional[Set[str]] = None) -> List[str]:
    out = ["## Paper trading (live, units only)", ""]
    if not pp.get("present"):
        return out + ["_No paper ledger on disk._", ""]
    if keys is None:
        out += [f"- **Placements:** {pp['n_total']}  |  **open:** {pp['n_open']}  |  "
                f"**settled:** {pp['n_settled']}  |  **in-game (paper_ingame):** "
                f"{pp['n_ingame']}",
                "- **By channel:** " + ", ".join(f"{k}={v}" for k, v in
                                                  sorted(pp.get("by_channel", {}).items())),
                "- **By market:** " + ", ".join(f"{k}={v}" for k, v in
                                                 sorted(pp.get("by_market", {}).items())),
                "", "_Paper units only; executed=false; CLV-graded; no dollars asserted._",
                ""]
        return out
    rows = {sp: d for sp, d in (pp.get("by_sport", {}) or {}).items() if sp in keys}
    if not rows or not any(d.get("total") for d in rows.values()):
        return out + ["_No paper placements for this sport yet._", ""]
    out += ["| sport | placements | open | settled | in-game | props |",
            "|---|---|---|---|---|---|"]
    for sp, d in sorted(rows.items()):
        out.append(f"| {sp} | {d.get('total', 0)} | {d.get('status:open', 0)} | "
                   f"{d.get('status:settled', 0)} | {d.get('channel:paper_ingame', 0)} | "
                   f"{d.get('market:prop', 0)} |")
    out += ["", "_Paper units only; executed=false; no dollars asserted._", ""]
    return out


def _signals_md(sig: Dict) -> List[str]:
    out = ["## Signal edge registry", ""]
    if not sig.get("present"):
        return out + ["_Signal registry not readable here._", ""]
    line = f"- **Catalogued signals:** {_n(sig.get('n_signals'))}"
    if sig.get("by_status"):
        line += "  (" + ", ".join(f"{k}={v}" for k, v in
                                   sorted(sig["by_status"].items())) + ")"
    out.append(line)
    if sig.get("lab_verdicts"):
        out.append("- **Signal-lab verdicts:** " + ", ".join(
            f"{k}={v}" for k, v in sorted(sig["lab_verdicts"].items())))
    out += ["", "_Registry counts only; read-only; an honest REJECT is a real node._", ""]
    return out


def _master(act: Dict, sports: List[str]) -> str:
    ls = ["---", "tags: [organized, index, activity, moc]", "---", "",
          "# What's Happening -- Live System Activity", "", _BANNER, "",
          "One map of the whole live AI: services up, what's predicting, what shipped "
          "or was rejected, and what is paper-trading right now. Each section links down "
          "to the detail.", ""]
    ls += _services_md(act["services"])
    ls += _predict_md(act["predicting"])
    ls += _calib_md(act["calibration"])
    ls += _improve_md(act["improvement"])
    ls += _paper_md(act["paper"])
    ls += _signals_md(act["signals"])
    ls += ["## Per-sport activity", ""]
    ls += [f"- [[{sp}/_Activity|{sp} activity]]" for sp in sports] or ["_No sports._"]
    ls += ["", "## Cross-sport hubs", "",
           "- [[_Brain|Brain Map]]",
           "- [[_Calibration_Scoreboard|Calibration Scoreboard]]",
           "- [[_Validated_Improvements|Validated Improvements]]",
           "- [[_Coverage|Coverage Map]]",
           "- [[_System/_System_Index|System Map]]", "",
           f"> {_DISCLAIM}", ""]
    return "\n".join(ls) + "\n"


def _sport_note(folder: str, keys: Set[str], act: Dict, has: Dict[str, bool]) -> str:
    ls = ["---", "tags: [organized, activity]", "---", "",
          f"# {folder} -- Live Activity and Calibration", "", _BANNER, "",
          "Per-sport view of the live layer: what is predicting, the calibration / CLV "
          "track record, the ship/reject self-improvement state, and live paper trading. "
          "Honest-empty where this sport has no live activity yet.", ""]
    ls += _predict_md(act["predicting"], keys)
    ls += _calib_md(act["calibration"], keys)
    ls += _improve_md(act["improvement"], keys)
    ls += _paper_md(act["paper"], keys)
    ls += ["## Sport hubs", "",
           "- [[_Index/_Whats_Happening|What's Happening (all sports)]]",
           f"- [[{folder}/_Index|{folder} Index]]"]
    if has.get("model_card"):
        ls.append(f"- [[{folder}/_Model_Card|Model Card]]")
    ls += ["- [[_Calibration_Scoreboard|Calibration Scoreboard]]", "",
           f"> {_DISCLAIM}", ""]
    return "\n".join(ls) + "\n"


def build_activity(organized_root: Optional[Path] = None, write: bool = True,
                   repo_root: Optional[Path] = None) -> Dict:
    """Build the live-activity hubs. Returns a report dict; honest-empty if no stores.

    ``organized_root`` defaults to ``vault/_Organized`` (the live brain). Per-sport
    notes are written only for sport folders that already exist in the tree.
    """
    root = Path(organized_root) if organized_root else _REPO_ROOT / "vault" / "_Organized"
    if not root.is_dir():
        return {"organized_root": str(root), "written": [], "error": "not found"}
    act = collect_activity(repo_root)
    folder_map = act["sport_folder_map"]
    sports = sorted(d.name for d in root.iterdir()
                    if d.is_dir() and not d.name.startswith("_"))
    written: List[str] = []
    idx = root / "_Index"
    if write:
        idx.mkdir(parents=True, exist_ok=True)
    master_path = idx / "_Whats_Happening.md"
    if write:
        master_path.write_text(_master(act, sports), encoding="utf-8")
    written.append(str(master_path))
    for folder in sports:
        keys = {k for k, v in folder_map.items() if v == folder}
        has = {"model_card": (root / folder / "_Model_Card.md").exists()}
        note = _sport_note(folder, keys, act, has)
        sp_path = root / folder / "_Activity.md"
        if write:
            sp_path.write_text(note, encoding="utf-8")
        written.append(str(sp_path))
    return {"organized_root": str(root), "sports": sports,
            "n_written": len(written), "written": written,
            "machinery_ready": act["machinery_ready"]}


def _cli() -> int:
    as_json = "--json" in sys.argv[1:]
    arg = next((a for a in sys.argv[1:] if not a.startswith("-")), None)
    rep = build_activity(Path(arg) if arg else None)
    if as_json:
        print(json.dumps(rep, indent=2))
    else:
        print(f"organized_root : {rep.get('organized_root')}")
        print(f"n_written      : {rep.get('n_written')}")
        for w in rep.get("written", []):
            print(f"  {w}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(_cli())


__all__ = ["build_activity"]
