"""brain_digest.py — Dense aggregate digest generator for vault/_Organized.

ORDERING NOTE: brain_digest runs AFTER vault_organize_multi (the organizer
wipes+rebuilds _Organized, so digests are regenerated each pipeline run):
    organize_all() -> build_digests()

Emits (1) a per-sport _Digest.md with archetype taxonomy table + scheme/trend
titles; (2) a cross-sport _Index/_Cross_Sport_Digest.md with analogue mapping.

Honest framing: intelligence map only; markets efficient; calibration is not a
market advantage.  No win-prob figures, house lines, or return-on-investment
numbers are written to digest notes — only counts, titles, qualitative sigs.

CLI: ``python -m scripts.platformkit.brain_digest [--json]``
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parents[2]

_BANNER = (
    "> **Digest note** — auto-generated by `scripts/platformkit/brain_digest.py`. "
    "Intelligence map only; markets efficient; calibration is not a market advantage. "
    "No win-prob figures, house lines, or return-on-investment numbers appear here — "
    "only counts, titles, and qualitative signatures."
)

# ---------------------------------------------------------------------------
# shape keyword map: two generic shapes; rest = "other"
# ---------------------------------------------------------------------------
_SHAPE_KW: Dict[str, List[str]] = {
    "primary": [
        "high_usage", "high-usage", "creator", "server", "power", "scoring",
        "attacking", "high-scoring", "slam", "grand", "high_variance", "dominant",
        "two-way",
    ],
    "grinder": [
        "defensive", "anchor", "grinder", "prevention", "low-block", "lowblock",
        "counterpuncher", "clay", "pitching", "draw-prone", "balanced", "baseliner",
        "journeyman",
    ],
}
_CANONICAL: Dict[str, Dict[str, str]] = {
    "primary": {"NBA": "High-Usage Creator", "Tennis": "Fast-Court Big Server",
                "MLB": "Power / Run-Scoring", "Soccer": "High-Scoring Attacking"},
    "grinder": {"NBA": "Defensive Anchor", "Tennis": "Counterpuncher / Clay Specialist",
                "MLB": "Pitching-Led / Run-Prevention", "Soccer": "Defensive Low-Block"},
}


def _shape(title: str) -> str:
    low = title.lower().replace(" ", "_").replace("-", "_")
    for s, kws in _SHAPE_KW.items():
        if any(k.replace("-", "_") in low for k in kws):
            return s
    return "other"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _h1(text: str) -> str:
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return ""


def _sig(text: str) -> str:
    pairs: List[Tuple[str, str]] = []
    for m in re.finditer(r"\*\*([^*]+)\*\*\s*:?\s*([^\n|]+)", text):
        k, v = m.group(1).strip().rstrip(":"), m.group(2).strip().rstrip("|").strip()
        if k and v:
            pairs.append((k, v))
        if len(pairs) >= 3:
            break
    if pairs:
        return " | ".join(f"{k}: {v}" for k, v in pairs)
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("-") and len(s) > 4:
            return s[:100]
    return "—"


def _md_files(d: Path) -> List[Path]:
    if not d.is_dir():
        return []
    return sorted(p for p in d.iterdir()
                  if p.is_file() and p.suffix == ".md"
                  and not p.name.startswith("_"))


def _count_teams(d: Path) -> int:
    if not d.is_dir():
        return 0
    subs = [p for p in d.iterdir() if p.is_dir()]
    if subs:
        return len(subs)
    return len([p for p in d.iterdir()
                if p.is_file() and p.suffix == ".md" and not p.name.startswith("_")])


def _arch_records(arch_dir: Path) -> List[Dict[str, object]]:
    recs = []
    for p in _md_files(arch_dir):
        txt = _read(p)
        title = _h1(txt) or p.stem.replace("_", " ")
        recs.append({"title": title, "sig": _sig(txt),
                     "size": len(txt.encode()), "shape": _shape(title)})
    recs.sort(key=lambda r: -r["size"])  # type: ignore[return-value]
    for i, r in enumerate(recs, 1):
        r["rank"] = i
    return recs


# ---------------------------------------------------------------------------
# per-sport digest
# ---------------------------------------------------------------------------

def _sport_digest(sport: str, sdir: Path) -> Tuple[str, Dict[str, object], List[Dict[str, object]]]:
    arcs = _arch_records(sdir / "Archetypes")
    scheme_t = [_h1(_read(p)) or p.stem.replace("_", " ")
                for p in _md_files(sdir / "Schemes")]
    trend_t = [_h1(_read(p)) or p.stem.replace("_", " ")
               for p in _md_files(sdir / "Trends")]
    n_teams = _count_teams(sdir / "Teams")

    ls: List[str] = ["---", "tags: [organized, digest]", "---", "",
                     f"# {sport} — Dense Intelligence Digest", "", _BANNER, "",
                     "## Counts", "",
                     f"- **Teams / entities tracked:** {n_teams}",
                     f"- **Archetypes:** {len(arcs)}",
                     f"- **Schemes / tactical notes:** {len(scheme_t)}",
                     f"- **Trend notes:** {len(trend_t)}", "",
                     "## Archetype Taxonomy", "",
                     "Prevalence proxy = note byte-size rank "
                     "(1 = largest / most documented).", "",
                     "| Rank | Title | Shape | Stat Signature (first 3 fields) |",
                     "|------|-------|-------|----------------------------------|"]
    for r in arcs:
        ls.append(f"| {r['rank']} | {r['title']} | {r['shape']} | {r['sig']} |")
    ls.append("")
    if scheme_t:
        ls += ["## Schemes / Tactics", ""] + [f"- {t}" for t in scheme_t] + [""]
    if trend_t:
        ls += ["## Trend Notes", ""] + [f"- {t}" for t in trend_t] + [""]
    ls += ["## Honest Verdict", "",
           f"This digest maps {sport} archetype/scheme/trend knowledge. "
           "Intelligence reference only — no market advantage claimed. "
           "Model-family and calibration choices transfer; market lines do not.", ""]

    info: Dict[str, object] = {"teams": n_teams, "archetypes": len(arcs),
                               "schemes": len(scheme_t), "trends": len(trend_t)}
    return "\n".join(ls), info, arcs  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# cross-sport digest
# ---------------------------------------------------------------------------

def _cross_digest(per_sport: Dict[str, Dict[str, object]],
                  arch_map: Dict[str, List[Dict[str, object]]]) -> str:
    sports = sorted(per_sport.keys())
    ls: List[str] = [
        "---", "tags: [organized, digest, cross-sport]", "---", "",
        "# Cross-Sport Archetype Transfer Digest", "", _BANNER, "",
        "> **Transfer scope:** What transfers is *model-family* and "
        "*calibration approach* — not outcome distributions, market prices, or "
        "market-advantage claims. Analogue shapes reveal where the same statistical "
        "reasoning applies but each sport's base rates differ.", "",
        "## Analogue Map by Generic Shape", "",
        "Each row = one generic shape; columns show archetypes matched to that shape.", "",
        "| " + " | ".join(["Shape"] + sports) + " |",
        "|" + "|".join(["---"] * (len(sports) + 1)) + "|",
    ]
    for sh in ("primary", "grinder", "other"):
        row = [sh.capitalize()]
        for sp in sports:
            matched = [str(r["title"]) for r in arch_map.get(sp, [])
                       if r.get("shape") == sh]
            if matched:
                row.append("; ".join(matched[:3]))
            else:
                c = _CANONICAL.get(sh, {}).get(sp, "—")
                row.append(f"(canonical: {c})" if c != "—" else "—")
        ls.append("| " + " | ".join(row) + " |")
    ls.append("")

    ls += ["## Per-Sport Archetype Inventory", ""]
    for sp in sports:
        info = per_sport[sp]
        ls += [f"### {sp}", "",
               f"Teams: {info.get('teams','?')} | Archetypes: {info.get('archetypes','?')} | "
               f"Schemes: {info.get('schemes','?')} | Trends: {info.get('trends','?')}", ""]
        arcs = arch_map.get(sp, [])
        if arcs:
            ls += ["| Title | Shape | Stat Signature |",
                   "|-------|-------|----------------|"]
            for r in arcs:
                ls.append(f"| {r['title']} | {r['shape']} | {r['sig']} |")
        else:
            ls.append("*(no archetypes found)*")
        ls.append("")

    ls += ["## Transfer Note (Honest)", "",
           "Cross-sport analogues transfer **what-works** at the modelling layer:\n"
           "- High-volume primary roles → similar usage-skew, Poisson/NegBinom fits.\n"
           "- Grinder / prevention roles → low-event, defensive-stat anchored models.\n"
           "- Surface/environment effects are sport-specific and do NOT transfer.\n"
           "No win-prob figures, house lines, or return-on-investment numbers here.", ""]
    return "\n".join(ls)


# ---------------------------------------------------------------------------
# public API
# ---------------------------------------------------------------------------

def build_digests(organized_root: Optional[Path] = None,
                  write: bool = True) -> Dict[str, object]:
    """Build dense per-sport and cross-sport digest notes.

    Returns dict: {organized_root, per_sport, cross_sport_path, n_written}.
    Run AFTER vault_organize_multi.organize_all().
    """
    root = Path(organized_root) if organized_root else _REPO_ROOT / "vault" / "_Organized"
    if not root.is_dir():
        return {"organized_root": str(root), "per_sport": {},
                "cross_sport_path": None, "n_written": 0,
                "error": f"not found: {root}"}

    per_info: Dict[str, Dict[str, object]] = {}
    arch_map: Dict[str, List[Dict[str, object]]] = {}
    dpaths: Dict[str, Optional[Path]] = {}
    n = 0

    for sdir in sorted(root.iterdir()):
        if not sdir.is_dir() or sdir.name.startswith("_"):
            continue
        sport = sdir.name
        text, info, arcs = _sport_digest(sport, sdir)  # type: ignore[misc]
        per_info[sport] = info
        arch_map[sport] = arcs
        dp = sdir / "_Digest.md"
        if write:
            dp.write_text(text, encoding="utf-8")
            n += 1
        dpaths[sport] = dp if write else None

    idx = root / "_Index"
    cross_path = idx / "_Cross_Sport_Digest.md"
    if write:
        idx.mkdir(parents=True, exist_ok=True)
        cross_path.write_text(_cross_digest(per_info, arch_map), encoding="utf-8")
        n += 1

    return {
        "organized_root": str(root),
        "per_sport": {sp: {**info, "digest_path": str(dpaths.get(sp))}
                      for sp, info in per_info.items()},
        "cross_sport_path": str(cross_path) if write else None,
        "n_written": n,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli() -> None:
    as_json = "--json" in sys.argv[1:]
    rep = build_digests()
    if as_json:
        print(json.dumps(rep, indent=2))
    else:
        print(f"organized_root : {rep['organized_root']}")
        print(f"n_written      : {rep['n_written']}")
        for sp, info in rep.get("per_sport", {}).items():  # type: ignore[union-attr]
            print(f"  {sp}: teams={info['teams']} archetypes={info['archetypes']} "  # type: ignore[index]
                  f"schemes={info['schemes']} trends={info['trends']}")  # type: ignore[index]
        print(f"cross_sport    : {rep.get('cross_sport_path')}")


if __name__ == "__main__":  # pragma: no cover
    _cli()
