"""Generate one intelligence brief per sport, entirely from artifacts on disk.

Run: python scripts/platformkit/intelligence_brief.py [--out DIR]

Every line in a generated brief quotes a value from a named file; nothing is
synthesised beyond arithmetic on quoted numbers.  These are data-status and
calibration briefs -- no edge, ROI or profit claim is made anywhere.  The "as-of"
clock is the newest input artifact mtime, not the wall clock, so regenerating an
unchanged tree reproduces byte-identical output.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
TRACKING_DIR = REPO / "data" / "tracking_reports"
AB_DIR = REPO / "data" / "ab_reports"
OUT_DIR = REPO / "docs" / "evidence" / "intelligence"

GAME_BAR, STALE_DAYS, MAX_LIST, MAX_QUOTES = 10, 7, 40, 12
KNOWN = ("mlb", "nba", "nfl", "soccer", "tennis", "wnba")
# ponytail: hand-maintained alias table; add a row when a new source token shows up.
ALIASES = {"basketball": "nba", "baseball": "mlb", "kxmlbgame": "mlb", "soccer_intl": "soccer"}
VERDICT_TOKENS = ("verdict", "status", "grade", "disclaimer", "caveat", "note", "warning")
BAD_VERDICTS = ("insufficient", "invalid")
FAILURE_RE = re.compile(r"^(\S+)\s+(-?[\d.]+)\s*([<>])\s*(-?[\d.]+)$")
BACKTICK, LEDGERS = chr(96), ("foundry_ledger.jsonl", "decay_ledger.jsonl")
NO_CLAIM = "No edge, ROI or profit claim is made in this brief."
GENERATED_BY = "Generated by `scripts/platformkit/intelligence_brief.py` from artifacts on disk."
INDEX_INTRO = "One brief per sport, from `data/tracking_reports/` and `data/ab_reports/`."
NO_TRACKING = "No report under `data/tracking_reports/` maps to {0}. Tracking status is UNKNOWN."
NO_MODEL = "No walk-forward or calibration file in `data/ab_reports/` names {0}. Status: UNKNOWN."
NO_SIGNAL = "No row for this sport in the `data/ab_reports/` signal ledgers. Status: UNKNOWN."
NO_LIMITS = "No failing metric and no INSUFFICIENT/INVALID verdict in the artifacts read."
PENDING_NOTE = "Pending fixes are exactly the `failures` entries below; nothing else on disk."
QUESTIONS_INTRO = (f"Derived mechanically -- failing thresholds, the {GAME_BAR}-game bar, "
                   f"and the {STALE_DAYS}-day freshness bar.")


def canon(token: Any) -> str | None:
    """Map a raw source token to a canonical sport key, or None if unknown."""
    key = str(token).strip().lower()
    key = ALIASES.get(key, key)
    return key if key in KNOWN else None


def rel(path: Path) -> str:
    """Repo-relative posix path, used as the citation for every quoted value."""
    try:
        return path.resolve().relative_to(REPO).as_posix()
    except ValueError:
        return path.as_posix()


def _load(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _quote(value: Any) -> str:
    text = str(value).replace(BACKTICK, "'").replace("\n", " ").strip()
    return BACKTICK + (text[:220] + "..." if len(text) > 220 else text) + BACKTICK


def _table(headers: list[str], rows: list[str]) -> list[str]:
    return ["| " + " | ".join(headers) + " |",
            "| " + " | ".join("---" for _ in headers) + " |"] + rows


def _section(heading: str, body: list[str], fallback: str) -> list[str]:
    return ["", f"## {heading}", ""] + (body or [fallback])


def worst_failure(failures: list[str]) -> str | None:
    """Return the failure whose value misses its own threshold by the widest margin."""
    def gap(text: str) -> float:
        match = FAILURE_RE.match(text.strip())
        if match is None:
            return -1.0
        value, threshold = float(match.group(2)), float(match.group(4))
        return abs(value - threshold) / abs(threshold) if threshold else abs(value - threshold)
    return max(failures, key=gap) if failures else None


def collect_tracking(root: Path) -> dict[str, list[dict[str, Any]]]:
    """Read data/tracking_reports/<dir>/*.json; the directory names the sport."""
    out: dict[str, list[dict[str, Any]]] = {}
    for path in sorted(root.glob("*/*.json")) if root.is_dir() else []:
        data = _load(path)
        sport = canon(path.parent.name) if isinstance(data, dict) else None
        if sport is None:
            continue
        out.setdefault(sport, []).append({
            "file": rel(path), "dir_token": path.parent.name, "file_sport": data.get("sport"),
            "passed": bool(data.get("passed")), "n_frames": data.get("n_frames"),
            "failures": [str(item) for item in (data.get("failures") or [])]})
    return out


def _walk(node: Any, path: str, sport: str | None, out: list[tuple[str | None, str, str]]) -> None:
    """Collect (sport, dotted_path, string_value) for every verdict-like leaf."""
    if isinstance(node, list):
        for value in node[:MAX_LIST]:
            _walk(value, path + "[]", sport, out)
    if not isinstance(node, dict):
        return
    here = canon(node.get("sport")) or canon(node.get("league")) or sport
    for key, value in node.items():
        child = f"{path}.{key}" if path else str(key)
        if isinstance(value, (dict, list)):
            _walk(value, child, canon(key) or here, out)
        elif isinstance(value, str) and any(t in child.lower() for t in VERDICT_TOKENS):
            out.append((here, child, value))


def collect_models(ab_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Quote every verdict-like string in data/ab_reports/*.json, scoped by sport."""
    out: dict[str, list[dict[str, Any]]] = {}
    for path in sorted(ab_dir.glob("*.json")) if ab_dir.is_dir() else []:
        data = _load(path)
        if data is None:
            continue
        found: list[tuple[str | None, str, str]] = []
        # A report with no in-body sport field falls back to its own filename.
        stem = next((s for t in re.split(r"[^A-Za-z0-9]+", path.stem) if (s := canon(t))), None)
        _walk(data, "", stem, found)
        counts: dict[str, Counter] = {}
        for sport, key_path, value in found:
            if sport is not None:
                counts.setdefault(sport, Counter())[(key_path, value)] += 1
        for sport, counter in sorted(counts.items()):
            out.setdefault(sport, []).extend(
                {"file": rel(path), "path": key_path, "value": value, "count": count}
                for (key_path, value), count in
                sorted(counter.items(), key=lambda item: (-item[1], item[0]))[:MAX_QUOTES])
    return out


def collect_signals(ab_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Read the foundry and decay JSONL ledgers; last row per (sport, signal) wins."""
    out: dict[str, list[dict[str, Any]]] = {}
    for name in LEDGERS:
        path = ab_dir / name
        latest: dict[tuple[str, str], dict[str, Any]] = {}
        for line in path.read_text(encoding="utf-8").splitlines() if path.is_file() else []:
            try:
                item = json.loads(line)
            except ValueError:
                continue
            if not isinstance(item, dict):
                continue
            sport, signal = canon(item.get("sport")), item.get("signal")
            if sport is None or not isinstance(signal, str):
                continue
            field = "status" if item.get("status") is not None else "grade"
            latest[(sport, signal)] = {"file": rel(path), "signal": signal, "field": field,
                                       "state": str(item.get(field)), "lift": item.get("lift")}
        for (sport, _signal), row in sorted(latest.items()):
            out.setdefault(sport, []).append(row)
    return out


def _open_questions(sport: str, tracking: list, models: list, signals: list,
                    mtimes: dict[str, datetime], as_of: datetime | None) -> list[str]:
    """Derive open questions mechanically from the thresholds and the two bars."""
    questions: list[str] = []
    metrics: Counter = Counter()
    for row in tracking:
        for text in row["failures"]:
            match = FAILURE_RE.match(text.strip())
            metrics[match.group(1) if match else text] += 1
    questions += [f"Metric {_quote(metric)} misses its threshold in {count} of {len(tracking)} "
                  "tracking report(s) under `data/tracking_reports/`. What fix closes it?"
                  for metric, count in sorted(metrics.items())]
    if len(tracking) < GAME_BAR:
        questions.append(f"Only {len(tracking)} tracking report(s) on disk for {sport}; the "
                         f"{GAME_BAR}-game bar is not met. What blocks collecting more?")
    if not models:
        questions.append(f"No file in `data/ab_reports/` names {sport}. Model status is UNKNOWN, not good.")
    if not signals:
        questions.append(f"No {sport} row in the foundry/decay ledgers under `data/ab_reports/`. "
                         "Signal status is UNKNOWN, not good.")
    for name in sorted({row["file"] for row in tracking + models + signals}) if as_of else []:
        age = as_of - mtimes.get(name, as_of)
        if age > timedelta(days=STALE_DAYS):
            questions.append(f"`{name}` is {age.days} days older than the newest artifact "
                             f"(bar: {STALE_DAYS} days). Is it still current?")
    return questions


def _known_limits(tracking: list, models: list) -> list[str]:
    """Every failing metric and every INSUFFICIENT/INVALID verdict, quoted verbatim."""
    limits: list[str] = []
    for row in tracking:
        limits += [f"{_quote(text)} -- `failures` in `{row['file']}`" for text in row["failures"]]
        if row["file_sport"] is not None and canon(row["file_sport"]) != canon(row["dir_token"]):
            limits.append(f"Directory says `{row['dir_token']}` but the file's `sport` field says "
                          f"{_quote(row['file_sport'])} -- `{row['file']}`")
    return limits + [f"{_quote(row['value'])} -- `{row['path']}` in `{row['file']}`" for row in models
                     if any(bad in str(row["value"]).lower() for bad in BAD_VERDICTS)]


def _preamble(title: str, intro: str, as_of: datetime | None) -> list[str]:
    stamp = as_of.strftime("%Y-%m-%dT%H:%M:%SZ") if as_of else "no artifacts"
    return [f"# {title}", "", intro,
            f"As-of clock (newest input artifact mtime): {stamp}. {NO_CLAIM}"]


def _tracking_lines(tracking: list) -> list[str]:
    """Section 1 body: pass rate, the per-report table, then the pending-fix list."""
    passed = sum(1 for row in tracking if row["passed"])
    rows = [f"| `{row['file']}` | {row['n_frames']} | {row['passed']} | "
            f"{_quote(worst) if (worst := worst_failure(row['failures'])) else '(none)'} |"
            for row in sorted(tracking, key=lambda item: item["file"])]
    pending = sorted({(text, row["file"]) for row in tracking for text in row["failures"]})
    return ([f"Reports on disk: {len(tracking)}. Pass rate: {passed}/{len(tracking)} "
             "(the `passed` field of each file).", ""]
            + _table(["report file", "n_frames", "passed", "worst failing metric (verbatim)"], rows)
            + ["", PENDING_NOTE, ""]
            + [f"- {_quote(text)} -- `{name}`" for text, name in pending])


def render_sport(sport: str, bundle: dict[str, Any]) -> str:
    """Render one sport brief; every bullet cites the file it was read from."""
    tracking = bundle["tracking"].get(sport, [])
    models = bundle["models"].get(sport, [])
    signals = bundle["signals"].get(sport, [])
    model_rows = _table(["source file", "field", "value (verbatim)", "occurrences"],
                        [f"| `{r['file']}` | `{r['path']}` | {_quote(r['value'])} | {r['count']} |"
                         for r in sorted(models, key=lambda r: (r["file"], r["path"], r["value"]))])
    signal_rows = _table(["signal", "field", "state (verbatim)", "lift", "source file"],
                         [f"| `{r['signal']}` | `{r['field']}` | {_quote(r['state'])} | "
                          f"{r['lift']} | `{r['file']}` |" for r in signals])
    questions = [f"- {text}" for text in _open_questions(
        sport, tracking, models, signals, bundle["mtimes"], bundle["as_of"])]
    return "\n".join(
        _preamble(f"Intelligence brief -- {sport}", GENERATED_BY, bundle["as_of"])
        + _section("1. Tracking status", _tracking_lines(tracking) if tracking else [],
                   NO_TRACKING.format(sport))
        + _section("2. Model status", model_rows if models else [], NO_MODEL.format(sport))
        + _section("3. Signals", signal_rows if signals else [], NO_SIGNAL)
        + _section("4. Known limits", [f"- {t}" for t in _known_limits(tracking, models)], NO_LIMITS)
        + _section("5. Open questions", [QUESTIONS_INTRO, ""]
                   + (questions or ["- None triggered by the bars above."]), "")) + "\n"


def render_index(sports: list[str], bundle: dict[str, Any]) -> str:
    """Render the index that links every per-sport brief."""
    rows = [f"| [{s}]({s}.md) | {len(bundle['tracking'].get(s, []))} | "
            f"{sum(1 for row in bundle['tracking'].get(s, []) if row['passed'])} | "
            f"{len(bundle['models'].get(s, []))} | {len(bundle['signals'].get(s, []))} |"
            for s in sports]
    return "\n".join(_preamble("Intelligence briefs", INDEX_INTRO, bundle["as_of"]) + [""] + _table(
        ["sport", "tracking reports", "passed", "ab_reports quotes", "signal ledger rows"],
        rows)) + "\n"


def build(tracking_dir: Path = TRACKING_DIR, ab_dir: Path = AB_DIR) -> dict[str, Any]:
    """Read every input artifact once and return the bundle the renderers consume."""
    paths = list(tracking_dir.glob("*/*.json")) if tracking_dir.is_dir() else []
    paths += (list(ab_dir.glob("*.json")) + list(ab_dir.glob("*.jsonl"))) if ab_dir.is_dir() else []
    mtimes = {rel(p): datetime.fromtimestamp(p.stat().st_mtime, timezone.utc) for p in paths}
    return {"tracking": collect_tracking(tracking_dir), "models": collect_models(ab_dir),
            "signals": collect_signals(ab_dir), "mtimes": mtimes,
            "as_of": max(mtimes.values()) if mtimes else None}


def write_briefs(out_dir: Path = OUT_DIR, tracking_dir: Path = TRACKING_DIR,
                 ab_dir: Path = AB_DIR) -> list[Path]:
    """Write <sport>.md for every known or discovered sport, plus index.md."""
    bundle = build(tracking_dir, ab_dir)
    sports = sorted(set(KNOWN) | set(bundle["tracking"]) | set(bundle["models"]) | set(bundle["signals"]))
    pages = [(f"{s}.md", render_sport(s, bundle)) for s in sports] + [
        ("index.md", render_index(sports, bundle))]
    out_dir.mkdir(parents=True, exist_ok=True)
    written = [out_dir / name for name, _ in pages]
    for path, (_name, text) in zip(written, pages):
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
    return written


def main() -> None:
    """Regenerate every brief and print the paths written."""
    parser = argparse.ArgumentParser(description="Generate per-sport intelligence briefs.")
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    print("\n".join(rel(path) for path in write_briefs(parser.parse_args().out)))


if __name__ == "__main__":
    main()
