"""scripts.platformkit.new_sport_scaffold -- generate a new sport's seam skeleton.

Stamps domains/<sport>/{__init__,feature_spec,ingest_manifest}.py from templates so a
new sport plugs straight into the census (data_registry), the parity matrix, and the
train==inference feature_spec seam. The generated feature_spec/manifest are valid out
of the box (their validators pass) -- you then edit the fields/sources to match the
real adapter and prove byte-equal parity with a guarded real-adapter test.

THE 9-STEP PLAYBOOK to add a sport (e.g. NFL):
  1. ingest its corpora to data/domains/<sport>/ (games, odds, ...).
  2. `python -m data_registry.inventory scan` -- confirm the census sees non-empty corpora.
  3. scaffold the seam:  python -m scripts.platformkit.new_sport_scaffold <sport> --write
  4. edit domains/<sport>/feature_spec.py fields to match the adapter's base matrix.
  5. edit domains/<sport>/ingest_manifest.py sources + leak_class + SLA.
  6. add the sport to scripts.platformkit.parity_matrix.SPORTS; run it -> all cells green.
  7. write a guarded real-adapter parity test (see tests/platformkit/test_feature_spec_nba.py).
  8. build a depth as-of builder via scripts.platformkit.asof_common; eval + gate it.
  9. record the honest gate verdict (REJECT/MATCH) in scripts.platformkit.reject_ledger.

CLI: python -m scripts.platformkit.new_sport_scaffold <sport>          # dry-run (prints)
     python -m scripts.platformkit.new_sport_scaffold <sport> --write  # writes files

PURE offline codegen. ASCII only. Refuses to overwrite existing files (use --force).
"""
from __future__ import annotations

import argparse
import string
import sys
from pathlib import Path
from typing import Dict, List, Optional

_REPO_ROOT = Path(__file__).resolve().parents[2]

_INIT_TMPL = string.Template(
    '"""domains.$sport -- generated sport adapter package (SCAFFOLD)."""\n')

_FEATURE_SPEC_TMPL = string.Template('''"""domains.$sport.feature_spec -- generated base-feature contract (SCAFFOLD).

Generated by scripts.platformkit.new_sport_scaffold. Edit the fields to match the
$sport adapter's base matrix, then prove parity with a guarded real-adapter test.
ACCURACY ONLY -- NO MARKET EDGE CLAIMED.
"""
from __future__ import annotations

from typing import List, Tuple

import numpy as np
import pandas as pd

from scripts.platformkit.feature_spec_core import (
    CAST_FLOAT,
    OP_DIFF,
    FeatureField,
    FeatureSpec,
    build_base_matrix,
)

${SPORT_UPPER}_BASE_SPEC = FeatureSpec(
    sport="$sport",
    version="$sport-base-v0",
    fields=(
$fields_block
    ),
)


def build_${sport}_base(df: pd.DataFrame) -> Tuple[np.ndarray, List[str]]:
    return build_base_matrix(${SPORT_UPPER}_BASE_SPEC, df)


def catalog() -> List[str]:
    return ${SPORT_UPPER}_BASE_SPEC.col_names()
''')

_MANIFEST_TMPL = string.Template('''"""domains.$sport.ingest_manifest -- generated provenance contract (SCAFFOLD).

Edit the sources / leak_class / SLA to match the real $sport corpora.
"""
from __future__ import annotations

from scripts.platformkit.ingest_manifest_core import (
    LEAK_POST_GAME,
    LEAK_PRE_GAME,
    LEAK_REFERENCE,
    IngestManifest,
    IngestSource,
)

${SPORT_UPPER}_MANIFEST = IngestManifest(
    sport="$sport",
    sources=(
$sources_block
    ),
)
''')

# Toy defaults: a rating-diff + a rest field; a pregame schedule + odds source.
_TOY_FIELDS: List[Dict] = [
    {"name": "rating_diff", "source": "home_rating", "default": 1500.0, "source2": "away_rating"},
    {"name": "rest_days", "source": "rest_days", "default": 5.0},
]
_TOY_SOURCES: List[Dict] = [
    {"corpus": "games", "leak": "LEAK_PRE_GAME", "sla": 1440,
     "desc": "schedule spine; result is the post-game label"},
    {"corpus": "odds", "leak": "LEAK_PRE_GAME", "sla": 120,
     "desc": "moneylines for devig + CLV"},
]


def _render_field(f: Dict) -> str:
    parts = [repr(f["name"]), repr(f["source"]), f"default={f.get('default')!r}", "cast=CAST_FLOAT"]
    if f.get("source2"):
        parts += [f"source2={f['source2']!r}", "op=OP_DIFF"]
    return "        FeatureField(" + ", ".join(parts) + "),"


def _render_source(s: Dict) -> str:
    return (f'        IngestSource("{s["corpus"]}", {s["leak"]}, '
            f'sla_minutes={s["sla"]}, description="{s["desc"]}"),')


def render_all(sport: str, fields: Optional[List[Dict]] = None,
               sources: Optional[List[Dict]] = None) -> Dict[str, str]:
    """Return {relative_filename: file_text} for the scaffolded sport."""
    fields = fields if fields is not None else _TOY_FIELDS
    sources = sources if sources is not None else _TOY_SOURCES
    sub = {"sport": sport, "SPORT_UPPER": sport.upper()}
    return {
        "__init__.py": _INIT_TMPL.substitute(sub),
        "feature_spec.py": _FEATURE_SPEC_TMPL.substitute(
            fields_block="\n".join(_render_field(f) for f in fields), **sub),
        "ingest_manifest.py": _MANIFEST_TMPL.substitute(
            sources_block="\n".join(_render_source(s) for s in sources), **sub),
    }


def scaffold(sport: str, dest_root: Path, fields: Optional[List[Dict]] = None,
             sources: Optional[List[Dict]] = None, force: bool = False) -> List[Path]:
    """Write the scaffold under dest_root/domains/<sport>/; return written paths."""
    pkg = Path(dest_root) / "domains" / sport
    pkg.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for fname, text in render_all(sport, fields, sources).items():
        target = pkg / fname
        if target.exists() and not force:
            raise FileExistsError(f"refusing to overwrite {target} (use force=True)")
        target.write_text(text, encoding="ascii")
        written.append(target)
    return written


def _cli(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="generate a new sport's seam skeleton")
    ap.add_argument("sport")
    ap.add_argument("--write", action="store_true", help="write files (default: dry-run)")
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    ap.add_argument("--dest", default=str(_REPO_ROOT))
    args = ap.parse_args(argv)

    files = render_all(args.sport)
    if not args.write:
        print(f"[dry-run] would create under {args.dest}/domains/{args.sport}/:")
        for fname in files:
            print(f"  {fname} ({len(files[fname])} bytes)")
        print("re-run with --write to create them.")
        return 0
    written = scaffold(args.sport, Path(args.dest), force=args.force)
    print(f"scaffolded {args.sport}:")
    for p in written:
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
