"""vault_organize_multi.py — Canonical multi-sport Obsidian vault organizer.

Builds a deduped, person-free, DENSE organized tree under vault/_Organized/ covering
NBA, MLB, Soccer, and Tennis.  Non-destructive: only writes under out_dir; never
touches source vault files.  Honesty note: an intelligence MAP, not a betting edge;
markets efficient; calibration is not edge.

CLI: ``python -m scripts.platformkit.vault_organize_multi [--json]``
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.platformkit.vault_organize import (   # noqa: E402
    _collect_players,
    _read_safe,
    _write,
)
from scripts.platformkit.vault_person_free_lint import (  # noqa: E402
    _fmt_bytes,
    lint_vault,
)
from scripts.platformkit.vault_sources import (    # noqa: E402
    SportSpec,
    source_specs,
    parse_archetype_from_body,
)

_UNASSIGNED = "_Unassigned"


# --------------------------------------------------------------------------- #
# dense _Team hub builder
# --------------------------------------------------------------------------- #

def _build_team_hub(team: str, source_text: Optional[str],
                    recs: List[dict]) -> str:
    """Dense _Team.md: source note content + optional archetype roster histogram."""
    arch_hist: Dict[str, int] = {}
    for r in recs:
        arch = r.get("archetype", "") or "Unknown"
        arch_hist[arch] = arch_hist.get(arch, 0) + 1

    lines = [
        "---\ntags: [organized, team, hub]\n---",
        f"# {team} — Team Hub\n",
        "> Dense canonical hub. Auto-generated by "
        "`scripts/platformkit/vault_organize_multi.py`. "
        "Intelligence map only — markets efficient; calibration is not edge.\n",
    ]

    if source_text:
        lines.append("## Source Intelligence\n")
        lines.append(source_text.strip())
        lines.append("")

    if recs:
        lines.append(f"\n## Roster ({len(recs)} canonical player(s))\n")
        for r in sorted(recs, key=lambda x: x["stem"]):
            arch = r.get("archetype", "") or ""
            suffix = f" — {arch}" if arch else ""
            lines.append(f"- [[{r['stem']}]]{suffix}")
        if arch_hist:
            lines.append("\n### Archetype Histogram\n")
            for arch, cnt in sorted(arch_hist.items(), key=lambda kv: (-kv[1], kv[0])):
                lines.append(f"| {arch} | {cnt} |")

    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# per-sport organizer
# --------------------------------------------------------------------------- #

def _copy_category(src_dirs: List[Path], out_cat: Path) -> int:
    """Copy .md files from all src_dirs into out_cat/; return count written."""
    n = 0
    for src in src_dirs:
        if not src.is_dir():
            continue
        for path in sorted(src.rglob("*.md")):
            if not path.is_file():
                continue
            text = _read_safe(path)
            if text is None:
                continue
            _write(out_cat / path.relative_to(src), text)
            n += 1
    return n


def _organize_sport(spec: SportSpec, sport_out: Path) -> Dict:
    """Build the <SPORT>/ subtree.  Returns per-sport stats dict."""
    cats: Dict[str, int] = {}
    n_players = 0
    n_teams = 0
    dupes = 0
    skipped = 0

    # ---- player/team notes ------------------------------------------------
    canonical: Dict[str, dict] = {}
    by_team: Dict[str, List[dict]] = {}

    if spec.players_dir is not None and not spec.is_solo:
        # team sport with player notes (NBA)
        canonical, dupes, skipped = _collect_players(spec.players_dir)
        n_players = len(canonical)
        for rec in canonical.values():
            team = rec.get("team") or _UNASSIGNED
            by_team.setdefault(team, []).append(rec)
        # write player notes under Teams/<team>/
        for rec in sorted(canonical.values(), key=lambda r: r["stem"]):
            team = rec.get("team") or _UNASSIGNED
            _write(sport_out / "Teams" / team / f"{rec['stem']}.md", rec["text"])

    elif spec.is_solo and spec.players_dir is not None:
        # solo sport with player notes (Tennis if Players/ present)
        canonical, dupes, skipped = _collect_players(spec.players_dir)
        n_players = len(canonical)
        for rec in sorted(canonical.values(), key=lambda r: r["stem"]):
            _write(sport_out / "Players" / f"{rec['stem']}.md", rec["text"])

    # ---- team hubs --------------------------------------------------------
    if spec.teams_dir is not None and spec.teams_dir.is_dir():
        for team_path in sorted(spec.teams_dir.glob("*.md")):
            if not team_path.is_file():
                continue
            team_name = team_path.stem
            source_text = _read_safe(team_path)
            recs = by_team.get(team_name, [])
            hub = _build_team_hub(team_name, source_text, recs)
            _write(sport_out / "Teams" / team_name / "_Team.md", hub)
            n_teams += 1

    # ---- intel categories -------------------------------------------------
    cats["Archetypes"] = _copy_category(spec.archetype_dirs, sport_out / "Archetypes")
    cats["Schemes"] = _copy_category(spec.scheme_dirs, sport_out / "Schemes")
    cats["Trends"] = _copy_category(spec.trend_dirs, sport_out / "Trends")
    cats["Reference"] = _copy_category(spec.reference_dirs, sport_out / "Reference")

    return {
        "n_players": n_players,
        "n_teams": n_teams,
        "duplicates_collapsed": dupes,
        "skipped": skipped,
        "categories": cats,
    }


# --------------------------------------------------------------------------- #
# per-sport _Index.md
# --------------------------------------------------------------------------- #

def _write_sport_index(spec: SportSpec, sport_out: Path, stats: Dict) -> None:
    cats = stats["categories"]
    lines = [
        "---\ntags: [organized, index]\n---",
        f"# {spec.name} — Intelligence Index\n",
        "> Intelligence map. Markets efficient; calibration is not edge. "
        "Auto-generated by `scripts/platformkit/vault_organize_multi.py`.\n",
        f"**Teams:** {stats['n_teams']}  |  **Players:** {stats['n_players']}  |  "
        + "  ".join(f"**{c}:** {n}" for c, n in sorted(cats.items()) if n > 0),
        "",
    ]
    if stats["n_teams"] > 0:
        lines.append("## Teams\n")
        teams_dir = sport_out / "Teams"
        if teams_dir.is_dir():
            for t in sorted(d.name for d in teams_dir.iterdir() if d.is_dir()):
                lines.append(f"- [[Teams/{t}/_Team|{t}]]")
    for cat, n in sorted(cats.items()):
        if n > 0:
            lines.append(f"\n## {cat} ({n})\n")
            cat_dir = sport_out / cat
            if cat_dir.is_dir():
                for f in sorted(cat_dir.rglob("*.md")):
                    rel = f.relative_to(cat_dir).as_posix()
                    lines.append(f"- [[{cat}/{rel}|{f.stem}]]")
    _write(sport_out / "_Index.md", "\n".join(lines) + "\n")


# --------------------------------------------------------------------------- #
# brain (_Index/_Brain.md)
# --------------------------------------------------------------------------- #

def _write_brain(out_dir: Path, sport_stats: Dict[str, Dict]) -> None:
    hdr = ("---\ntags: [organized, brain, moc]\n---\n"
           "# Organized Vault — Brain (Multi-Sport)\n\n"
           "> **An intelligence MAP, not a betting edge; markets efficient; "
           "calibration is not edge.**\n> Non-destructive copy — live vault/ untouched.\n\n"
           "## Sports\n")
    rows = []
    for sport, stats in sorted(sport_stats.items()):
        cats = stats["categories"]
        cs = ", ".join(f"{c}={n}" for c, n in sorted(cats.items()) if n > 0)
        rows.append(f"- **[[{sport}/_Index|{sport}]]** — "
                    f"{stats['n_teams']} teams · {stats['n_players']} players · {cs}")
    _write(out_dir / "_Index" / "_Brain.md", hdr + "\n".join(rows) + "\n")


# --------------------------------------------------------------------------- #
# public entrypoint
# --------------------------------------------------------------------------- #

def organize_all(vault_dir: Optional[Path] = None,
                 out_dir: Optional[Path] = None) -> Dict:
    """Build the full multi-sport organized tree. Returns a structured report dict."""
    vault_dir = Path(vault_dir) if vault_dir is not None else (_REPO_ROOT / "vault")
    out_dir = Path(out_dir) if out_dir is not None else (vault_dir / "_Organized")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    before = lint_vault(vault_dir)

    specs = source_specs(vault_dir)
    sport_stats: Dict[str, Dict] = {}

    for spec in specs:
        sport_out = out_dir / spec.name
        stats = _organize_sport(spec, sport_out)
        _write_sport_index(spec, sport_out, stats)
        sport_stats[spec.name] = stats

    _write_brain(out_dir, sport_stats)

    after = lint_vault(out_dir)
    after_matchup_leaks = after["leak_counts"].get("matchup_vs", 0)

    return {
        "vault_dir": str(vault_dir),
        "out_dir": str(out_dir),
        "before": {
            "n_files": before["n_files"],
            "total_bytes": before["total_bytes"],
            "person_leaks": sum(before["leak_counts"].values()),
            "matchup_vs_leaks": before["leak_counts"].get("matchup_vs", 0),
        },
        "after": {
            "n_files": after["n_files"],
            "total_bytes": after["total_bytes"],
            "person_leaks": sum(after["leak_counts"].values()),
            "matchup_vs_leaks": after_matchup_leaks,
        },
        "per_sport": sport_stats,
    }


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def main(argv: Optional[List[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if "--help" in argv or "-h" in argv:
        print(__doc__)
        return 0
    vault_dir_arg = next((a for a in argv if not a.startswith("-")), None)
    vault_dir = Path(vault_dir_arg) if vault_dir_arg else None
    rep = organize_all(vault_dir=vault_dir)
    if "--json" in argv:
        print(json.dumps(rep, indent=2))
        return 0
    b, a = rep["before"], rep["after"]
    print(f"source : {rep['vault_dir']}")
    print(f"out    : {rep['out_dir']}")
    print(f"\n{'':12}{'files':>8}{'size':>12}{'leaks':>10}{'matchup_vs':>12}")
    print(f"{'BEFORE':12}{b['n_files']:>8}{_fmt_bytes(b['total_bytes']):>12}"
          f"{b['person_leaks']:>10}{b['matchup_vs_leaks']:>12}")
    print(f"{'AFTER':12}{a['n_files']:>8}{_fmt_bytes(a['total_bytes']):>12}"
          f"{a['person_leaks']:>10}{a['matchup_vs_leaks']:>12}")
    print()
    for sport, stats in sorted(rep["per_sport"].items()):
        cats = stats["categories"]
        cat_str = " ".join(f"{c[:3]}={n}" for c, n in sorted(cats.items()))
        print(f"  {sport:10} teams={stats['n_teams']:>4}  players={stats['n_players']:>4}"
              f"  dupes_collapsed={stats['duplicates_collapsed']:>3}  {cat_str}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
