"""domains.nfl.feature_spec -- generated base-feature contract (SCAFFOLD).

Generated by scripts.platformkit.new_sport_scaffold. Edit the fields to match the
nfl adapter's base matrix, then prove parity with a guarded real-adapter test.
ACCURACY ONLY -- NO MARKET EDGE CLAIMED.
"""
from __future__ import annotations

from typing import List, Tuple

import numpy as np
import pandas as pd

from scripts.platformkit.feature_spec_core import (
    CAST_FLOAT,
    OP_DIFF,
    FeatureField,
    FeatureSpec,
    build_base_matrix,
)

NFL_BASE_SPEC = FeatureSpec(
    sport="nfl",
    version="nfl-base-v0",
    fields=(
        FeatureField('rating_diff', 'home_rating', default=1500.0, cast=CAST_FLOAT, source2='away_rating', op=OP_DIFF),
        FeatureField('rest_days', 'rest_days', default=5.0, cast=CAST_FLOAT),
    ),
)


def build_nfl_base(df: pd.DataFrame) -> Tuple[np.ndarray, List[str]]:
    return build_base_matrix(NFL_BASE_SPEC, df)


def catalog() -> List[str]:
    return NFL_BASE_SPEC.col_names()
